### DISCUSSION TITLE
Rime 输入法的双拼

### DISCUSSION THREAD

**Discussion by resigned1292** [rime/home#1017] [Q&A] [answered]
我使用 Rime 的小鹤双拼，默认情况下，打出的字母会变成完整的拼音，例如：输入 hc 会变成 hao，这个功能在我一开始学习小鹤双拼的时候还是蛮好用的，但是我现在熟悉小鹤双拼了，这个功能总是让候选框一跳一跳的，虽然不影响正常使用，但是看上去有点分散注意了，而且并不是“所见即所得”，有什么办法让它直接显示我所输入的字母吗？

**Comment by lotem** [comment, marked as answer]
自己設置一下

```yaml
# double_pinyin_flypy.custom.yaml
patch:
  translator/preedit_format: []
```

**Comment by resigned1292** [comment]
```yaml
patch:
  translator/preedit_format:
    "iu": "q"
    "ei": "w"
    "uan": "r"
    "ue": "t"
    "ve": "t"
    "un": "y"
    "sh": "u"
    "ch": "i"
    "uo": "o"
    "ie": "p"
    "ong": "s"
    "iong": "s"
    "ai": "d"
    "en": "f"
    "eng": "g"
    "ang": "h"
    "an": "j"
    "uai": "k"
    "ing": "k"
    "uang": "l"
    "iang": "l"
    "ou": "z"
    "ua": "x"
    "ia": "x"
    "ao": "c"
    "ui": "v"
    "zh": "v"
    "in": "b"
    "iao": "n"
    "ian": "m"
```
