### DISCUSSION TITLE
形碼輸入法簡拼(首拼)實現與改善

### DISCUSSION THREAD

**Discussion by ianzhuo** [rime/home#1038] [Q&A]
小弟參考佛振的速成方案，透過 script_translator 與 table_translator@fixed建立一份形碼方案(如下)，
並加入拼寫規則`'derive/^(\w).+$/$1/'`，實現了同時滿足單字固頂、詞句調頻、智能語句，簡拼輸入等功能的形碼輸入方案。
該規則實現了接近於明月拼音中`abbrev/^([a-z]).+$/$1/`的簡拼調用功能。

這份方案，平時既可table_translator使用固訂單字輸入，需要使用詞語時，也可善用script_translator的優點，進行智能組句，只需要輸入一次該詞句，未來即可直接以首拼方式調用該詞句，大幅降低打錯字的可能性，但目前發現一個很大的缺點，就是不能導入外部詞庫，經實測，於導入預設八股文詞庫後，會造成運算效能十分低落，想是可能`derive`拼寫規則匹配到整個字典檔的關係。

不知道有無可改進本方案之效能問題的作法呢？

```
translators:
- punct_translator
- script_translator
- table_translator@fixed

filters:
- simplifier
- uniquifier
#- single_char_filter

speller:
alphabet: zyxwvutsrqponmlkjihgfedcba
delimiter: " ;"
  algebra:
    - 'derive/^(\w).+$/$1/'

translator:
  dictionary: liur_express.extended
  db_class: tabledb
  enable_user_dict: true
  enable_sentence: true
  enable_encoder: false #是否開啓自動造詞〔僅table_translator有效〕
  encode_commit_history: false
  max_phrase_length: 10
  enable_completion: false
  comment_format:
  disable_user_dict_for_patterns:
    - "^[',.].*$"
  initial_quality: 10

fixed:
  __include: /translator
  enable_encoder: false
  enable_user_dict: false
  initial_quality: 1000
```
