### DISCUSSION TITLE
如何手动调整词频?

### DISCUSSION THREAD

**Discussion by pdog18** [rime/home#1040] [Q&A] [answered]
我在输入「y」的时候, 希望出现的首个词是「有」, 但是目前出现的是「又」.
类似的就是我输入
* 「sm」的时候希望出现的是「什么」, 而不是「售卖」.
* 「zhong」希望「中」, 而不是「种」
* 「z」希望是「在」,而不是其他的内容

用哪种方式来修改鼠须管的配置是最合适的?

-----------
我看过文档, 也找过 issue 中一些方案, 好像都没有效果, 另外对 settings 种的内容进行修改, 部署以后, 输入法依旧是需要切换到其他应用程序种输入才会展示修改后的效果吗?(例: 在 chrome 修改部署后, 仍旧在 chrome 种输入没有改变,需要另外打开 vscode , 才会展示出修改后的效果)

**Comment by pdog18** [comment]
我目前用的是袖珍简体方案
现在通过这样的方案似乎能实现, 不知道是不是错误的用法:
1. 创建了`pinyin_simp.extended.dict.yaml` 文件,
    ```
    name: pinyin_simp.extended   # 命名会在 pinyin_simp.schema.yaml 中使用到
    version: "0.1"
    sort: by_weight
    
    import_tables:
      - pinyin_simp  # 导入pinyin_simp.dict.yaml
    ...
    ```
2. 在  `pinyin_simp.schema.yaml` 中, 设置 `dictionary` 为 `pinyin_simp.extended`
    ```
    translator:
       dictionary: pinyin_simp.extended
    ```
3. 在 `pinyin_simp.extended.dict.yaml` 中添加需要的词库, 重新部署

**Comment by lotem** [comment]
如果输入方案设计为启用用户词典（`translator/enable_user_dict: true`），输入字词上屏即可调整词频。

如果输入方案设计为不启用用户词典（`translator/enable_user_dict: false`），重码字词的顺序由固态词典（*.dict.yaml）定义，有按照词频排序（`sort: by_weight`）和按照码表顺序（`sort: original`）两种方式。

**Reply by pdog18** [reply]
对不起, 还是很难理解

**Reply by SetsuikiHyoryu** [reply]
> 如果输入方案设计为启用用户词典（`translator/enable_user_dict: true`），输入字词上屏即可调整词频。
> 
> 如果输入方案设计为不启用用户词典（`translator/enable_user_dict: false`），重码字词的顺序由固态词典（*.dict.yaml）定义，有按照词频排序（`sort: by_weight`）和按照码表顺序（`sort: original`）两种方式。

@lotem 
当固态词典是 `sort: by_weight` 时有没有不修改固态词典也不复制一遍固态词典就可以关闭词频的解决方案？

另外我尝试把固态词典改为 `sort: original` 也无效（重新部属并重启过程序）。

**Reply by lotem** [reply]
不复制词典源码？


可以在 this.dict.yaml 之外另写一部词典 other.dict.yaml，
在其头部 yaml 配置里定义这两项

```yaml
sort: original
import_tables: [ this ]
```

然而做出来的二进制文件肯定会复制所有词语。

**Reply by SetsuikiHyoryu** [reply]
@lotem 
这个方式不用手动复制一遍码表，我也能接受。不过虽然使用这个方式成功自定义了词典，但是 `sort: original` 还是没有生效。具体来说是五笔 86 的 `fcu` 存在「支、云、去」三个字，不管怎么修改配置都会因为词频导致排列顺序发生改变。

这是我的配置文件：

```yaml
# default.custom.yaml

customization:
  distribution_code_name: Weasel
  distribution_version: 0.16.1
  generator: "Rime::SwitcherSettings"
  modified_time: "Thu Aug  1 17:31:12 2024"
  rime_version: 1.11.2
patch:
  "key_binder/bindings":
    - {accept: Return, send: Escape, when: composing}
    - {accept: semicolon, send: 2, when: has_menu}
    - {accept: apostrophe, send: 3, when: has_menu}
    - {accept: bracketleft, send: Page_Up, when: paging}
    - {accept: bracketright, send: Page_Down, when: has_menu}
  "menu/page_size": 3
  schema_list:
    - {schema: wubi86}
    - {schema: wubi_pinyin}
  "translator/enable_user_dict": false

```

```yaml
# weasel.custom.yaml

customization:
  distribution_code_name: Weasel
  distribution_version: 0.16.1
  generator: 'Weasel::UIStyleSettings'
  modified_time: 'Thu Jul 25 14:30:54 2024'
  rime_version: 1.11.2
patch:
  'style/+':
    font_face: 'Source Han Sans'
    horizontal: true
    inline_preedit: true
    preedit_type: composition
  'style/color_scheme': lost_temple

```

```yaml
# wubi86.extended.dict.yaml

name: wubi86.extended
version: '0.1.0'

sort: original
import_tables: [wubi86]
```

```yaml
# wubi86.schema.yaml

# ...

translator:
  dictionary: wubi86.extended

# ...

```

**Reply by lotem** [reply]
方案里开调频了。须关闭用户词典。
词典的 `sort` 参数只控制固态词典的结果排序。

**Reply by SetsuikiHyoryu** [reply]
@lotem 

方案是指方案选单吗？但是其中没看到关于用户词典的设置：

![image](https://github.com/user-attachments/assets/8721f9f1-7aa5-4dcd-91ef-c67abd2f2620)
![image](https://github.com/user-attachments/assets/f5c8a90d-24c4-480a-bc7c-50d5a36d451b)

右键图标时确实有像是用户词典的选项，但是其中没有删除或者关闭这样的按钮：

![image](https://github.com/user-attachments/assets/c9866e8f-7ee2-45f9-887f-3eb764fadc82)
![image](https://github.com/user-attachments/assets/4e8ea641-c00a-4840-aa7d-e009ef8bb38c)

**Comment by lotem** [comment]
如果输入方案设计为启用用户词典（`translator/enable_user_dict: true`），输入字词上屏即可调整词频。

如果输入方案设计为不启用用户词典（`translator/enable_user_dict: false`），重码字词的顺序由固态词典（*.dict.yaml）定义，有按照词频排序（`sort: by_weight`）和按照码表顺序（`sort: original`）两种方式。

部署时会结束所有输入会话，针对app的输入状态不会保留到部署之后。

**Comment by pdog18** [comment]
```
# pinyin_simp.schema.yaml
translator:
  dictionary: pinyin_simp.extended
  enable_user_dict: false
```

我现在企图使用这样的配置来达到我想要的效果, 但是还是很难:

```
#pinyin_simp.extended.dict.yaml 完整的自定义词频
有	y	10000
在	z	10000
中	zhong	1000000
这	zh	1000000
现在	xian z	1000000
```

这样配置了以后, 会有一个很奇怪的问题就是, 当我输入 「y」时, 只有一个备选词「有」了, 这就会导致我输入「zhey」的时候期望出现「这样」但是只会出现「这有」.
