### DISCUSSION TITLE
請問rime在輸入英文的時候，是否也有輸入單詞候選？

### DISCUSSION THREAD

**Discussion by lccc7liu** [rime/home#1056] [Q&A]
請問rime在輸入英文的時候，是否也有輸入單詞候選？
因爲有的英文單詞記得不是很準確，希望也可以有英文單詞候選，謝謝。

**Comment by Python-37** [comment]
我目前配置中包含了英文词库，是中文模式下才可以用的，要输入英文时如果前面某个字母拼错则无法匹配单词，同时要输入足够多个字母才会出现单词候选项，只能说聊胜于无。

**Comment by iDvel** [comment]
目前最大的困扰就是下面这图，在输入到最后一个字母之前，第一个候选项总是莫名其妙的。
<img width="240" alt="image" src="https://user-images.githubusercontent.com/14658234/167385758-89bb599e-6f67-4740-844c-107816f8cc9a.png">

**Reply by iDvel** [reply]
我搞定啦： 
<img width="151" alt="图片" src="https://user-images.githubusercontent.com/14658234/168282464-1d0e9d93-3f0a-4e95-b85f-b286ec8f735a.png">
https://dvel.me/posts/make-rime-en-better/
这样设置就行了，我也不知道为什么：
```
# 拼音
translator:
  dictionary: pinyin_simp
  initial_quality: 1.2

# 英文输入方案
melt_eng:
  dictionary: melt_eng
  initial_quality: 1.1
```
