### DISCUSSION TITLE
怎样禁用自动造句/造词？

### DISCUSSION THREAD

**Discussion by Quackgrass** [rime/home#1137] [Q&A] [answered]
## 描述

当键入的拼音不存在对应的词组时，默认会使用剩余拼音的第一个候选词补全，如下图左所示。

我期望没有第一个生成的候选词。如下图右，只匹配第一个词即选中第二个候选词，后续的仍显示为拼音。

根据 https://github.com/rime/home/issues/397#issuecomment-508921355 的提示配置了 `  "translator/enable_sentence": false`，未达到预期。

请问这个配置的效果是什么？有配置可以去掉第一个生成的候选词吗？

![image](https://user-images.githubusercontent.com/42032091/188864135-db63689b-54ef-472d-8a7c-915a6098dea1.png)

## 配置项

初始化配置，只添加了这一项。

```yaml
# pinyin_simp.custom.yaml
patch:
  "translator/enable_sentence": false
```

build 中生成的配置文件

```
translator:
  dictionary: pinyin_simp
  enable_sentence: false
  preedit_format:
    - "xform/([nl])v/$1ü/"
    - "xform/([nl])ue/$1üe/"
    - "xform/([jqxy])v/$1u/"
```

## 参考

根据 [Schema.yaml 詳解](https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E4%B8%89translator) 中描述：

>三、translator
> 9. enable_sentence: 是否開啓自動造句
