### DISCUSSION TITLE
有办法实现在已有内容的情况下下划线不自动选词而转换为英文继续输入吗？

### DISCUSSION THREAD

**Discussion by plutotree** [rime/home#1209] [Q&A] [answered]
在输入内容的时候经常会输入带下划线的英文词，比如各类变量名，用搜狗输入法会很习惯直接输入比如`cats_num`，然后就能正常输出了，而Rime在输入`_` 的时候会自动先选择字符上屏，想咨询下有没有类似搜狗的解决方法

默认配置下RIME会将_转换为破折号，但即使我关闭这个转换，结果仍然是有问题的

- 搜狗输入法：输入`_a_b `
   ![sogou](https://user-images.githubusercontent.com/60023/217524671-c0c9bb90-241c-492d-a96f-0202252188f1.gif)
- RIME输入法：输入`_a_b `
   ![rime](https://user-images.githubusercontent.com/60023/217524696-24eb7d45-9d93-4c47-b54a-7f25254f5c8d.gif)
- RIME输入法：输入`_a_b `（关闭符号转换）
  ![rime2](https://user-images.githubusercontent.com/60023/217526038-f1d9bef8-723d-4f4e-a24f-5618f961b2b2.gif)

**Comment by plutotree** [comment]
我把issue提到`weasel`里面去

**Comment by iDvel** [comment, marked as answer]
```yaml
recognizer:
  patterns:
    # ...
    # 增加下面这行
    underscore: "^[A-Za-z]+_.*"
```
