### DISCUSSION TITLE
请问如何阻止 反斜杆 \ 上屏

### DISCUSSION THREAD

**Discussion by nasyxx** [rime/home#1238] [Q&A]
不知道是不是我的版本问题...

```
macOS: 13.2
squirrel: 0.17.2
Rime version: 1.8.5
```

我尝试设置了如下内容：

一个是

```
speller:
  alphabet: 'pyfgcrlaoeuidhtnsqjkxbmwvzZYXWVUTSRQPONMLKJIHGFEDCBA\'
  delimiter: " '\\"
  ...

punctuator:
  half_shape:
    "\\": ["a", "b"]
    "\\\\": ["c", "d"]

recognizer:
  patterns:
    latex: "^\\\\.+$"
    latex2: "^\\.+$"
```

但都没有出现预期的内容，而是 \ 直接上屏。

是有什么地方我没注意到吗？还是什么其他原因？
