### DISCUSSION TITLE
鼠须管和小狼毫，在今天(2023/4/10)，它们的配色方案分别支持哪些属性？

### DISCUSSION THREAD

**Discussion by pdog18** [rime/home#1259] [Q&A]
查看了 `weasel.yaml` 发现内部有很多`定製【小狼毫】配色方案`, 未提到的属性。
例如：
```
hilited_label_color
hilited_candidate_label_color
```

![img](https://camo.githubusercontent.com/ccf1aa20feee0d38291d2a90406554ee68985f7e350a12b11bbcd74744d74671/687474703a2f2f692e696d6775722e636f6d2f685374793663422e706e67)

尤其在 `weasel.yaml` 中还同时存在 `label_color` 属性，这就很让人疑惑。**_rime 有地方提到过哪些属性是较新的吗？_**

另外的，在文件中，一些主题仅仅设置了7条颜色属性，例如：
```yaml
  aqua:
    author: "佛振 <chen.sst@gmail.com>"
    back_color: 0xeceeee
    border_color: 0xe0e0e0
    hilited_back_color: 0xd4d4d4
    hilited_candidate_back_color: 0xfa3a0a
    hilited_candidate_text_color: 0xffffff
    hilited_text_color: 0x000000
    name: "碧水／Aqua"
    text_color: 0x000000
```
但是已经是可以搭配出一套可以运行的配色，如果为了玩家更好的理解配色，能否由我来对默认的配置进行调整，补全哪些缺省的属性（即使对应颜色缺省也会又其他属性得到）？

**Comment by pdog18** [comment]
似乎我应该在这里查找https://github.com/rime/weasel/blob/371e08e4c799beef15ec93b461b17125c77f166b/RimeWithWeasel/RimeWithWeasel.cpp#L621-L666

https://github.com/rime/weasel/blob/371e08e4c799beef15ec93b461b17125c77f166b/include/WeaselCommon.h#L156-L213

**Reply by pdog18** [reply]
> 似乎我应该在这里查找https://github.com/rime/weasel/blob/371e08e4c799beef15ec93b461b17125c77f166b/RimeWithWeasel/RimeWithWeasel.cpp#L621-L666
> 
> https://github.com/rime/weasel/blob/371e08e4c799beef15ec93b461b17125c77f166b/include/WeaselCommon.h#L156-L213

太混乱了，这部分的代码

**Reply by pdog18** [reply]
应该是有历史原因的，就好比之前只有一个 `label_color` 但是后来根据现实情况，细分了 `label_text_color` 和 `hilited_label_text_color` 然后当然不可以在代码中直接删除掉 `label_color`（因为这将会导致用户的配色不正确），可以说是无奈之举。

不知道这算不算 `yaml` 来让用户定制的一个副作用？好像也不是。

**Comment by pdog18** [comment]
所以现在的代码逻辑是：
1. 获取 `text_color`   （ `text_color` 必选项）
2. 获取 `candidate_text_color` ，如果文件中没有则 `text_color => candidate_text_color`
3. 获取 `back_color` （ `back_color` 必选项）
4. 获取 `border_color` ，如果文件中没有则 `text_color => border_color`
5. 获取 `hilited_text_color` ，如果文件中没有则 `text_color => hilited_text_color`
6. 获取 `hilited_back_color` ，如果文件中没有则 `back_color=> hilited_back_color `
7. 获取 `hilited_candidate_text_color` ，如果文件中没有则 `hilited_text_color=> hilited_candidate_text_color`
8. 获取 `hilited_candidate_back_color` ，如果文件中没有则 `hilited_back_color=> hilited_candidate_back_color`
9. 获取 `label_color` 赋值至 `label_text_color`，如果文件中没有则 `blend_colors(style.candidate_text_color, style.back_color)=> label_text_color` （混合 `candidate_text_color` 及`back_color` ）
10. 获取 `hilited_label_color` 赋值至 `hilited_label_text_color`，如果文件中没有则 `blend_colors(style.hilited_candidate_text_color, style.hilited_candidate_back_color)` （混合 `hilited_candidate_text_color` 及`hilited_candidate_back_color` ）
11.   暂时将  `comment_text_color ` 的值设置为 `label_text_color`
12.   暂时将 `hilited_comment_text_color ` 的值设置为 `hilited_label_text_color`
13. 获取 `comment_text_color` 
14. 如果文件中 `comment_text_color` 有值，那么 `comment_text_color` 就更新为文件中的 `comment_text_color`
15. 如果 `14` 更新成功，则同时将 `hilited_comment_text_color ` 的值更新为 `comment_text_color`
16. 如果文件中 `hilited_comment_text_color` 有值，那么优先使用文件中的 `hilited_comment_text_color`值

 


```c++
RimeConfigGetInt(config, (prefix + "/text_color").c_str(), &style.text_color);
if (!RimeConfigGetInt(config, (prefix + "/candidate_text_color").c_str(), &style.candidate_text_color)){
	style.candidate_text_color = style.text_color;
}
RimeConfigGetInt(config, (prefix + "/back_color").c_str(), &style.back_color);
if (!RimeConfigGetInt(config, (prefix + "/border_color").c_str(), &style.border_color)){
	style.border_color = style.text_color;
}
if (!RimeConfigGetInt(config, (prefix + "/hilited_text_color").c_str(), &style.hilited_text_color)){
	style.hilited_text_color = style.text_color;
}
if (!RimeConfigGetInt(config, (prefix + "/hilited_back_color").c_str(), &style.hilited_back_color)){
	style.hilited_back_color = style.back_color;
}
if (!RimeConfigGetInt(config, (prefix + "/hilited_candidate_text_color").c_str(), &style.hilited_candidate_text_color)){
	style.hilited_candidate_text_color = style.hilited_text_color;
}
if (!RimeConfigGetInt(config, (prefix + "/hilited_candidate_back_color").c_str(), &style.hilited_candidate_back_color)){
	style.hilited_candidate_back_color = style.hilited_back_color;
}
if (!RimeConfigGetInt(config, (prefix + "/label_color").c_str(), &style.label_text_color)){
	style.label_text_color = blend_colors(style.candidate_text_color, style.back_color);
}
if (!RimeConfigGetInt(config, (prefix + "/hilited_label_color").c_str(), &style.hilited_label_text_color)){
	style.hilited_label_text_color = blend_colors(style.hilited_candidate_text_color, style.hilited_candidate_back_color);
}
style.comment_text_color = style.label_text_color;
style.hilited_comment_text_color = style.hilited_label_text_color;
if (RimeConfigGetInt(config, (prefix + "/comment_text_color").c_str(), &style.comment_text_color)){
	style.hilited_comment_text_color = style.comment_text_color;
}
RimeConfigGetInt(config, (prefix + "/hilited_comment_text_color").c_str(), &style.hilited_comment_text_color);
```

**Comment by pdog18** [comment]
所以小狼毫预置的 style 
```yaml

  psionics:
    name: 幽能／Psionics
    author: 雨過之後、佛振
    text_color: 0xc2c2c2
    back_color: 0x444444
    border_color: 0x444444
    candidate_text_color: 0xeeeeee
    hilited_text_color: 0xeeeeee
    hilited_back_color: 0x444444
    hilited_candidate_label_color: 0xfafafa
    hilited_candidate_text_color: 0xfafafa
    hilited_candidate_back_color: 0xd8bf00
    comment_text_color: 0x808080
    hilited_comment_text_color: 0x444444
```

它的 `hilited_candidate_label_color` 实际上是完全无效的？
