### DISCUSSION TITLE
为何按键设置会有两处方案？这样设计原因是为什么？

### DISCUSSION THREAD

**Discussion by pdog18** [rime/home#1267] [Q&A] [answered]
键位设置中存在两套方案：

``` yaml
key_binder/bindings
```
另外，还有针对 Caps_Lock、Shift 和 Control 的一些特定选项：

``` yaml
patch:
  ascii_composer/good_old_caps_lock: true
  ascii_composer/switch_key:
    Caps_Lock: commit_code
    Shift_L: noop
    Shift_R: noop
    Control_L: commit_code
    Control_R: commit_code
```
这两套方案让我感到有些迷惑。此外，`good_old_caps_lock` 的命名方式也让我难以直观地理解它的作用。尽管我尝试过搜索，但未能找到更多解释。有谁能帮忙解答一下吗？

**Comment by iDvel** [comment]
我猜啊，CapsLock 的本意是切换大小写，后来有的把它当作 ESC，有的当作 Ctrl，有的当作切换中英或输入法。
所以 good old CapsLock 为 true 就是让它回到原本切换大小写的作用 😄

**Reply by pdog18** [reply]
> 我猜啊，CapsLock 的本意是切换大小写，后来有的把它当作 ESC，有的当作 Ctrl，有的当作切换中英或输入法。 所以 good old CapsLock 为 true 就是让它回到原本切换大小写的作用 😄

唉，这一块小狼毫的支持较差，对于我们这种习惯用 capslock 来切换中英文的真的头大

**Reply by iDvel** [reply]
小狼毫不是也支持吗，设置为 false 就是切换中英了。

**Reply by pdog18** [reply]
> 小狼毫不是也支持吗，设置为 false 就是切换中英了。

支持，但是有问题，输入法处于非激活状态时，切换功能不总是可信的。
[另一个讨论贴里](https://github.com/rime/home/discussions/1206#discussioncomment-5660550)

**Reply by zcunlin** [reply, marked as answer]
这个问题@lotem有写过：

>
中西文切換鍵的默認設置寫在 default.yaml 裏面
以下的 default.custom.yaml 在全局範圍重定義該組快速鍵

可用的按鍵有 Caps_Lock, Shift_L, Shift_R, Control_L, control_R
 Mac 系統上的鼠鬚管不能區分左、右，因此只有對 Shift_L, Control_L 的設定起作用

已輸入編碼時按切換鍵，可以進一步設定輸入法中西文切換的形式。
可選的臨時切換策略有三：
inline_ascii 在輸入法的臨時西文編輯區內輸入字母、數字、符號、空格等，回車上屏後自動復位到中文
commit_text 已輸入的候選文字上屏並切換至西文輸入模式
commit_code 已輸入的編碼字符上屏並切換至西文輸入模式
設爲 noop，屏蔽該切換鍵

**如果要把 Caps Lock 設爲只改變母的大小寫而不做中西文切換，可將 Caps_Lock 對應的切換方式設爲 noop
如果要以 Caps Lock 切換到西文模式，默認輸出小寫字母，請置 ascii_composer/good_old_caps_lock: false
如果要以 Caps Lock 切換到西文模式，默認輸出大寫字母，請使用以下設置：**
```yaml
patch:
  ascii_composer/good_old_caps_lock: true
  ascii_composer/switch_key:
    Caps_Lock: commit_code
    Shift_L: noop
    Shift_R: noop
    Control_L: commit_code
    Control_R: commit_code
```
