### DISCUSSION TITLE
在软件内设置默认中文还是英文，并且可以切换中英文输入

### DISCUSSION THREAD

**Discussion by mikaizhu** [rime/home#1283] [Q&A]
我的操作系统：
-  Mac OS

我在Squirrel yaml文件中，进行了如下配置：

```
app_options:
  net.kovidgoyal.kitty:
    # ascii_mode: true
    vim_mode: true
  md.obsidian:
    vim_mode: true
  com.google.Chrome:
    ascii_mode: false
  org.yuanli.utools:
    ascii_mode: true
```
当我打开谷歌浏览器时，输入法会自动切换为中文，但是我想在谷歌浏览器中切换中英文，却发现不能操作。

如何**打开某个软件，可以设置默认的中文或英文输入法，并且可以随意切换中英文？**

**Comment by pdog18** [comment]
Chrome 按照你的配置，可以正常切换中英文(我使用的 capslock)，你有没有修改 `default.custom.yaml` 中的
```
ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: clear
    Control_L: noop
    Control_R: noop
    Eisu_toggle: clear
    Shift_L: inline_ascii
    Shift_R: commit_text
 ```

**Reply by mikaizhu** [reply]
我的 default yaml配置文件：
```
ascii_composer:
  good_old_caps_lock: true  # true | false
  switch_key:
    Caps_Lock: clear      # commit_code | commit_text | clear
    Shift_L: noop  # commit_code | commit_text | inline_ascii | clear | noop
    Shift_R: noop         # commit_code | commit_text | inline_ascii | clear | noop
    Control_L: noop       # commit_code | commit_text | inline_ascii | clear | noop
    Control_R: noop       # commit_code | commit_text | inline_ascii | clear | noop
```
我使用的是Control + Space切换中英文输入：

```
- { when: always, accept: Control+space, toggle: ascii_mode }
```
使用这些配置后，我无法在chrome浏览器中，使用Control + Space 切换英文输入了
