### DISCUSSION TITLE
请教如何实现首码隐藏功能？

### DISCUSSION THREAD

**Discussion by niuhaizhen** [rime/home#1352] [Q&A]
对于双拼用户来说，首码内嵌+隐藏可以尽可能的不显示候选窗口，直接在输入框输入文字。

类似下面的效果
<img width="836" alt="image" src="https://github.com/rime/home/assets/1239710/c8fa1fb7-7180-4825-bf99-fb79e6925c91">

---
放上一个从网上找的实现动态对比图

![fcitx5-hidden-typing-windows-demo](https://github.com/rime/home/assets/1239710/38f42653-3d79-45a9-8c74-f016abb211ba)

**Comment by yanhuacuo** [comment]
哈哈，「首选」不是「所需」时，不觉得这样太过诡异吗？

**Reply by niuhaizhen** [reply]
使用双拼+辅码时，可以做到很大部分只有一个候选项，重码时再弹出选择。基于这样的场景才有类似的需求。只使用双拼不加辅码时，还是得需要候选提示。

**Comment by fxliang** [comment]
如果是新的小狼毫，可以新其中一个margin设置为负值，然后preedit_type设置为preview_all, inline_preedit设置为true， 就可以全部在preedit中显示候选内容，不显示候选窗。
大概可能接近你想要的效果了。
```yaml
  style/inline_preedit: true
  style/preedit_type: preview_all
  style/layout/margin_x: -10

```

![image](https://github.com/rime/home/assets/4023160/4503295e-3412-443e-b43f-952e48efd26e)
