### DISCUSSION TITLE
在key_bindings中设置ctrl+shift+0快捷键无效

### DISCUSSION THREAD

**Discussion by Lantaio** [rime/home#1365] [Q&A]
想在key_bindings中用Ctrl+Shift+0作为快捷键来切换某个功能，但是设置后无效，例如：
``` yaml
patch:
  numbered_mode_switch:
    __append:
      - { when: always, accept: Control+Shift+0, toggle: full_shape }
      - { when: always, accept: Control+Shift+parenright, toggle: full_shape }
```
如上设置后无法通过Ctrl+Shift+0来进行全角/半角的切换。但我改用1～9好像都没有问题。请问这是bug吗？还是这个快捷键组合有什么特殊的作用？我搜索过这个快捷键组合好像也不是Windows系统的快捷键。
