### DISCUSSION TITLE
每一个选项都被全拼注音，如何关闭？

### DISCUSSION THREAD

**Discussion by lw6151** [rime/home#1366] [Q&A]
ibus+rime
东风破一键安装了雾凇
使用体验很完美，然而！！！
输入时发现发现每一个选项都被全拼注音了

![Screenshot from 2023-09-02 05-26-35](https://github.com/rime/home/assets/59368561/91d9e640-0722-4ae9-86c9-dab600771dda)

萌新请问该如何关闭掉注音呢？

**Comment by Lantaio** [comment]
如果你的用户目录里有`rime_ice.schema.yaml`这个文件，打开，将`spelling_hints`和`always_show_comments`两行注释，像下面这样。
```yaml
# 主翻译器，拼音
translator:
  dictionary: rime_ice           # 挂载词库 rime_ice.dict.yaml
#  spelling_hints: 8              # corrector.lua ：为了让错音错字提示的 Lua 同时适配全拼双拼，将拼音显示在 comment 中
#  always_show_comments: true     # corrector.lua ：Rime 默认在 preedit 等于 comment 时取消显示 comment，这里强制一直显示，供 corrector.lua 做判断用。
  initial_quality: 1.2           # 拼音的权重应该比英文大
```
貌似会使错音提示失效，不过应该不重要。如果这样不行的话，就去问[雾凇的主](https://github.com/iDvel/rime-ice)。
