### DISCUSSION TITLE
如何在輸入的界面顯示其他拼音方案

### DISCUSSION THREAD

**Discussion by Photon-gjq** [rime/home#1388] [Q&A] [answered]
想問下rime如何設置拼寫運算時顯示其他dictionary裡的拼音方案？我想在用普通話拼音打字的時候顯示粵語/中古音的對應，例如下圖的效果。

![7fa9e8fea2b4ede4fd68f2cec9ae7c1](https://github.com/rime/home/assets/71842413/2b8346d3-a5d6-4ff2-921b-7a793f81c922)

這個需求並不等價于反查，反查需要多按一個按鍵，我想在直接輸入的時候默認顯示。我不知道是不是在translator的enable_completion裡動手腳，或者有沒有辦法設置默認反查？我曾嘗試把反查的前綴從"`"改成""或刪除prefix選項，但都無效（而且即使默認反查，也有問題，例如輸入邏輯不同等等）

先感謝！

**Comment by russell-liu** [comment]
同問 求解

**Comment by russell-liu** [comment]
找到參考資料了：https://github.com/rime/home/issues/298
我寫了個方案，能初步解決問題，但仍在優化中。

**Reply by Photon-gjq** [reply]
感謝提供。但這個也只是權宜之計，需要按反查按鈕。我想要的其實是默認輸入的時候直接顯示反查結果的方案，感覺技術上沒有本質困難，但就是不知道如何操作。

**Reply by russell-liu** [reply]
參考資料中gkovacs的解決方法似乎是不需按反查按鈕的，但我還沒完全看懂。不過以下幾項改動應該可以初步解決問題：

- 刪去`reverse_lookup/prefix`和`reverse_lookup/suffix`
- 修改`recognizer/reverse_lookup`，刪去正則表達式中原有的prefix和suffix
- 刪去`engine/segmentors/abc_segmentor`

我認為這個解決方法有它的短處，但你可以試下是否符合你的要求。

**Comment by russell-liu** [comment, marked as answer]
時隔一年，我再嘗試研究此問題（默認反查），算是把解決方法看懂了。先在此提供我寫出的你需求的"朙月拼音學粵語拼音"和"朙月拼音學中古全拼"兩種方案配置：

luna_pinyin_learn_jyut6ping3.schema.yaml

```yaml
# Rime schema
# encoding: utf-8

__include: jyut6ping3.schema:/

schema:
  schema_id: luna_pinyin_learn_jyut6ping3
  name: 朙月拼音學粵語拼音
  version: "2024.11.07"

__patch:
  luna_pinyin/prefix:
  luna_pinyin/suffix:
  recognizer/patterns/luna_pinyin: "^[a-z']*$"
  recognizer/patterns/loengfan:
  recognizer/patterns/stroke:
  recognizer/patterns/cangjie5:
  engine/segmentors/@6: # abc_segmentor
```

luna_pinyin_learn_zyenpheng.schema.yaml

```yaml
# Rime schema
# encoding: utf-8

__include: zyenpheng.schema:/

schema:
  schema_id: luna_pinyin_learn_zyenpheng
  name: 朙月拼音學中古全拼
  version: "2024.11.07"

__patch:
  recognizer/patterns/luna_pinyin: "[a-z]*$"
  engine/translators/@1: script_translator@luna_pinyin # script_translator
  luna_pinyin/tag: luna_pinyin
  luna_pinyin/dictionary: luna_pinyin
  luna_pinyin/preedit_format:
    __include: luna_pinyin.schema:/translator/preedit_format
  engine/filters/@next: reverse_lookup_filter@zyenpheng_reverse_lookup
  zyenpheng_reverse_lookup/tags: [ luna_pinyin ]
  zyenpheng_reverse_lookup/dictionary: zyenpheng
```

"X學Y"方案配置靠改動設有X反查的Y方案配置實現（我一年前提到要作出改動，但忘了指明改動的對象）；這理當適用於任何X和Y方案。

以上兩種方案配置的異處源於粵語拼音使用reverse_lookup_filter，而中古全拼使用（過時的）reverse_lookup_translator；我之前的解決方法是基於reverse_lookup_translator寫的。對粵語拼音的改動與我之前所説幾乎一樣，只是reverse_lookup改爲luna_pinyin，而且刪掉與默認朙月拼音反查衝突的其他方案反查。對中古全拼可以單作出之前提出的改動，但這會有之前提到但沒描述的短處：失去組詞功能，即例如打"lookup"無法出現"咯哦酷派"選項（這或許是你所提到的反查"輸入邏輯不同"問題）。因此，我新寫的方案配置把中古全拼的reverse_lookup_translator也改爲reverse_lookup_filter了。

值得注意的是：現時librime不支持反查多音節詞（可參見 https://github.com/rime/home/issues/1536 ），所以用以上方案時多音節詞旁不會顯示提示碼；幸好我成功對librime作出改動以實現此功能，發佈於 https://github.com/russell-liu/librime/releases/tag/1.11.3-0 。要反查多音節詞，則可安裝此版本librime。
