### DISCUSSION TITLE
win11 23H2，小狼毫最新版action，default.yaml和default.custom.yaml均无法生效

### DISCUSSION THREAD

**Discussion by Think0508** [rime/home#1475] [Q&A] [answered]
已测试此版本：
https://github.com/rime/weasel/actions/runs/7874554255
在我的电脑上，候选词数量无法生效，改标点符号/翻页均不生效。
环境：win11 23H2.
共享目录里的config_version是0.40，为避免小于它，我之后又把default里的版本设到了1.5，依然无效。
tab和空格/缩进反复检查过，无问题。我也用润笔网站的yaml尝试替代，依然无效。
我给朋友另一台电脑安装官版小狼毫，同样设置，他的可以生效。
我几天前，曾在这台电脑安装action版的小狼毫，同样设置，候选词可以正常生效。（后来由于另一个bug，我删除了它）
我备份了当时的用户文件夹，但覆盖回去后，default依然不生效。
我多次尝试重装小狼毫，依然无效。
[Rime.zip](https://github.com/rime/home/files/14256838/Rime.zip)
以上是我的用户文件夹，除了词库之外的文件，供debug。

**Comment by MokOopsing** [comment]
![image](https://github.com/rime/home/assets/39441028/4f343e73-d785-43b1-b192-8e6d47fe40a3)

这份文件是不能直接用的

**Reply by Think0508** [reply]
感谢回复！我的Rime用户文件夹没打包文件夹。现在我传了一份蓝奏云，[https://www.lanzv.com/idWZC1onfgbg](url) 内容是Rime的用户文件夹所有内容的zip。如果方便的话烦请查看，再次感谢帮助！

**Reply by MokOopsing** [reply, marked as answer]
symbols_v.yaml

```yaml
# Rime's symbols
# encoding: utf-8
#
# copy from /Library/Input Methods/Squirrel.app/Contents/SharedSupport/symbols.yaml
#
# 原「/」模式 改为了「v」模式，
# 映射的汉字改为简体，
# 一些韵母前四位顺序改为「一声、二声、三声、四声、其他...」如输入 va 得到 ā á ǎ à
#
# version: 2023-12-24

symbols:
#符号、电脑

  # 键盘符号
  'vcmd': [⌘] # 单个的可以不加[]
  'vctrl': [⌃]
  'dv': [√]
  'dm': [·]
  'yr': [○]
  'xb': [❤️]
  'zo': [←]
  'yz': [→]
  'uh': [↑]
  'xx': [↓]
  'xnyu': [＜]
  ''dayu: [＞]
  'budgyu': [≠]
  'ueuidu': [°C]

```
```yaml
''dayu: [＞]
```
