### DISCUSSION TITLE
小狼毫 0.15.0.0 如何切换中英文图标？

### DISCUSSION THREAD

**Discussion by GitFlzy** [rime/home#1513] [Q&A] [answered]
默认的图标是一个“中”和“A”，如何替换成其它图标？对 ico 文件的大小有要求吗？

**Comment by GitFlzy** [comment, marked as answer]
已解决
在 <方案名>.schema.yaml 文件里的 "schema" 次级关键字 “icon" 和 "ascii_icon"（分别对应”中“和”A“图标）指明 icon 文件位置即可，具体如下：
```yaml
schema:
  schema_id: flypy
  ...
  icon: "icon/chinese.ico"
  ascii_icon: "icon/english.ico"

```
其中，icon/ 文件夹在 rime 的用户目录，具体位置或名称为自定义
