### DISCUSSION TITLE
請問如何調整異體字使用何種版本？

### DISCUSSION THREAD

**Discussion by felix920506** [rime/home#1534] [Q&A]
環境：
Linux Mint 21.3，使用 Debian / Ubuntu 教程安裝，ibus 版本

目前遇到的有這兩個
臺灣慣用“啟”，RIME輸出“啓”
臺灣慣用“為”，RIME輸出“爲“
不清楚是否還有更多

請問如何修正？
目前狀態下製作文件非常不方便

**Comment by ksqsf** [comment]
~~剛剛看錯，重新答一下~~ 可以使用 opencc 轉換。修改 schema，增加如下內容

```
engine:
  filters:
    - simplifier@tw
tw:
  opencc_config: t2tw.json
```

**Reply by felix920506** [reply]
我在 luna_pinyin.schema.yaml 中修改了相關設定並重新部署但問題沒有解決

**Reply by felix920506** [reply]
[luna_pinyin.schema.txt](https://github.com/rime/home/files/15084437/luna_pinyin.schema.txt)
這個是完整的 luna_pinyin.schema.yaml 檔案（重新命名成.txt因爲github無法上傳.yaml）

**Reply by ksqsf** [reply]
这个文件看起来像是 build 之后的结果（不应该手动修改），建议把原始 luna_pinyin.schema.yaml 拷贝到用户目录后再修改。

**Reply by felix920506** [reply]
我複製了一份到 ~/.config/ibus/rime 然後進行以上修改，依然沒有效果
[luna_pinyin.schema.yaml.txt](https://github.com/rime/home/files/15094786/luna_pinyin.schema.yaml.txt)

**Comment by fxliang** [comment]
其實是沒改完,朙月拼音詞庫是 traditional, 其simplifier原本是要轉換成簡化字,這裡需要調整下, simplifier 為1是對應簡體, 那就將這個簡體漢字的位置換成臺灣漢字即可

```yaml
patch:
  engine/filters:
    - simplifier@t2tw
    - uniquifier
  t2tw:
    opencc_config: t2tw.json
  switches:
    - name: ascii_mode
      reset: 0
      states: [ 中文, 西文 ]
    - name: full_shape
      states: [ 半角, 全角 ]
    - name: simplification
      states: [ 漢字, 臺灣漢字 ]
    - name: ascii_punct
      states: [ 。，, ．， ]
```

![image](https://github.com/rime/home/assets/4023160/cb2d162a-1f1e-4d84-90d1-d130c82bf0d2)
![image](https://github.com/rime/home/assets/4023160/0112e844-184f-4a41-9f1d-7015110d0e5e)
![image](https://github.com/rime/home/assets/4023160/6e0a5463-e669-41d0-bcfa-3130ee64fc87)
