### DISCUSSION TITLE
How to use a key to replace another key?

### DISCUSSION THREAD

**Discussion by Freed-Wu** [rime/home#1558] [Q&A] [answered]
I try to use rime to input japanese. ノート shoulde be no-to in dictionary, however, - will become page down. Is it possible to use _ to replace -?

I try:

```yaml
  key_binder/bindings/@next:
    accept: Control+minus
    send: minus
    when: always
```

can work,

```yaml
  key_binder/bindings/@next:
    accept: underscore
    send: minus
    when: always
```

cannot. However, in mobile without keyboard, ctrl is hard to be typed. So is it possible to use a key to replace another key?

TIA!
