### DISCUSSION TITLE
不同分辨率下候选词展示卡顿

### DISCUSSION THREAD

**Discussion by hundan2015** [rime/home#1559] [Q&A] [answered]
我现在使用的是0.16.0版本，这个问题在0.15以及相关的Nightly版本中都有出现。

在主屏幕我是1080p的分辨率，输入法候选词栏流畅反应快速；但是在副2K屏上候选词和预览都有延迟。

下面是我的自定义配置：
```yaml
"style/color_scheme": clean_white
  "style/comment_font_point": 10
  "style/display_tray_icon": false
  "style/font_face": "Advocate Ancient Sans:normal"
  "style/font_point": 13
  "style/horizontal": true
  "style/inline_preedit": true
  "style/label_font_face": "Advocate Ancient Sans:normal"
  "style/label_font_point": 13
  "style/layout/border_width": 1
  "style/layout/candidate_spacing": 12
  "style/layout/corner_radius": 6
  "style/layout/enhanced_position": true
  "style/layout/hilited_corner_radius": 6
  "style/layout/margin_x": 7
  "style/layout/margin_y": 7
  "style/layout/min_width": 50
  "style/layout/shadow_offset_x": 0
  "style/layout/shadow_offset_y": 2
  "style/layout/shadow_radius": 7
  "style/preedit_type": composition
  ”show_notifications": false
  “show_notifications_when”: never
```
