### DISCUSSION TITLE
引入的自定义词库无法正常生效

### DISCUSSION THREAD

**Discussion by AnLazyOtter** [rime/home#1589] [Q&A] [answered]
使用的版本：0.15.1.0（之前也试过0.16.1，词库部分也没成功）
使用的系统：windows 11 23H2 (22631.3593)
遇到的问题：根据文档，我尝试了引入自定义词库。在配置中， 修改menu/page_size生效了，但词典，这几个都没生效：
1. 在`extended.dict.yaml`中直接录入映射，没生效。
2. 词典文件`~RIME\RIMEDotA2.dict.yaml`，没生效
3. 词典文件`~RIME\dict\RIMEPersonalDict.dict.yaml`，没生效

**1. 修改default.custom，启用用户词典**

```yaml
#文件名：default.custom.yaml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.15.1
  generator: "Rime::SwitcherSettings"
  modified_time: "Mon Jun 10 00:22:38 2024"
  rime_version: 1.11.2
patch:
  schema_list:
    - {schema: luna_pinyin_simp}
  menu:
    page_size: 6 #候选字数量
  translators:
    enable_user_dict: true #允许使用用户词典
    dictionary: extended #引入特定名称的用户词典
```

**2. 新建extended.dict，引入用户词典**

```yaml
# 文件名：extended.dict.yaml
# Rime exteneded dictionary
# encoding: utf-8
---
name: extended
version: "2024-06-09"
sort: original

import_tables:
  - cn-dicts/RIMEPersonalDict
  - RIMEDotA2
...
补差款	bu cha kuan
欢欣之刃	huan xin zhi ren
```

**3. 引入自制词库RIMEDotA2**

```yaml
# 文件名：RIMEDotA2.dict.yaml
# dota2词库 由深蓝转换 无词频
# encoding: utf-8
---
name: RIMEDotA2 # 词库名
version: "07-36-3"  # 词库版本
sort: original # 排序依据：按照权重/by_sort，按原始顺序original
...
阿哈利姆福佑	a ha li mu fu you
阿哈利姆魔晶	a ha li mu mo jing
```

**4.引入自定义词库RIMEPersonalDict**

```yaml
# 文件名：dict/RIMEPersonalDict.dict.yaml
# 个人词库 由深蓝转换 无词频
---
name: RIMEPersonalDict  # 词库名
version: "2024-06-09"  # 词库版本
sort: original # 排序依据：按原始顺序
...
奥尔德南	ao er de nan
补差款	bu cha kuan
```

附加信息：

已测试使用的换行符，确实是unix的\n
![image](https://github.com/rime/home/assets/40395191/356e075e-aeca-4fed-9506-b013d00113bc)

完成上述设置并重新部署后，还是无法输入词库中的内容，例如：
![image](https://github.com/rime/home/assets/40395191/b755c0e8-7468-49e2-bb8c-e5db86ed1eba)

文件的绝对路径应该不算长：
> C:\Users\Iwonn\AppData\Roaming\Rime\cn-dicts\RIMEDotA2.dict.yaml

求助各位大佬：到底如何才能引入自定义词库？

**Comment by fxliang** [comment]
修改default.custom，启用用户词典

这步错了

**Reply by AnLazyOtter** [reply]
> 修改default.custom，启用用户词典
> 
> 这步错了

@fxliang 请问，是因为必须将用户词典在schema文件中录入，而非在`default.custom.yaml`中么？

**Reply by fxliang** [reply]
应该是方案名.custom.yaml 里引入吧

**Reply by AnLazyOtter** [reply, marked as answer]
> 应该是方案名.custom.yaml 里引入吧

最后还是改了处理思路，现在自己解决了。
我没能看明白具体“修改default.custom，启用用户词典”这一步错在哪里了，索性直接改用了雾凇拼音输入方案，然后追加了我自己的词库。参考资料：《[Windows小狼毫Rime输入法使用体验-靜風說](https://www.jingfengshuo.com/archives/2753.html)》
既然我花了几个小时才整理出来如何解决，那索性加一篇文章，说明下我是怎么解决的吧。

# 步骤1：改用雾凇拼音的所有功能
1. 在输入法设置中退出算法服务，并切换到其他输入法，或者直接关闭输入法
2. 删除用户文件夹`%APPDATA%\RIME`中的所有内容
3. 将下载下来的雾凇拼音所有文件复制到上述路径
4. 切换输入法到小狼毫，此时会自动进行一次重新部署
5. 待完成后，在输入法设定中，仅启用雾凇拼音输入方案。
6. 保险期间，我再次执行了重新部署。

# 步骤2：追加自定义词典
1. 提前通过深蓝词库转换器转换生成了词库文件
2. 保存后，使用Emeditor打开
3. 在”替换“窗口，查找`\r\n'，替换为'\n'，点击全部替换
4. （首次执行时会触发）emeditor会提问是否要区分CR和LF的段落标记，选择是、要区分即可
5. 再次执行替换，确保没有遗漏的
6. 在`%appdata%\RIME`下新建文件夹：`custom-dicts`
7. 在emeditor中，将刚刚编辑完成的文件另存为：`%appdata%\RIME\custom-dicts\RIMEPersonalDict.dict.yaml`，以及`%appdata%\RIME\custom-dicts\RIMEDotA2.dict.yaml`。（我有两个词库文件，所以就保存两个文件）

小提示：建议保证文件名与词库名一致。例如：文件名为`RIMEDotA2.dict.yaml`，那么文件头的name也叫作RIMEDotA2，保证内外统一。
示例：
```yaml
# dota2词库 由深蓝转换 无词频
#coding: UTF-8
---
name: RIMEDotA2 # 词库名
version: "V7.36-3"  # 词库版本
sort: original # 排序依据：按照权重
...
阿哈利姆福佑	a ha li mu fu you
```

# 步骤3：启用自定义词典
首先，需要了解下雾凇拼音输入方案是如何构架词库的（其实这对于RIME来说都是通用的）。
雾凇拼音输入方案的方案文件`%appdata%\Rime\rime_ice.schema.yaml`中写到（节选）：
```yaml
# 主翻译器，拼音
translator:
  dictionary: rime_ice        # 挂载词库 rime_ice.dict.yaml
```
顺藤摸瓜，查看在其主词库文件`rime_ice.dict.yaml`中的内容（节选）：
```yaml
# Rime dictionary
# encoding: utf-8

---
name: rime_ice
version: "2023-11-13"
import_tables:
  - cn_dicts/8105     # 字表
  # - cn_dicts/41448  # 大字表（按需启用）
  - cn_dicts/base     # 基础词库
  - cn_dicts/ext      # 扩展词库
  # - cn_dicts/tencent  # 腾讯词向量（大词库，部署时间较长）
  - cn_dicts/others   # 一些杂项

  # 建议把扩展词库放到下面，有重复词条时，最上面的权重生效
  # - cn_dicts/mydict
#【下文省略】
```
由此可知，在`rime_ice.dict.yaml`中，声明我自行制作的自定义词库的路径就OK了。
所以，在文件的`# - cn_dicts/mydict`后面，我追加了两行：
```yaml
  - custom-dicts/RIMEPersonalDict
  - custom-dicts/RIMEDotA2
```
由上得到的最终结果：
```yaml
# Rime dictionary
# encoding: utf-8

---
name: rime_ice
version: "2023-11-13"
import_tables:
  - cn_dicts/8105     # 字表
  # - cn_dicts/41448  # 大字表（按需启用）
  - cn_dicts/base     # 基础词库
  - cn_dicts/ext      # 扩展词库
  # - cn_dicts/tencent  # 腾讯词向量（大词库，部署时间较长）
  - cn_dicts/others   # 一些杂项

  # 建议把扩展词库放到下面，有重复词条时，最上面的权重生效
  # - cn_dicts/mydict
  - custom-dicts/RIMEPersonalDict
  - custom-dicts/RIMEDotA2
#【下文省略】
```
最后，**重新部署**即可生效。
