### DISCUSSION TITLE
preedit_type:  是否可以只针对特定程序生效？

### DISCUSSION THREAD

**Discussion by JohnKhanJr** [rime/home#1633] [Q&A]
输入候选窗在Photoshop等程序中无法跟随光标，而是跑到屏幕左上角。
preedit_type: preview_all可以强制让候选内容显示在光标处，但我发现只能作为全局设置，针对特定程序使用并无效果。请问是我的写法不对还是该设置项本就不支持特例？

_下附我的设置参数_

```
patch:
  app_options:
    photoshop.exe:
      ascii_mode: true
      inline_preedit: true
      preedit_type: preview_all                       # 预编辑区显示内容 composition（编码）；preview（高亮候选）；preview_all（全部候选）

```
