### DISCUSSION TITLE
How to insert a list of scalars to a list of scalars at a specific index in the custom yaml

### DISCUSSION THREAD

**Discussion by dhay3** [rime/home#1649] [Q&A]
Greeting rime maintainers and expert users,

Here is my question, I want to insert a list of custom `derive` directives into `speller/algebra` of `double_pinyin.schema.yaml` by `double_pinyin.custom.yaml`. Though it works when insert the list of custom `derive` directives into `double_pinyin.schema.yaml` before the `xform` directives directly, whereas I do prefer to keep  that part in the `double_pinyin.custom.yaml` or not to use `speller/algebra`  to replace the whole part in the custom schema yaml for the reason of rime management.

I've read the documentations of rime and rime-ice, It seems that the `@[before|after]` syntax does want I want. However it does not work as my expected(It transfer the \u\ to the literal u not the \sh\ in double pinyin.), after I‘ve tried this patch directive. 

Now I'm not for sure if it only works for the list of mapping format in yaml( excuse me, I've not read the source code of librime, as for me it is a complicated project. ) or just my using wrong. 

And I'm also read the issues and discussions of rime and rime-ice, not much useful information. By the way I'm using `fcitx5-rime` on Arch linux, I've found no way to debug it by `fcitx5-diagnose` (  if I don't miss something ). And if that is a way I'm glad to offer the information.

The part of the `double_pinyin.schema.yaml`  looks like that.

```yaml
speller:
  algebra:
    - erase/^xx$/
    - derive/^([jqxy])u$/$1v/
    - derive/^([aoe])([ioun])$/$1$1$2/ 
    - xform/^([aoe])(ng)?$/$1$1$2/
    - xform/iu$/Ⓠ/
    - xform/[iu]a$/Ⓦ/
    - xform/[uv]an$/Ⓡ/
    .....
```

The related snippet in `double_pinyin.custom.yaml`

```yaml
patch:
  # Ambiguous Spell
  speller/algebra/@before 3:
     - derive/^([zcs])h/$1/
     - derive/^([zcs])([^h])/$1h$2/
```

Which I want to insert `derive/^([zcs])h/$1/` and `derive/^([zcs])([^h])/$1h$2/` before the `xform/^([aoe])(ng)?$/$1$1$2/`

It would be a highly appreciate if any hints.

Best regards.
