### DISCUSSION TITLE
中文输入状态下能否取消数字小键盘选择候选？还有能否设置小键盘回车上屏英文？

### DISCUSSION THREAD

**Discussion by TYC108301** [rime/home#1696] [Q&A]
如题，中文输入状态下能否取消数字小键盘选择候选？我希望的是数字小键盘就是输入数字，比如说输入”shuru1“，如果1是大键盘上面的数字就是选择第一个候选上屏”输入“，如果是小键盘的数字1那就按下空格上屏”shuru1“，参考搜狗输入法。
还有一个问题是中文输入状态下大键盘回车直接上屏英文，小键盘回车却不可以，能否优化下？

**Comment by yivifu** [comment]
小键盘回车直接上屏英文，可以增加设置，例如在方案名.custom.yaml中：
```
patch:
  editor:
    bindings:
      KP_Enter: commit_raw_input            # 数字键盘回车键：上屏原始输入
```

数字键盘数字不上屏同问。

**Comment by yivifu** [comment]
数字键盘数字取消选择的问题也解决了。创建如下lua脚本（文件名：`kp_num_processor.lua`），增加一个processor：
```lua
-- kp_num_processor.lua
local function processor(key_event, env)
    local key_code = key_event:repr() -- 获取按键名称
    -- 定义数字键盘数字键的映射
    local numpad_keys = {
        ["KP_0"] = "0",
        ["KP_1"] = "1",
        ["KP_2"] = "2",
        ["KP_3"] = "3",
        ["KP_4"] = "4",
        ["KP_5"] = "5",
        ["KP_6"] = "6",
        ["KP_7"] = "7",
        ["KP_8"] = "8",
        ["KP_9"] = "9"
    }
 
    -- 检查是否是数字键盘数字键
    if numpad_keys[key_code] then
        local context = env.engine.context -- 获取输入上下文
        local input_text = context.input -- 获取当前输入的原始码
        if input_text and input_text ~= "" then
            -- 如果有输入的原始码，拼接原始码和数字并提交
            env.engine:commit_text(input_text .. numpad_keys[key_code])
            context:clear() -- 清空输入缓冲区
        else
            -- 如果没有原始码，只提交数字
            env.engine:commit_text(numpad_keys[key_code])
        end
        return 1 -- 表示按键已处理
    end
 
    return 2 -- 未处理，交给其他处理器
end
 
return processor
```
然后配置这个processor，例如在微软双拼输入方案中（`double_pinyin_mspy.schema.yaml`）：
```yaml
-- ……前面的配置内容省略

engine:

  processors:

    - lua_processor@*kp_num_processor

    - lua_processor@*select_character  # 以词定字

    - ascii_composer

-- ……后续配置内容省略
```
