### DISCUSSION TITLE
请问如何禁用 Ctrl+Space 中英文切换

### DISCUSSION THREAD

**Discussion by mantou132** [rime/home#1699] [Q&A]
我是 Windows 系统，系统的 Ctrl+Space 已经关了

但是小狼毫还是会在 Ctrl + Space 时切换，我尝试过：

```
customization:
  distribution_code_name: Weasel
  distribution_version: 0.16.1
  generator: "Rime::SwitcherSettings"
  modified_time: "Fri Jun 21 14:44:30 2024"
  rime_version: 1.11.2
patch:
  "ascii_composer/good_old_caps_lock": false
  "menu/page_size": 7
  "ascii_composer/switch_key":
    Caps_Lock: commit_code
  key_binder/bindings:
    - { when: always, accept: Control+Space, toggle: noop }
```

但是没用

谢谢
