### DISCUSSION TITLE
请问可以设置 space 为选字时的换页键吗？

### DISCUSSION THREAD

**Discussion by kunsin** [rime/home#1767] [Q&A]
用的是【速成】输入法，按了 space 就会把光标目前选的字送出，预置的换页键是 Page_Down, Page_Up。
跟微软输入法的换页选字方式不一样，导致用起来不太顺手，用 patch key_binding 的方式似乎换不了？

请好心的高手协助，万分感谢！

**Comment by yfdyh000** [comment]
```
  key_binder/bindings/+:
      - { when: composing, accept: space, send: Page_Down }
```

**Reply by kunsin** [reply]
请问是在加在哪边才能作用呢？

default.custom.yaml
quick5.schema.yaml
我都试著加上过，也重新布属，但SPACE一按一样出光标目前选的字.

谢谢!

**Reply by yfdyh000** [reply]
default.custom.yaml 中`patch:`下。我用拼音方案测试是可以生效的。
您看看build/default.yaml文件中是否出现了相关定义。

**Comment by kunsin** [comment]
再试过的结果，在 “注音-台湾正体” 是可以作用的，但 quick 就是我在 quick5.schema.yaml, build/default 下加入 patch 也无法使用space换页。

**Reply by lotem** [reply]
不太清楚具體情況。可能補丁沒打對。
另外不要手動編輯 build/ 下面的文件。效果無法保持。

推薦這個做法，直接爲輸入方案打補丁，新建文件 Rime 用戶文件夾/quick5.custom.yaml

```yaml
patch:
  key_binder/bindings/+:
    - { when: has_menu, accept: space, send: Page_Down }
```
