### DISCUSSION TITLE
英文输入模式下开启联想

### DISCUSSION THREAD

**Discussion by freezed-corpse-143** [rime/home#1820] [Ideas]
怎么在英文模式下开启联想，中英文混输不习惯。

**Comment by lotem** [comment]
不支持英文呢。
只支持中文。關閉中文轉換模式就是字母鍵盤直出。

如果要近似地實現所求，可以編寫一個英文輸入方案，再設置一個快捷鍵在中英文輸入方案之間切換。

**Reply by freezed-corpse-143** [reply]
谢谢。但是英文输入法也有中文和英文模式，我容易按到left shift键，切换，怎么禁用切换

**Reply by lotem** [reply]
```yaml
# default.custom.yaml 或 <輸入方案>.custom.yaml
patch:
  ascii_composer/switch_key/Shift_L: noop
```
