### DISCUSSION TITLE
请教：在EmEditor中无法使用小狼毫？

### DISCUSSION THREAD

**Discussion by AnLazyOtter** [rime/home#1821] [Q&A]
# 概述
在几次重启后，突然之间出现了「切换到EmEditor窗口后，自动回退到上一个输入法」的异常现象。想问有可能是我哪里设置的有问题才会出现这样的情况吗？

```yaml
# RimeUserFolder\build\weasel.yaml
__build_info:
  rime_version: 1.9.0
  timestamps:
    weasel: 1709212515
    weasel.custom: 1740238076
app_options:
  dota2.exe:
    inline_preedit: true
  firefox.exe:
    inline_preedit: true
config_version: 0.22
global_ascii: false
```

视频中的操作：

1. 在「记事本」中，能正常输入文本；
2. 切换到「EmEditor」，则会自动回退到上一个使用的输入法。

![小狼毫与EmEditor](https://github.com/user-attachments/assets/51376bb1-fc5b-40b5-a095-12d4542b8bf0)

# 附加信息
当前小狼毫版本：0.15.1
原因是：为使能在DotA2中通过小狼毫输入中文，故回退到了0.15.1版本（参见 https://github.com/rime/weasel/issues/321#issuecomment-1977025909 ），如果可以的话，我希望能在当前版本中解决此问题……
