### DISCUSSION TITLE
求助：有無方法可以開關中英混打？

### DISCUSSION THREAD

**Discussion by HoengSaan** [rime/home#1855] [Q&A]
我希望我的方案（[rime-gukwan](https://github.com/HoengSaan/rime-gukwan)）能開關中英混打，這是我的嘗試。

```
switches:
  - name: ascii_mode
    reset: 0
    states: [ 粵文, 英文 ]
  - name: full_shape
    reset: 0
    states: [ 半角, 全角 ]
  - name: simplification
    reset: 0
    states: [ 深筆, 簡筆 ] 
    abbrev: [ 繁, 簡 ]
  - name: ascii_punct
    reset: 0
    states: [ 。，, ．， ]
  - name: emoji_cantonese_suggestion
    reset: 1
    states: [ 無✖, 有🔴 ]
  - name: melt_eng
    reset: 1
    states: [ 無混, 有混 ] 

gukwan-melt-eng:
  options: melt_eng
  dictionary: gukwan-melt-eng
  enable_sentence: false
  enable_user_dict: false
  initial_quality: 1.1
  comment_format:
    - xform/.*//
```
但這樣不能關閉中英混打的，可能我本身的方向錯誤了。
我的中英混打本身也是參攷網上的案例才能實現，或許關閉中英混打的需求並不多，我並沒有搜索到相關案例。（亦或許是我的搜索能力不足）

如果以上資訊不足，可以看一下整個文件：https://github.com/HoengSaan/rime-gukwan/blob/main/gukwan.schema.yaml
文件裏面可能比較亂，請多多擔待。多謝各位。
