### DISCUSSION TITLE
自定義多套标点符号方案

### DISCUSSION THREAD

**Discussion by ZauberViolino** [rime/home#1877] [Q&A] [answered]
由于個人习惯和生活需要，我将「直角引号」安排在`'` `"`键上。但是有时候又需要输入“弯引号”，而我的其他符号键已经排满，输入“弯引号”不方便也不习惯。我希望我能通过一個switch切换使用「直角引号」和“弯引号”，同一個键在不同的switch下输入不同的标点符号。我明白有全角/半角的切换，但是我不希望影响到其他符号和数字的输入。

我之前在tg群求助过，群友热心提供一些替代建议，但仍然並不是很適合我，因此前来求助。若现在可行，恳请教我如何设置；若不可行，则请當作Feature Request。

我觉得这一功能或许也对別人有用，如有些领域可能需要使用全角句点，但其他符号都不变。或者有些人可能需要在多種特殊的标点符号需求间切换。

谢谢。

**Comment by lotem** [comment, marked as answer]
自定義輸入方案即可。僅修改該符號的定義。

``` yaml
punctuator:
  half_shape:
    "'": { pair: [ 「, 」 ] }
    "\"": { pair: [ 『, 』 ] }
```
