### DISCUSSION TITLE
现在能做到在切换配色方案的同时自动切换布局

### DISCUSSION THREAD

**Discussion by Yimien** [rime/home#1881] [Q&A]
比如我首先下载了别人的配置，然后我又下载了另一个人的配置，这个时候下载的第一份的配色和布局和第二份下载的配色和布局不同，能够实现我在从第一份配色方案切换到第二份配色方案时自动切换为第二份布局而不是第一份布局吗？

```
# patch:
#   show_notifications_time: 200            # 部署通知、中英切换标识  显示时长 ms
#   style:
#     inline_preedit: true
#     color_scheme: MacRoseo                 # 匹配正文的颜色方案，对应正文的颜色方案名
#     display_tray_icon: false
#     horizontal: true                        # 横向排列候选
#     font_point: 13                          # 候选词 字号
#     font_face: "Microsoft Yahei"            # 字体 - 候选文字 例子： "Microsoft Yahei:12:15:bold"
#     label_font_face: "Microsoft Yahei"     # string    序号字体 标注
#     label_font_point: 12                   # number    序号字体 大小
#     comment_font_face: "Microsoft Yahei"   # string    注释字体
#     comment_font_point: 11                 # number    注释字体 大小
#     text_orientation: horizontal                         # horizontal | vertical
#     preedit_type: "composition"            #  "composition" | "preview" | "preview_all"

#     layout:
#       align_type: "bottom"        # string  "top" | "center" | "bottom" 序号、候选词、注释纵向对齐方式
#       corner_radius: 3            # number  圆角大小 候选面板
#       enhanced_position: false    # bool 允许光标位置获取失败时，在当空窗口左上角绘制候选框（而不是桌面左上角）
#       shadow_radius: 3
#       shadow_offset_x: 2          # number 阴影横向偏移量
#       shadow_offset_y: 2          # number 阴影纵向偏移量
#       border_width: 1             # number 边框宽度 候选边框、面板边框
#       candidate_spacing: 10       # number 候选之间的间隔
#       hilite_spacing: 3           # number 序号与候选词之间的间隔 宽度
#       hilite_padding: 0           # number 候选词边界值 宽度
#       margin_x: 9                 # number 内容离边框的，左右边界  当 margin_x 和 margin_y 设置为负值时，将不显示候选窗口，但不影响方案选择
#       margin_y: 5                 # number 内容离边框的，上下边界  当 margin_x 和 margin_y 设置为负值时，将不显示候选窗口，但不影响方案选择

#   preset_color_schemes:   # 主题：颜色方案
#     MacRoseo: # 玫红字体
#       name: 玫红 / MacRoseo
#       author: KyleBing
#       creat_time: "2021-07-26"
#       back_color: 0xFFFFFF
#       border_color: 0x33000000                     # color 面板边框颜色
#       text_color: 0x000000
#       candidate_text_color: 0x000000
#       comment_text_color: 0xBBCC27

#       label_color: 0x999999                        # color 序号颜色 未选中的
#       shadow_color:  0x44000000                    # color 面板阴影

#       nextpage_color:  0x000000                    # color
#       prevpage_color:  0x000000                    # color

#       candidate_back_color:  0xFFFFFF              # color 面板背景色
#       candidate_shadow_color:  0x00000000          # color 面板阴影颜色
#       candidate_border_color:  0x00000000          # color 面板边框颜色

#       hilited_shadow_color:  0xcccccc              # color 阴影颜色 选中的候选
#       hilited_text_color: 0x000000
#       hilited_back_color: 0xEDEDF9

#       hilited_label_color: 0x884F11FA              # color 序号颜色，选中的
#       hilited_candidate_text_color: 0x4F11FA       # color 文字颜色 选中的候选
#       hilited_candidate_back_color: 0x004F11FA     # color 背景色 选中的候选
#       hilited_candidate_shadow_color:  0x004F11FA  # color aarrggbb
#       hilited_candidate_border_color:  0x004F11FA  # color 边框颜色 选中的候选
#       # hilited_mark_color:  0xEDEDF9                # color 候选项前面的高亮颜色


#     MacRoseoAlt: # 玫红背景
#       name: MacRoseo
#       author: KyleBing
#       creat_time: "2021-07-26"
#       back_color: 0xFFFFFF
#       border_color: 0xD6D6D6
#       text_color: 0x000000
#       hilited_text_color: 0x000000
#       hilited_back_color: 0xFFFFFF
#       hilited_candidate_text_color: 0xFFFFFF
#       hilited_candidate_back_color: 0x4F11FA
#       candidate_text_color: 0x000000
#       comment_text_color: 0xBBCC27

#     WhiteAqua: # 水绿背景
#       name: WhiteAqua
#       author: KyleBing
#       creat_time: "2021-07-26"
#       back_color: 0xFFFFFF
#       border_color: 0xD6D6D6
#       text_color: 0x000000
#       hilited_text_color: 0x000000
#       hilited_back_color: 0xFFFFFF
#       hilited_candidate_text_color: 0xFFFFFF
#       hilited_candidate_back_color: 0x9BAD23
#       candidate_text_color: 0x000000
#       comment_text_color: 0xBBCC27

#   style/layout/border_width: 1

# 横排 天圆地方
patch:
  style/+:
    color_scheme: nord                 # 匹配正文的颜色方案，对应正文的颜色方案名
    label_format: "%s"
    inline_preedit: true
    font_face: "HONOR Sans CN"
    font_point: 15
    label_font_face: "HONOR Sans CN"     # string    序号字体 标注
    label_font_point: 15
    comment_font_face: "HONOR Sans CN"   # string    注释字体
    comment_font_point: 14
    horizontal: true
    layout:
      max_width: 1200
      min_width: 10
      margin_x: 15
      margin_y: 6
      hilite_spacing: 6
      hilite_padding_y: 6
      hilite_padding_x: 15
      shadow_radius: 8
      corner_radius: 8
      round_corner: 8
      shadow_offset_x: 5
      shadow_offset_y: 5
  preset_color_schemes:
    nord:                                     # 在 `style/color_schema` 指定的配色方案值
      name: "远山／Nord"                       # 方案设置中显示的配色名称
      author: Mirtle                           # 配色作者名称
      color_format: rgba                       # 颜色格式：argb（0xaarrggbb）；rgba（0xrrggbbaa）；abgr（0xaabbggrr 默认）
      # 默认配色
      text_color: 0x2E3440                     # 文字
      shadow_color: 0x000000b4                 # 阴影
      label_color: 0x4C566A                    # 标签
      comment_text_color: 0xD08770             # 注释
      border_color: 0xECEFF4                   # 边框
      back_color: 0xECEFF4                     # 背景
      # 候选项配色
      # candidate_back_color: 0xECEFF4         # 背景
      # candidate_border_color:                # 边框
      # candidate_shadow_color:                # 阴影
      # candidate_text_color: 0x2E3440         # 文字
      # 高亮区域配色
      hilited_text_color: 0x000000             # 文字
      hilited_back_color: 0xEBCB8B             # 背景
      # hilited_shadow_color:                  # 阴影
      # 选中的候选区域配色
      # hilited_mark_color: 0xBF616A             # 标签前的标记
      hilited_label_color: 0x4C566A            # 标签
      hilited_comment_text_color: 0xBF616A     # 注释
      # hilited_candidate_text_color: 0x2E3440   # 文字
      hilited_candidate_text_color: 0xFEFEFE   # 文字
      hilited_candidate_border_color: 0x8FBCBB # 边框
      hilited_candidate_back_color: 0x8FBCBB   # 背景
      # hilited_candidate_shadow_color:        # 阴影
      # inline_preedit: false 时翻页箭头颜色，不设置则不显示箭头
      nextpage_color: 0xBF616A                 # 下一页
      prevpage_color: 0x000000                 # 上一页
 ```
