### DISCUSSION TITLE
MacOS 挂接小鹤音形如何在中文状态下直接输入英文？

### DISCUSSION THREAD

**Discussion by superacac** [rime/home#1884] [Q&A] [answered]
使用小鹤音形（四码上屏），中英文切换的频率高，使用shift切换太累，有没有在中文状态下又可以输入英文的方法？

**Comment by yana9i** [comment]
我使用的是 [openfly ](https://github.com/amorphobia/openfly)的输入方案 
我不太喜欢四码上屏同时也觉得 shift 切换中英文比较麻烦，所以我 patch 了这几项：
```
patch:
  speller/auto_clear: None
  speller/auto_select: false
  speller/max_code_length: None
  speller/auto_select_pattern: None
```
