### DISCUSSION TITLE
win11自0.14.3更新至0.17.0，补丁失效，custom无法合并至schema中

### DISCUSSION THREAD

**Discussion by ttttinyfish** [rime/home#1916] [General]
使用五笔86方案，之前在0.14.3有效，更新后失效
[原始文件.zip](https://github.com/user-attachments/files/20366627/default.zip)

**Comment by lotem** [comment]
看看錯誤信息吧。

粗看這裏有問題。
補丁一條要改 `punctuator/import_preset`，一條要改上級節點 `punctuator`，兩者有衝突。
究竟 `punctuator` 下面該寫一項 `import_preset`，還是該照着 `punctuator` 定義的那段寫？
我猜測這條補丁本意是只改 `punctuator/half_shape`。

```
patch:
  # 特殊符号的实现
  punctuator/import_preset: default  # 衝
  recognizer/patterns/punct: "^/([a-z]+|[0-9])$
  
  punctuator:  # 突
    half_shape:

```
