### DISCUSSION TITLE
許氏注音如何輸出台灣慣用字

### DISCUSSION THREAD

**Discussion by thlintw** [rime/home#1933] [Q&A]
環境是windows 10小狼毫與mac osx鼠鬚管 皆有一樣問題

看bopomofo_hsuq.schema.yaml內容dictionary使用的是terra_pinyin

目前嘗試過下載一個內有數萬字的terra_pinyin.custom.dict.yaml放入資料夾

將所有「爲」取代為「為」

並在terra_pinyin.custom.yaml內放入

```
patch:
  translator/dictionary: terra_pinyin.custom
```

但並沒有生效

直接修改bopomofo_hsuq.schema.yam內的dictionary為terra_pinyin.custom也無效

另外也試過模仿bopomofo_tw內的設定在terra_pinyin的switch內放入

```
  - options: [zh_hant, zh_hans, zh_hant_tw]
    reset: 2
    states: ["傳統漢字", "简化字", "臺灣字形"]
```

實際的switch只有出現0, 1無法選擇2

請先進解惑該如何正確設定 感謝

**Comment by KmolYuan** [comment]
我的設定是
```yaml
# bopomofo_hsu.custom.yaml
# or bopomofo_hsuq.custom.yaml
patch:
  translator/dictionary: terra_pinyin.custom
```
搭配 `terra_pinyin.custom.dict.yaml`，重新部署即引用新的字典。
