### DISCUSSION TITLE
Shift实现中文输入上屏英文且不切换输入法，无输入时shift切换中英模式

### DISCUSSION THREAD

**Discussion by fc525260** [rime/home#1938] [Q&A]
windows11系统，该输入法配合白霜词库。我想实现以下效果，中文模式下，输入“nihao”，候选词第一个会是“你好”，此时，如果按空格键，候选词第一个会直接上屏；如果按shift键，会上屏“nihao”；如果按caps_lock键，会上屏“NIHAO”;如果按回车键，会上屏“nihao”。同时中文模式下，没有任何输入内容，如果我按shift键，会切换到英文输入法；如果我按caps_lock键，会切换到英文大写模式。目前default.custom.yaml配置如下：
```
patch: 
  # 候选词数量
  "menu/page_size": 9   

  # 使用白霜词库
  schema_list:
    - {schema: rime_frost} 

  # shift键上屏
  "ascii_composer/good_old_caps_lock": true     
  ascii_composer/switch_key:
    Caps_Lock: commit_code   # commit_code，切换大小写并切换到英文，默认大写字母
    Shift_L: commit_codenoop     # commit_code，左shift键直接上屏且rime切换为英文                      
    Shift_R: inline_ascii    # inline_ascii，右shift键后，不上屏，字符转变为英文输入，按Enter键英文字符上屏，之后默认还是中文输入
    Control_L: clear         # clear，左control键，字符被清除，同时RIME输入状态切换为英文输入。再在按此键，RIME输入切换回中文输入
    Control_R: commit_text   # commit_text，右control键，文字上屏，同时RIME切换为英文输入。再按此键，切换回来

  # 只有Alt+grave（Tab上面那个键）可以呼出方案选项
  "switcher/hotkeys": 
    - "Alt+grave"

  # 改掉原来的繁体字标题。
  "switcher/caption": "【设置菜单】"

  # 用半角斜线而不是奇丑无比的全角斜线做分隔符。
  "switcher/option_list_separator": "/"

  #快捷键
  "key_binder/bindings":
    # 使用，。对候选字翻页
    - {accept: comma, send: Page_Up, when: has_menu}
    - {accept: period, send: Page_Down, when: has_menu}
    # 使用 - =对候选字翻页
    - {accept: minus, send: Page_Up, when: has_menu}
    - {accept: equal, send: Page_Down, when: has_menu}
    # 使用Control+Shift+space进行简繁转换
    - {accept: Control+Shift+space, toggle: traditionalization, when: always}
```
 
尝试在key_binder/bindings中添加
```
    # 当有候选词时，Shift键实现与Return键相同的效果（上屏首选词）
    - {accept: Shift_L, send: Return, when: has_menu}
    - {accept: Shift_R, send: Return, when: has_menu}
    
    # 当没有输入内容（无候选词菜单）时，Shift键切换中英文模式
    - {accept: Shift_L, toggle: ascii_mode, when: always}
    - {accept: Shift_R, toggle: ascii_mode, when: always}
```
    
   但由于ascii_composer/switch_key中的优先级更高，在输入中文需要上屏英文时，shift要么是上屏会切换到英文模式，要么就没有任何反应。配置lua脚本也不能覆盖，求教各位。
