### DISCUSSION TITLE
请教关于 __include 和 __patch的用法和限制

### DISCUSSION THREAD

**Discussion by VimWei** [rime/home#1939] [Q&A] [answered]
我注意到雾凇拼音在方案.schema 中采用 `__include`，来导入外部default.yaml文件

```
punctuator:
  __include: default:/punctuator               # 从 default.yaml 导入 punctuator 的所有配置，为了引用 digit_separators 等属性
  full_shape:
    __include: default:/punctuator/full_shape  # 从 default.yaml 导入配置
  half_shape:
    __include: default:/punctuator/half_shape  # 从 default.yaml 导入配置
  symbols:
    __include: symbols_caps_v:/symbols         # 从 symbols_caps_v.yaml 导入配置
```

而万象拼音则再 .custom.yaml中使用`__patch`来导入外部文件的相关内容
```
patch:
  speller/algebra:
    __patch:
      - wanxiang.schema:/小鹤双拼
      - wanxiang.schema:/直接辅助
```
而RIME 程序文件夹中的 default.yaml文件，则都有：

```
punctuator:
  full_shape:
    __include: punctuation:/full_shape
  half_shape:
    __include: punctuation:/half_shape

key_binder:
  bindings:
    __patch:
      - key_bindings:/emacs_editing
      - key_bindings:/move_by_word_with_tab
      - key_bindings:/paging_with_minus_equal
      - key_bindings:/paging_with_comma_period
      - key_bindings:/numbered_mode_switch

```

此外，在 symbols.yaml 中，又有相关的 `import_preset`
```
punctuator:
  import_preset: default
```

请教： `__include` 、 `__patch` 及` import_preset` 的相关用法。我在做些模块化改造时遇到了很多问题，特别是继承、覆盖、深度合并等，在不同场景下出现完全不同的效果，询问cursor等AI，但它们的回答经常颠三倒四，希望有高人能做个指引。
