### DISCUSSION TITLE
请教：如何替换一个节点内容为列表A，并在A之前插入列表B？

### DISCUSSION THREAD

**Discussion by VimWei** [rime/home#1940] [Q&A]
[在大佬 lotem 指引下](https://github.com/rime/home/discussions/1939#discussioncomment-13443162)，学习了半天 [wiki Rime 配置文件](https://github.com/rime/home/wiki/Configuration) ，希望解决一个问题——给“部件拆字”方案添加双拼模糊音功能。在cursor协助下尝试了很久，但发现AI面对这些规则，也显得很笨拙。为此，特来求助：

1. 背景：在radical_pinyin.schema.yaml中有如下定义：
```
speller:
  alphabet: "abcdefghijklmnopqrstuvwxyz;"
  delimiter: " '"
  algebra:
    __include: algebra_pinyin           # 全拼
```

2. 我希望给 radical_pinyin.custom.yaml中实现：
（1） 改用小鹤双拼
（2）添加双拼的模糊音功能：

3. 我的实现草案：虽然能成功重新部署，但模糊音并不能使用，因为最终结果中只有将模糊音规则放在algebra_flypy规则的上面，才能生效。

```
patch:
  speller/algebra:
    __include: radical_pinyin.schema:/algebra_flypy
    __append:
      - derive/^([zcs])h/$1/             # zh, ch, sh => z, c, s
      - derive/^([zcs])([^h])/$1h$2/     # z, c, s => zh, ch, sh
      - derive/([aei])n$/$1ng/           # an => ang, en => eng, in => ing
      - derive/([aei])ng$/$1n/           # ang => an, eng => en, ing => in
      - derive/([iu])an$/$1ang/          # ian => iang, uan => uang
      - derive/([iu])ang$/$1an/          # iang => ian, uang => uan
 ```
 
但我实在想不出来该如何才能实现这个诉求，特求助。

**Comment by VimWei** [comment]
探索各种指令的组合，总结要满足的完整规则如下：
1. 我们有两个列表：fuzzy_rules 和 algebra_flypy，希望用它们替换原有的algebra_pinyin。
2. 我们想要把它们合并成一个列表，而且是fuzzy_rules 在前，algebra_flypy 在后。
3. 使用 `- __include:xxx` 这样的方式，会导致列表以数组形式的引入，无法运行。
4. 同一个map下，不能使用多个相同的键，因此，不能同时使用多个__include。
5. 同一个map下，不能混合使用 map 和 list，因此不能在`__include:xxx`之后直接加列表

要满足这些条件，实在想不出可以复用代码的解决方案。难道只能很笨拙的自己手工合并出一个全集？
虽然可以这样，但这让人感觉RIME语法规则即使很复杂，却还是不够灵活和强大。

```
patch:
  speller/algebra:
    # 模糊拼音 fuzzy_rules
    - derive/^([zcs])h/$1/             # zh, ch, sh => z, c, s
    - derive/^([zcs])([^h])/$1h$2/     # z, c, s => zh, ch, sh
    - derive/([aei])n$/$1ng/           # an => ang, en => eng, in => ing
    - derive/([aei])ng$/$1n/           # ang => an, eng => en, ing => in
    - derive/([iu])an$/$1ang/          # ian => iang, uan => uang
    - derive/([iu])ang$/$1an/          # iang => ian, uang => uan
    # 小鹤双拼规则 algebra_flypy
    - derive/^([jqxy])u(?=^|$|')/$1v/
    - derive/'([jqxy])u(?=^|$|')/'$1v/
    ...
```

**Reply by VimWei** [reply]
我看到万象拼音的custom.yaml处理方式：

```
patch:
  speller/algebra:
    __patch:
      - fuzzy_rules
      - wanxiang.schema:/小鹤双拼
      - wanxiang.schema:/直接辅助
```
但是它有些前提：在schema 或custom中，定义`fuzzy_rules`、`小鹤双拼`等具体规则时，都使用了`__append`，而我们要处理的方案`部件拆字`中，其定义都是直接跟列表项。

```
fuzzy_rules:
  __append:
    - derive/^z([a-z])/v$1/
    - derive/^c([a-z])/i$1/
    - derive/^s([a-z])/u$1/
    - derive/^v([a-z])/z$1/
    ……
```

**Reply by VimWei** [reply]
借鉴万象拼音的成功经验，要解决`部件拆字`的小鹤双拼+模糊音的问题，好像需要做以下改动：

1. **首先，在 radical_pinyin.schema.yaml 中重构规则定义**：
```yaml
# 将原有的直接列表改为使用 `__patch:`来模块化定义
algebra:
  __patch:
    - set_base_rules      # 基础规则
    # 其他基础规则集...

# 定义小鹤双拼规则集，使用`__append`
小鹤双拼:
  __append:
    - derive/^([jqxy])u(?=^|$|')/$1v/
    - derive/'([jqxy])u(?=^|$|')/'$1v/
    # ... 其他小鹤双拼规则

# 定义模糊音规则集，使用`__append`
模糊音规则:
  __append:
    - derive/^([zcs])h/$1/             # zh, ch, sh => z, c, s
    - derive/^([zcs])([^h])/$1h$2/     # z, c, s => zh, ch, sh
    - derive/([aei])n$/$1ng/           # an => ang, en => eng, in => ing
    - derive/([aei])ng$/$1n/           # ang => an, eng => en, ing => in
    - derive/([iu])an$/$1ang/          # ian => iang, uan => uang
    - derive/([iu])ang$/$1an/          # iang => ian, uang => uan
```

2. **然后，在 radical_pinyin.custom.yaml 中使用 `__patch` 组合规则**：
```yaml
patch:
  speller/algebra:
    __patch:
      - radical_pinyin.schema:/模糊音规则    # 模糊音规则在前
      - radical_pinyin.schema:/小鹤双拼      # 小鹤双拼规则在后
```
