### DISCUSSION TITLE
一对多标点的情况，为什么不让用数字键选择？

### DISCUSSION THREAD

**Discussion by Jimmy-Z** [rime/home#1945] [General]
参考 https://github.com/rime/home/wiki/UserGuide#%E8%BC%B8%E5%85%A5%E6%A8%99%E9%BB%9E%E7%AC%A6%E8%99%9F

为什么呢？这样不是会更快捷吗？

**Comment by lotem** [comment]
沒有不讓。可以用數字選。

不過要考慮衝突的情況。數字鍵也可以設置爲符號。

**Comment by Jimmy-Z** [comment]
我这里除了装了五笔，和做了一些外观上的设置，都是默认，但是选标点的时候不能用数字，会直接上屏。

**Comment by lotem** [comment]
要看輸入方案如何設定。出廠配置可以用數字選。

不要籠統地說會如何。
最好有完整的配置和具體的重現步驟。

**Comment by Jimmy-Z** [comment]
安装了 小狼毫 0.17.4，加上了 rime/rime-wubi，除此之外只有外观上的配置我想应该不影响。

default.custom.yaml
```yaml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.17.4
  generator: "Rime::SwitcherSettings"
  modified_time: "Sat Jun 21 13:39:11 2025"
  rime_version: 1.13.1
patch:
  schema_list:
    - { schema: wubi86 }
  menu/page_size: 7
```

weasel.custom.yaml
```yaml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.17.4
  generator: "Weasel::UIStyleSettings"
  modified_time: "Sat Jun 21 13:40:00 2025"
  rime_version: 1.13.1
patch:
  style/+:
    color_scheme: starcraft
    font_face: "Microsoft YaHei : light"
    label_font_face: "Candara"
    comment_font_face: "Candara"
    font_point: "16"
    label_font_point: "11"
    comment_font_point: "11"
    horizontal: true
    inline_preedit: true
    label_format: "%s"
    paging_on_scroll: true
    layout/+:
      border_width: 1
      margin_y: 1
      align_type: bottom
      hilite_spacing: 2
      candidate_spacing: 12
      round_corner: 0
      corner_radius: 0
  preset_color_schemes/+:
    starcraft/+:
      # default color format abgr
      back_color: 0xa0000000
      hilited_label_color: 0x909090
      hilited_comment_text_color: 0x707070
      label_color: 0x808080
      comment_text_color: 0x606060
      hilited_candidate_back_color: 0x00000000
```
