### DISCUSSION TITLE
小狼毫+unicode码输入方案，似乎只能输中文字符

### DISCUSSION THREAD

**Discussion by SogaSuga** [rime/home#768] [Q&A] [answered]
如下图，词库里是有符号的
![01](https://user-images.githubusercontent.com/38813998/114525473-fa653c80-9bfa-11eb-8a48-5dee3803dfd5.jpg)

但是候选里没有
![02](https://user-images.githubusercontent.com/38813998/114525623-19fc6500-9bfb-11eb-9bb1-ddebb01ed024.jpg)

方案里也看不出有问题
```
engine:
  processors:
  translators:
    - punct_translator
    - table_translator
    - reverse_lookup_translator

speller:
  alphabet: "0123456789abcdef"
  initials: "0123456789abcdef"
```
不仅是标点符号，似乎非汉字字符都不行，
同样的方案在鼠须管和同文里则可以输出所有的字符，比如在同文里
![03](https://user-images.githubusercontent.com/38813998/114526168-94c58000-9bfb-11eb-9908-775d48ad31dc.png)

完整方案和词库文件：
[unicode.schema+dict.zip](https://github.com/rime/home/files/6302468/unicode.schema%2Bdict.zip)
