### DISCUSSION TITLE
如何实现上屏原始输入而不切换成英文

### DISCUSSION THREAD

**Discussion by xiaoxiong23333** [rime/home#791] [Q&A] [answered]
查看[文档](https://gist.github.com/lotem/2981316) ascii_composer/switch_key 接受 inline_ascii commit_text  commit_code  这三个值,然而后两个都会切换成英文,第一个是还要再按enter 才能上屏.
我希望能在存在中文输入的时候按shift提交原始字母并保持中文,在没有输入的时候,按shift切换中英文.
在[这里](https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md ) 有看到一个editor 似乎有更多选项,但是我不知道这个该在哪里写.
![Clipboard Image](https://user-images.githubusercontent.com/81311277/118352759-b5d01680-b595-11eb-939c-53c622336ad0.png)

**Comment by lotem** [comment, marked as answer]
按回車鍵上屏按鍵字符​序列

<kbd>Shift</kbd>默認的功能是切換輸入狀態，上屏未完成的輸入或編碼是切換時的副作用

**Comment by csgka1** [comment]
在Linux 下可以这样操作：在 fcitx 的设置中只保留 rime 一个输入法，或者更改 fcitx 中切换输入法的快捷键，不要让 fcitx 在按下左 shift 时切换输入法。这样rime才能接管左 shift 按键。然后用网上给的一般配置即可：
```yaml
patch:
     ascii_composer:
        switch_key:
            Shift_L: commit_code
            Shift_R: commit_code
``` 
这样当按下左 shift 时，rime 会将输入的西文上屏并切换至英文模式。
