### DISCUSSION TITLE
中文输入状态下输入英文

### DISCUSSION THREAD

**Discussion by wang1zhen** [rime/home#827] [Q&A]
由于时常会有在输入中文时，间或输入一些英文字词的需求，能否在不用Shift切换的前提下，提升英文的输入体验（类似微软默认输入法的行为）？

目前困扰：
- 输入小写字母会出现在输入栏中，shift或enter上屏没有问题，但大写英文字母会直接上屏，后续小写字母输入就有一些支离破碎，如图

![图片](https://user-images.githubusercontent.com/31798841/122868766-fe7dab00-d35d-11eb-85ba-5e1073d2e7d8.png)
- 输入一些小写字母，后接一个大写字母，会导致前面的小写字母被按照拼音成为中文，与大写英文一同上屏，输入openSUSE的效果如图

![图片](https://user-images.githubusercontent.com/31798841/122869027-3f75bf80-d35e-11eb-8e3c-3d36c8542f93.png)

- 类似微软输入法有这样的逻辑，如果判断下来可能是英语单词，就会把相应的英语单词放在第一个候选项，方便空格上屏，如图

![图片](https://user-images.githubusercontent.com/31798841/122869229-88c60f00-d35e-11eb-8fbc-f6030fb8c575.png)

是否可以在中文输入状态下，无论大小写字母均进入输入栏，并且遇到大写字母，不要自动上屏？另外，判断中英文字词的要求可能比较难做到，但是能否对于大写字母开头的输入，直接把相应的ascii作为候选首项，方便上屏呢？

**Comment by Ace-Who** [comment]
可以。官方拼音方案的默认配置都直接支持。

**Comment by wang1zhen** [comment]
> 
> 
> 可以。官方拼音方案的默认配置都直接支持。

在我使用默认设置时似乎不是这个行为？

**Comment by lotem** [comment]
大寫字母開頭的在缺省配置裏支持期望的行爲。配置爲：
https://github.com/rime/rime-luna-pinyin/blob/623adb022b094d540218b287c2e601509eee3347/luna_pinyin.schema.yaml#L98
https://github.com/rime/rime-prelude/blob/3de303ffaa731dba07b0462ce59f4767e1219ad2/default.yaml#L55

大小寫字母均進入輸入欄，需要改一項配置，在字母表裏加入大寫字母：
https://github.com/rime/rime-luna-pinyin/blob/623adb022b094d540218b287c2e601509eee3347/luna_pinyin.schema.yaml#L57

**Reply by kuudman** [reply]
感谢！困扰了我很久，解决了！在luna_pinyin.custom.yaml加入下面的
```
  recognizer:
    import_preset: default
    patterns:
      reverse_lookup: "v[a-z]*'?$"
      email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
      uppercase: "^[-_.0-9A-Za-z]*[A-Z][-_.0-9A-Za-z]*$"
```
