### DISCUSSION TITLE
retention的用法在哪里

### DISCUSSION THREAD

**Discussion by pingshunhuangalex** [rime/home#868] [Q&A]
我在有些输入法里看到了利用`retention`来阻止编码过早上屏，但是在文档中没有看到相关API的介绍。

请问哪里可以查询到相关的用法？另外就是还有哪些类似的API是文档里没有提到的，如果有熟悉的人能帮忙罗列一下就好了。谢谢

**Comment by lotem** [comment]
不太瞭解。願聞其詳。

**Reply by pingshunhuangalex** [reply]
了解了一下发现可能只是一个自定义的recognizer pattern而已，并不是Rime的API

我想知道Rime有没有可能可以根据后选项个数决定是否上屏

还有就是有什么办法可一关闭候选菜单 只保留inline preedit

谢谢

**Reply by lotem** [reply]
可以配置爲唯一候選自動上屏
```yaml
speller:
  auto_select: true
```

**Reply by pingshunhuangalex** [reply]
我有设置这个 但是如果我在 recognizer pattern加匹配的话就不会自动上屏了 也就是说pattern的优先级更高

**Reply by MokOopsing** [reply]
关闭候选菜单 只保留inline preedit


```yaml
#weasel.custom.yaml
patch:
  style:
    inline_preedit: true
    preedit_type: preview #composition
    layout:
      margin_x: -99
      margin_y: -99
```
