### DISCUSSION TITLE
功能请求：在ibus切换engine时记住输入模式/ascii_mode

### DISCUSSION THREAD

**Discussion by xlucn** [rime/home#872] [Q&A]
**上游issue**
我在ibus的仓库提交了功能请求： https://github.com/ibus/ibus/issues/2344 

**功能请求**
在ibus切换engine时，即在RIME切换为其它engine前和切换回来后，保持相同的中英状态/ascii_mode（如果确实是ascii_mode负责这个的话）。

**已作调研**
有一个配置项`switches/@0/reset`，不清楚是不是与此相关，也不清楚怎么*不设置*这个选项，即不重置为某一个特定的状态，而是记住之前的值。正因为有这个选项，我觉得实现我的需求可能不难。

**使用情景**
主要情景就是在vim中切换vim模式时，需要同时切换输入法模式。但是下列情形会对使用造成困难：
1. 用Shift键切换到RIME的英文模式下，输入英文
2. 在vim中切换至normal模式，借助插件执行例如`ibus engine xkb:us::eng`
3. 再切换至insert模式，借助插件执行例如`ibus engine rime`
4. RIME会重置为中文输入（默认）

**其它**
相关issue，但是没有精确表述： https://github.com/rime/ibus-rime/issues/118 ，实现了我的请求，可以通过上面的步骤解决该issue。

**Comment by xlucn** [comment]
Alternative:

针对我提出的使用情景，有另一种解决方案，如果能实现下面的功能（无需记忆输入模式）：

使用命令获取当前ascii_mode，或者用任何间接方式知道其状态。

不过rime貌似不提供命令行工具，ibus那边不知道能不能获取RIME的状态信息？

**Comment by lotem** [comment]
`reset: 0` 是要求切換輸入法後設置爲`states`列出的第一個狀態，通常用戶會預期切換輸入法之後即可輸入中文。
可以配置爲記憶狀態，不過這樣配置是否實用，您需要試驗。

```yaml
# luna_pinyuin.custom.yaml
patch:
  switches/@0/reset: # 不要寫 {}
```

```yaml
# default.custom.yaml
patch:
  switcher/save_options/+:
    - ascii_mode
```

**Comment by xlucn** [comment]
@lotem 感谢回复，知道有可能性我就很高兴了。不过我试了一下这两处配置，重复了我上面的使用情景，并没有发现rime记忆了输入状态，见下面的录屏（我最开始使用了Shift调至英文输入）。我尽量除了干扰因素，请麻烦看一下问题可能在哪

Edit: 我发现了一个typo（switcher），我去更正一下，再试一试
Edit: 不行

https://user-images.githubusercontent.com/12032219/132101665-be75afb4-5a0c-4e3f-a8ea-cf62ce7e46ce.mp4

**Comment by xlucn** [comment]
另外，这个如果真的是rime的既有功能（即问题在我的配置，而不在rime），那这就不算issue了，应该可以移至discussion吧。

**Comment by lotem** [comment]
前文的配置不對。改成這樣才能使`reset`無效：

```yaml
# luna_pinyuin.custom.yaml
patch:
  switches/@0/reset:
```

然而，我又發現，有「記住模式」和「臨時切換」兩種操作。
以上配置只支持從方案選單裏切換時記住模式（類比主流輸入法點選狀態欄按鈕）；
而快捷鍵只做臨時切換不記憶，這一點也同主流輸入法一致。
