### DISCUSSION TITLE
luna-pinyin有办法直接在luna_pinyin.custom.yaml配置里禁用掉反查功能吗

### DISCUSSION THREAD

**Discussion by Python-37** [rime/home#890] [Q&A] [answered]
我从来都没使用过笔画反查这个功能，每次同步都带一些笔画输入相关的文件，感觉不方便，请问有不改luna_pinyin.schema.yaml文件禁用笔画反差的方法吗。

**Comment by lotem** [comment, marked as answer]
打補丁修改以下配置項：
https://github.com/rime/rime-luna-pinyin/blob/6e677427764b542313858eaed22c2951d8ec22fe/luna_pinyin.schema.yaml#L17
https://github.com/rime/rime-luna-pinyin/blob/6e677427764b542313858eaed22c2951d8ec22fe/luna_pinyin.schema.yaml#L101

參考資料：
https://github.com/rime/home/wiki/CustomizationGuide#%E5%AE%9A%E8%A3%BD%E6%8C%87%E5%8D%97

**Reply by Python-37** [reply]
我在`luna_pinyin.custom.yaml`文件中patch了
```yaml
    recognizer/patterns:
        punct: "^/([0-9]0?|[a-z]+)$"
        reverse_lookup: ""
    schema/dependencies: []
```
重新部署后发现奏效了，谢谢解答
