### DISCUSSION TITLE
請問怎麼修改翻頁鍵又同時保留預設快捷鍵？

### DISCUSSION THREAD

**Discussion by DDeenngg** [rime/home#952] [Q&A] [answered]
我想修改翻頁鍵，並按照以下指引修改用戶資料夾的default.custom.yaml，結果設置成功但其他預設快捷鍵都不見了，
```yaml
patch:
  "key_binder/bindings":
    - { when: paging, accept: bracketleft, send: Page_Up }
    - { when: has_menu, accept: bracketright, send: Page_Down }
```

我搜尋資料後發現，好像是因為這樣改會覆寫default.yaml中"key_binder/bindings"所有項目。
所以我參考定製指南後加上`/@next`，修改如下：
```yaml
patch:
  "key_binder/bindings/@next":
    - { when: paging, accept: bracketleft, send: Page_Up }
    - { when: has_menu, accept: bracketright, send: Page_Down }
```
結果預設快捷鍵都還在，但是翻頁鍵設置失敗。

原因似乎是在default.yaml裡面會多兩個square brackets
```yaml
- [{accept: bracketleft, send: Page_Up, when: paging}, {accept: bracketright, send: Page_Down, when: has_menu}]
```
我預期default.yaml裡應該要長這樣
```yaml
- {accept: bracketleft, send: Page_Up, when: paging}
- {accept: bracketright, send: Page_Down, when: has_menu}
```
為什麼加了`/@next`後，非我所預期？
所以我要怎麼修改翻頁鍵又同時保留預設快捷鍵？

**Comment by lotem** [comment, marked as answer]
WIKI推薦的方式是在 *輸入方案的* 補丁裏定義 `key_binder/bindings` 列表：
https://github.com/rime/home/wiki/CustomizationGuide#%E4%BB%A5%E6%96%B9%E6%8B%AC%E8%99%9F%E9%8D%B5%E6%8F%9B%E9%A0%81

輸入法程序會先後加載 `key_binder/import_preset` 所指向的預設快捷鍵定義，以及輸入方案裏的快捷鍵定義。

如果一定要修改預設快捷鍵，例如有大量輸入方案都使用相同的快捷鍵設置，可以這樣追加預設快捷鍵：

```yaml
# default.custom.yaml
patch:
  key_binder/bindings/+:
    - { when: paging, accept: bracketleft, send: Page_Up }
    - { when: has_menu, accept: bracketright, send: Page_Down }
```

`@next` 用來向列表末尾追加一個元素，用法如下：
``` yaml
patch:
  key_binder/bindings/@next: {when: composing, accept: Control+g, send: Escape}
```

參考： https://github.com/rime/home/wiki/Configuration

**Comment by DDeenngg** [comment]
您好，感謝您撥冗回覆，問題已解決。
> "含列表的設定項/@next": 在列表最後一個元素之後插入新的設定值（不建議在補靪中使用）

原來是`/@next`只能插入”一個“新的設定值，而且設定值前面還不能有minus，
否則重新部署後，default.yaml裡會多兩個square brackets。
```yaml
#default.custom.yaml
patch:
  key_binder/bindings/@next: 
    - {when: composing, accept: Control+g, send: Escape}
```
```yaml
#default.yaml
key_binder:
  bindings:
    - [{accept: "Control+g", send: Escape, when: composing}]
```

另外補充說明一下，我看的是 `https://rime.im -> 幫助 -> 方案設計（中階） -> 定製指南`，即：
https://github.com/rime/home/wiki/RimeWithSchemata#%E5%AE%9A%E8%A3%BD%E6%8C%87%E5%8D%97
其中內容並無`/+`的使用說明：
```
  "含列表的設定項/+": 與列表合併的設定值（必須為列表）
  "含字典的設定項/+": 與字典合併的設定值（必須為字典，注意 YAML 字典的無序性）
```
但是剛剛發現 `https://rime.im -> 幫助 -> 定製指南（初階） -> 定製指南`，即：
https://github.com/rime/home/wiki/CustomizationGuide#%E5%AE%9A%E8%A3%BD%E6%8C%87%E5%8D%97
有這一段內容。

中階沒有的內容，反而初階卻有😢。
