### DISCUSSION TITLE
如何删除 小狼毫 的英文模式？

### DISCUSSION THREAD

**Discussion by ZeronoFreya** [rime/home#956] [Q&A]
如题，我看到有 [如何删除 鼠须管 的英文模式？](https://github.com/rime/squirrel/issues/221)
也照做了，无效，还是有英文模式

```
// 没用
'switches/@0/states': [中文]

// 删除 ascii_composer没用，其实我不知道怎么删，
// 这样：default.custom.yaml
engine:
    processors: noop
// 还是这样  luna_pinyin_simp.schema.yaml
engine:
  processors:
    # - ascii_composer
```
总之就是无效

那么怎么删除呢？

ps. 这是刚需，我用的软件在输入法模式下无法使用快捷键，需要切到英文模式，小狼毫的英文模式也不行，必须是系统的，虽然这是那个软件的问题，但没法改

**Comment by LEOYoon-Tsaw** [comment]
刪除`engine/processors`下的`ascii_composer`。
如果用`patch`修改會麻煩一些，patch只能加不能刪，可以用patch列出所有除了`ascii_composer `的`processors `

**Reply by ZeronoFreya** [reply]
感谢回复，问题是我不清楚这个所谓的`engine/processors`在哪，我查找配置文件在`luna_pinyin_simp.schema.yaml`等文件里有，我把它注释掉了，我只用`朙月拼音·简化字`

```yaml
engine:
  processors:
    # - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
```

重新部署没用
