### ISSUE TITLE
能否根据分辨率/屏幕尺寸设置候选字符大小? 

### ISSUE THREAD

**Issue by nutnutwin** [rime/home#1011]
笔记本(13.3Inch, 1920✕1080)经常外接27Inch 3840✕2160

笔记本上看起来不错的字符尺寸在台式机上非常小

现在设置的weasel.yaml

```
style:
  color_scheme: youtube
  display_tray_icon: false
  # font_face: "Microsoft YaHei"
  font_face: "LXGW WenKai Mono Bold"
  # font_face: "SimHei"
  font_point: 15
```
