### ISSUE TITLE
请问怎么让symbols自动上屏？

### ISSUE THREAD

**Issue by KeqiZeng** [rime/home#1016]
比如我定义了`"/s": ["ß"]`，只有一个候选项，能不能让`ß`在我按下`/s`的时候自动上屏呢？试过`    "/s": {commit: "ß"}`这样写，好像也没用诶

**Comment by Python-37** [comment]
试试这样配置是否奏效
```yaml
speller:
        auto_select: true
        auto_select_unique_candidate: true
```
