### ISSUE TITLE
关于大写字母上屏的疑问

### ISSUE THREAD

**Issue by KeqiZeng** [rime/home#1018]
我想自制一个支持输入symbols的“假”英文模式用于输入德语，在绝大多数字母都能直接上屏的前提下同时可以输入`äü`等这类。目前的思路是把半角的标点除了用于触发symbols的`/`都定义为英文的标点，`speller/alphabet`中同样只留下用于触发symbols的几个字母。如下：
```yaml
speller:
  # alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA
  alphabet: advs # äöüß
  delimiter: " '"
```
（已禁用ascii_mode模式）
因为我并没有设置词库(`translator/dictionnary`指向不存在的文件)，所以这里我理解的上屏是指输入完字母后按下一次空格是否会真的给我打出一个空格。

目前发现如果我按shift输入大写字母时，大写字母似乎并不会直接上屏，具体行为如下：
直接输入小写字母，除上面定义的`advs`都能自动上屏，例如输入字母`b`后按空格，空格可以直接生效，`b`字母后后会多一个空格，但是如果我用shift临时输入大写字母，大写字母并不会自动上屏，例如输入字母`B`后按空格，第一个空格会将`B`上屏，只有我按下第二个空格时，`B`后才会多出一个空格。想请问一下大佬们，有没有办法可以让输入大写字母时也能自动上屏，使在上面的例子中输入`B`的体验和输入`b`一样呢？万分感谢！

附上完整的schema.yaml文件：
```yaml
# Rime schema
# encoding: utf-8
#


schema:
  schema_id: easy_de
  name: Easy German
  version: "0.1"
  author:
    - ketch
    - idea from BlindingDark <blindingdark@outlook.com> thx!
  description:
    Easy German Input Method


# switches:
  # - name: ascii_mode
  #   reset: 0
  #   states: [ ASCII-OFF, ASCII-ON ]

engine:
  processors:
    # - ascii_composer
    - key_binder
    - speller
    - recognizer
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    # - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    # - table_translator
    - punct_translator
  # filters:
  #   - uniquifier

speller:
  # alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA
  alphabet: advs # äöüß
  delimiter: " '"

punctuator:
  full_shape:
  half_shape:
    "!": {commit: "!"}
    "\"": {pair: ["„", "“"]}
    "#": "#"
    "$": "$"
    "%": "%"
    "&": "&"
    "^": "^"
    "'": "'"
    "(": "("
    ")": ")"
    "*": "*"
    ",": {commit: ","}
    "-": "-"
    _: "_"
    "=": "="
    "+": "+"
    .: {commit: "."}
    "/": ["/", "/"]
    ":": {commit: ":"}
    ";": {commit: ";"}
    "<": "<"
    ">": ">"
    "?": {commit: "?"}
    "@": "@"
    "[": "["
    "\\": "\\"
    "]": "]"
    "`": "`"
    "{": "{"
    "|": "|"
    "}": "}"
    "~": "~"

  symbols:
    "/A": ["Ä"]
    "/D": ["Ö"]
    "/V": ["Ü"]
    "/a": ["ä"]
    # "/o": ["ö"]
    "/d": ["ö"]
    "/v": ["ü"]
    "/s": ["ß"]

recognizer:
  import_preset: default
  patterns:
    punct: "^/([0-9]0?|[A-Za-z]+)$"

translator:
  dictionary: none
  enable_user_dict: false
```

**Comment by LEOYoon-Tsaw** [comment]
删去recognizer/pattern下項

**Comment by KeqiZeng** [comment]
> 删去recognizer/pattern下項

感谢，已经解决了！并且我发现像下面这样写可以让所以字母的大小写直接上屏同时可以输入symbols
```yaml
speller:
    # alphabet: advs # äöüß
    alphabet: /
    initials: /
    delimiter: " '"
```
给需要在英文模式下输入symbols的朋友一个参考。再次感谢！
