### ISSUE TITLE
如何通过切换大小写来切换平片假名？

### ISSUE THREAD

**Issue by Schezuk** [rime/home#1021]
拉丁字母和西里尔字母都能按shift切换大小写，自制的平片假名无法做到。
请问平片假名想建立类似的对应关系应当在哪里进行配置？

**Comment by LEOYoon-Tsaw** [comment]
改編碼

**Comment by Schezuk** [comment]
> 改編碼

在哪里改

**Comment by LEOYoon-Tsaw** [comment]
xxx.dict.yaml

**Comment by Schezuk** [comment]
> xxx.dict.yaml

@LEOYoon-Tsaw 没有哪个dict.yaml出现д Д对应关系甚至没有哪个yaml文件有这个关系，但他就是能大小写切换，请问再哪里配置？

**Comment by LEOYoon-Tsaw** [comment]
沒法配置，改dict

**Comment by Schezuk** [comment]
trime.yaml @LEOYoon-Tsaw @osfans 
```
  kana:
    name: 仮名
    keys:
    - {click: 'あ', long_click: 'ア'}
    - {click: 'ぁ', long_click: 'ァ'}
    - {click: '㋐', long_click: 'ｱ'}
```
@LEOYoon-Tsaw
