### ISSUE TITLE
文檔：自製形碼方案怎麼用朙月拼音反查？

### ISSUE THREAD

**Issue by Eliot00** [rime/home#1041]
我的方案配置如下，按下esc下的按鍵，可以使用朙月拼音打出字，但是後選項裏沒有顯示我自定義方案碼表裏的編碼。請求增加文檔說明怎麼實現反查功能。

![图片](https://user-images.githubusercontent.com/18375468/161421038-095194df-bf44-403a-9a5b-ba4a770a4931.png)

```yaml
engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - affix_segmentor@reverse_lookup
    - punct_segmentor
    - fallback_segmentor
  translators:
    - echo_translator
    - punct_translator
    - table_translator
    - script_translator@reverse_lookup
  filters:
    - uniquifier
    - reverse_lookup_filter@pinyin_reverse_lookup

speller:
  alphabet: zyxwvutsrqponmlkjihgfedcba
  delimiter: " '"
  auto_select: true

translator:
  dictionary: holo

reverse_lookup:
  tag: reverse_lookup
  dictionary: luna_pinyin
  enable_completion: true
  prefix: "`"
  suffix: ";"
  tips: 【拼音反查】
  closing_tips: 【反查关闭】

pinyin_reverse_lookup:
  tags: [ pinyin_reverse_lookup ]
  dictionary: holo

punctuator:
  import_preset: default

key_binder:
  import_preset: default

recognizer:
  import_preset: default
  patterns:
    reverse_lookup: "`[a-z]*;?$"
```
