### ISSUE TITLE
[Question] 对于同时带词频和辅码的词典，无法在有辅码的字典里直接定义字频。

### ISSUE THREAD

**Issue by Oyami-Srk** [rime/home#1046]
有词典如下：
* zrm_pinyin.py
* zrm_pinyin.weight
前者记载不带辅码的字频
后者记载带辅码的字频（同一个字字频相等）

![P1](https://user-images.githubusercontent.com/6939913/162429030-2fc36194-b586-4789-bdf7-8bc9c471d146.jpg)
若给weight加上注释，则单字会根据字频正常在候选列表中排序。
但若取消weight的注释，则单字则乱序排序（乱序规律未找到，起码不是出现在字典中的前后顺序）
![P2](https://user-images.githubusercontent.com/6939913/162429488-409f4233-6624-4a09-b44a-0f2bc2b9ce07.jpg)

方案与字典文件如下：
[zrm.zip](https://github.com/rime/home/files/8451532/zrm.zip)
方案中拼写器的片段如下：
```
speller:
  alphabet: "zyxwvutsrqponmlkjihgfedcba;:"
  initials: 'abcdefghijklmnopqrstuvwxyz'
  delimiter: " '"
  algebra:
    - derive/^(\w*);(\w)(\w)$/$1;$2$3/
    - derive/^(\w*);(\w)(\w)$/$1;$2/
    - derive/^(\w*);(\w)(\w)$/$1/
    - abbrev/^(.{2});+$/$1/
```
根据 #750 似乎可能是拼写器没有配置「主码」，但是这个abbrev难道没有起到省略辅码的作用吗？而且乱序乱的也不是在字典中出现的顺序。
*Github一按回车就Submit就离谱。*
