### ISSUE TITLE
reverse_lookup_filter 匹配由多於一個字組成的詞時出現問題

### ISSUE THREAD

**Issue by whyjz** [rime/home#1095]
各位好，我正在實作一個用中文 (台灣) 注音反查台語注音的反查器，但遇到了一個問題，不確定是 bug 還是有我不知道的設定方法。以下是我的 schema 相關設置： (完整的 schema [在此](https://github.com/whyjz/rime-moetaigi/blob/main/rime-moetaigi/moetaigi-tsuim.schema.yaml))
```
engine:
  filters:
    - reverse_lookup_filter@tsuim_reverse_lookup_hidepinyin
    - reverse_lookup_filter@tsuim_reverse_lookup

#### 中文注音反查的設定 (1) -- 利用中文注音打出漢字
zhuyin:
  tag: zhuyin
  dictionary: terra_pinyin
  prism: bopomofo_tw
  prefix: "`"    # 啟動碼
  spelling_hints: 6
  preedit_format:
    - "xlit|1qaz2wsxedcrfv5tgbyhnujm8ik,9ol.0p;/- 6347'|ㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄧㄨㄩㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦˉˊˇˋ˙ |"
    - xform/^/《中文反查》/
  tips: 《中文反查》

#### 中文注音反查的設定 (2) -- 對於不存在台語注音的漢字詞，在註解中把拼音隱藏起來，並顯示【無台語注音】
tsuim_reverse_lookup_hidepinyin:
  tags: [ zhuyin ]
  overwrite_comment: true
  dictionary: terra_pinyin
  comment_format:
    - xform/^.*$/【無台語注音】/

#### 中文反查模式的設定 (3) -- 如果漢字詞有台語注音，就在候選項後面顯示
tsuim_reverse_lookup:
  tags: [ zhuyin ]
  overwrite_comment: true
  dictionary: moetaigi.unspaced
  comment_format:
    __patch:
      #### 這些是 moetaigi.unspaced 中紀錄的台羅拼音至台語注音的轉譯規則，目前運作正常
      - tsuim:/pinyin_to_tsuim
      - tsuim:/keymap_bopomofo
      - tsuim:/bopomofo_symbols

recognizer:
  patterns:
    zhuyin: "`.*$"
```

然而實際用起來會變成這樣

![moetaigi_reverse-lookup_issue](https://user-images.githubusercontent.com/19339926/178369038-e6c75f5f-e062-4ca8-bc35-b2b057c385da.gif)

觀察如下：
1. 有台語注音的漢字（例如「爬」）正常顯示其注音。
2. 沒有台語注音的漢字（例如「趴」）正常顯示為【無台語注音】。
3. 有台語注音的多字詞（例如「扒飯」）正常顯示其注音。
4. 沒台語注音的多字詞（例如「趴伏」）預計要讓它顯示【無台語注音】，但是不知道為什麼 `comment_format` 沒有作用，顯示了在 `terra_pinyin` 內的拼音原始碼。

有什麼辦法可以讓 comment_format 內的規則也套用在多字詞的條目？
