### ISSUE TITLE
luna_pinyin.custom.yaml里面的设置无效

### ISSUE THREAD

**Issue by segamop** [rime/home#11]
luna_pinyin.custom.yaml里面的设置如下：
patch:
  'punctuator/half_shape':
    "/" : "/"
  'punctuator/import_preset': symbols
  'recognizer/patterns/punct': "^/[a-z0-9][a-z]*$"

但是输入“/”，仍然弹出选字

输入“/xz”，也没有出现星座的特殊符号的选择：

图传不上去。

**Comment by segamop** [comment]
luna_pinyin.custom.yaml里面设置无效，在luna_pinyin.schema.yaml修改了，就行了，不知道是不是custom文件不需要了。

**Comment by jakwings** [comment]
试试我下面贴的配置：

```yaml
patch:
  'punctuator/half_shape':
    '/': '/'
  'punctuator/import_preset': symbols
  'recognizer/patterns/punct': ^/[a-z0-9][a-z]*$
```

你的可能是第三行没缩进好。
