### ISSUE TITLE
“干”和“乾”

### ISSUE THREAD

**Issue by Mjzsl123-github** [rime/home#1110]
如图
![image](https://user-images.githubusercontent.com/110514823/182990411-b8fc4179-8630-4911-95a5-94ced921971c.png)
能否修改OpenCC里的文件让“干”在输入“qian”时不出现？
“乾”同理
![image](https://user-images.githubusercontent.com/110514823/183230550-70ed6fcd-8584-4401-aa76-fad044f71394.png)

**Comment by LEOYoon-Tsaw** [comment]
不能，OpenCC只能基於字轉換

**Comment by Mjzsl123-github** [comment]
好的

**Comment by barrer** [comment]
> 不能，OpenCC只能基於字或詞轉換

@Mjzsl123-github 这个是可以实现的，同样遇到了这个问题，根源就是繁简转换的问题。我自己和面制作了一份原生简体中文词库，词频自己养几个月就好了，见：<https://github.com/barrer/rime-native-simplified-chinese>

**Comment by barrer** [comment]
> 不能，OpenCC只能基於字或詞轉換

@Mjzsl123-github 这个是可以实现的，参见<https://github.com/rime/home/issues/322>这个问题，使用这个词库。
词库使用步骤：

# Rime 使用原生简体中文词库

## 使用步骤

* 导出用户词典（或备份整个 Rime 配置文件夹）
* 停用算法服务
* 删除所有 `*.userdb` 用户词典数据库的文件夹
* 移除所有繁体词库，配置简体词库 `*.dict.yaml` 为 `use_preset_vocabulary: false`
* 修改输方案 `*.custom.yaml` 配置文件，移除现有繁简转换配置（如：`patch/switches/name: simplification`、`patch/engine/filters: simplifier`）
* 启动算法服务
* 重新部署

## 繁体输入

添加如下配置：

```yaml
patch:
# ……
  switches:
    - name: s2tw
      reset: 0
      states: [ 汉字, 漢字 ]
# ……
  engine/filters:
    # ……
    - simplifier@s2tw
    - uniquifier
# ……
  s2tw: # 簡體到臺灣正體
    option_name: s2tw
    opencc_config: s2tw.json
    tips: none
# ……
grammar:/hans
# ……
```
