### ISSUE TITLE
关于yaml的patch补丁语法问题

### ISSUE THREAD

**Issue by qq420100523** [rime/home#1116]
首先我只在wiki里找到了关于patch的一些语法介绍：
```yaml
patch:
  "一級設定項/二級設定項/三級設定項": 新的設定值
  "另一個設定項": 新的設定值
  "再一個設定項": 新的設定值
  "含列表的設定項/@0": 列表第一個元素新的設定值
  "含列表的設定項/@last": 列表最後一個元素新的設定值
  "含列表的設定項/@before 0": 在列表第一個元素之前插入新的設定值（不建議在補靪中使用）
  "含列表的設定項/@after last": 在列表最後一個元素之後插入新的設定值（不建議在補靪中使用）
  "含列表的設定項/@next": 在列表最後一個元素之後插入新的設定值（不建議在補靪中使用）
```
其次我根据https://github.com/rime/rime-emoji这个编写了一份相似的patch配置，非常开心，发现了特别的打开方式。
但当我将两份patch配置同时应用到一个输入法方案时，发现会冲突，然后我检查build目录里生成的schema.yaml，确定了使用上述的patch语法会有问题，比如：
rime-emoji这份patch配置里的emoji_suggestion.yaml：
```yaml
patch:
  switches/@next:
    name: emoji_suggestion
    reset: 1
    states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
  'engine/filters/@before 0':
    simplifier@emoji_suggestion
  emoji_suggestion:
    opencc_config: emoji.json
    option_name: emoji_suggestion
    tips: all
```
switches/@next和我编写的switches/@next:相互覆盖，同样ngine/filters/@before 0也是，谁覆盖谁，取决于打到输入法方案里的顺序，也就是相同配置项，只能最后一个生效。
因为没有更多的文档说明，所以我不太清楚这是特性还是bug，对此语法有了解的同学，请多多指教

**Comment by Ace-Who** [comment]
是特性，所以「不建议在补丁中使用」。可以改用 `/+` 操作符在列表末尾添加任意多个项目，且不会覆盖。
https://github.com/rime/home/wiki/Configuration

```yaml
patch:
  foo/+:
    - ...
    - ...
```
