### ISSUE TITLE
导入扩展词库后无法使用自动造词功能

### ISSUE THREAD

**Issue by feijie825** [rime/home#1117]
使用五笔输入，导入搜狗扩展词库，使用中英混输（easy_en），同时希望使用动态的词库和自动造词功能。
但是一旦导入外部词库，自动造词功能就无法使用。就是说，既无法使用之前的自造词，也无法自动造新词。
下面是我的配置：

```yaml
# wubi86.custom.yaml
patch:
  translator/enable_user_dict: true                 # 用户词典开启/关闭、词序自动调频
  translator/dictionary: wubi86_feijie             # 载入扩展词库
  __include: easy_en:/patch                            # 中英混输
  easy_en/enable_sentence: false                   # 防止英文无意义带太极图案的词
```

```yaml
---
# wubi86_feijie.dict.yaml
name: wubi86_feijie
version: "2022.07.16"
sort: by_wight
use_preset_vocabulary: true

import_tables:
  - wubi86	#这个是默认使用五笔词库，没事别删
  - wubi86_sougou_stand.extended   #这个是搜狗标准库，以后别的词库也要这样输入进来才有效
...
```

```yaml
# wubi86_sougou_stand.extended.dict.yaml
---
name: wubi86_sougou_stand.extended
version: "1.0"
sort: by_weight
columns:
  - text
  - code
  - weight
  - stem
encoder:
  exclude_patterns:
    - '^z.*$'
  rules:
    - length_equal: 2
      formula: "AaAbBaBb"
    - length_equal: 3
      formula: "AaBaCaCb"
    - length_in_range: [4, 10]
      formula: "AaBaCaZa"
...

# 下面是扩展词库内容
啊啊啊	kkkb	1
阿埃二氏病变	bffy	1
阿埃二氏手术	bffs	1
阿埃二氏损害	bffp	1
阿埃二氏细胞	bffe	1
阿埃斯特兰德二氏手术	bfas	1
```
目前基础词库、扩展词库、中英混输功能都正常，但是无法使用自动造词功能，之前的自造词也不会出现。我做过多次尝试，该功能始终无法正常，相同配置情况下如果不导入扩展词库则功能正常。

**Comment by Ace-Who** [comment]
未指定用户词典，默认与固态词典同名，如果要使用 `wubi86` 的用户词典，须定义 `translator/user_dict: wubi86`。
造词规则应当在 `wubi86_feijie.dict.yaml` 中定义。

**Comment by feijie825** [comment]
> translator/user_dict: wubi86

感谢👍，这个问题困扰我好久！
定义 `translator/user_dict: wubi86` 后，之前的自造词就能够出现在候选词列表中了，我之前一直尝试添加 `translator/dictionary: wubi86` 原来是搞错了。目前无法造新词，应该和你说的造词规则相关。

另，我有两个问题：
1. 造词规则是不是这些代码：

```yaml
translator:
  dictionary: wubi86
  enable_charset_filter: true
  enable_sentence: true
  enable_encoder: true
  encode_commit_history: true
  max_phrase_length: 4
  disable_user_dict_for_patterns:
    - "^z.*$"
```

2. 造词规则放在 `wubi86_feijie.dict.yaml` 中是否代表自造词放在扩展词库内了，还是仍然在用户词典内？
    与放在 `wubi86.custom.yaml` 中有什么区别，或者是使用扩展词库必须将造词规则放在 `wubi86_feijie.dict.yaml` 中？
