### ISSUE TITLE
反查快捷鍵 grave 無作用

### ISSUE THREAD

**Issue by z-Wind** [rime/home#1119]
切過去注音，按下 grave 是有反查功能的
但切回自定的嘸蝦米，卻只會打出 grave
請問是弄錯了什麼呢？

schema.yaml 如下
```yaml
# Rime schema
# encoding: utf-8
# 嘸蝦米輸入法（中文模式）
# Schema.yaml 詳解 https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md
schema:
  name: 嘸蝦米
  schema_id: zpsliu
  version: 0.1
  author:
    - "發明人 劉重次"
  description: 嘸蝦米
  dependencies:
    - bopomofo_tw

switches:
  - name: ascii_mode
    reset: 0
    states: ["中文", "英數"]
  - name: full_shape
    states: ["半形", "全形"]
  - name: simplification
    states: ["繁體", "打繁出簡"]
  - name: ascii_punct
    reset: 0
    states: ["標點", "符號"]


engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - affix_segmentor@reverse_lookup
    - punct_segmentor
    - fallback_segmentor
  translators:
    #- echo_translator
    - punct_translator
    - table_translator
    - script_translator@reverse_lookup
  filters:
    - simplifier
    - uniquifier
    - reverse_lookup_filter@bopomofo_reverse_lookup

menu:
# page_size: 5
 alternative_select_keys: "0123456789"

speller:
  alphabet: "abcdefghijklmnopqrstuvwxyz,.'[]"
  max_code_length: 5
  auto_select: false

translator:
  dictionary: zpsliu
  enable_charset_filter: true
  enable_encoder: false
  enable_commit_history: false
  enable_completion: true # 不提示後續按鍵的組字結果
  enable_sentence: false # 關閉連打組句。若要啟動的話需要打開 speller/delimiter 及 enable_user_dict
  enable_user_dict: false # 取消使用者字頻調整機制。若打開的話則無法維持候選字順序。
  preedit_format:
    - "xlit|abcdefghijklmnopqrstuvwxyz,.'[]|ＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺ，．’〔〕"

reverse_lookup:
  tag: reverse_lookup
  dictionary: bopomofo_tw
  enable_completion: true
  prefix: "`"
  suffix: ";"
  tips: 【注音反查】
  closing_tips: 【反查關閉】

bopomofo_reverse_lookup:
  tags: [ reverse_lookup ]
  dictionary: zpsliu

key_binder:
  bindings:
    - { when: always, accept: Shift+space, toggle: full_shape }
    - { when: always, accept: Control+Shift+4, toggle: simplification }
    - { when: has_menu, accept: space, send: space }
    - { when: composing, accept: space, send: Escape }
    - when:   has_menu  # 只要有候選字即滿足條件
      accept: period
      send:   period
  import_preset: default

punctuator:
  import_preset: default

recognizer:
  import_preset: default
```
