### ISSUE TITLE
engine/filters simplifier@* opencc 配置文件无法定位

### ISSUE THREAD

**Issue by LawssssCat** [rime/home#1127]
schema 配置（网上cv的），如下

```yml
switches:
  - name: emoji_suggestion
    reset: 1
    states: [ "❌️ emoji suggestion off", "😁️ emoji suggestion on" ] # 0为关闭、1为开启
engine:
  filters:
    - simplifier@emoji_suggestion # 表情
    - simplifier
    - uniquifier
emoji_suggestion:
  opencc_config: emoji.json # 位于 %rime_dir%/opencc/ 的字符转换配置文件
  option_name: emoji_suggestion # 对应 switches 中的 name
  # tips: all # 字符转换范围
```

上面的配置是希望读取“用户目录”的`opencc/emoji.json`文件吗？

我想应该是的，因为报错日志（`%temp%/rime.weasel.{win10 user name}.log.ERROR.{time string}`）有这么一段

```txt
E0826 10:55:01.631604  9048 simplifier.cc:44] opencc config not found: C:\Users\lawsssscat\AppData\Roaming\Rime\opencc\emoji.json
```

可问题是，如此目录上的文件是存在的

`C:\Users\lawsssscat\Downloads\rime-setting-master\opencc\emoji.json`
```json
{
  "name": "Chinese to Emoji",
  "segmentation": {
    "type": "mmseg",
    "dict": {
      "type": "text",
      "file": "emoji_word.txt"
    }
  },
  "conversion_chain": [{
    "dict": {
      "type": "group",
      "dicts": [{
        "type": "text",
        "file": "emoji_word.txt"
      }]
    }
  }]
}
```

思考了，应该不存在【名字拼写错误/权限问题】。所以就想不明白为啥找不到。

定位到日志这段日志就不知道如何继续排查了

问题：
是我上面配置有问题吗？或者有人遇到类似情况？解决？或者如何继续排查？

---

系统：
win10
rime版本：
```yml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Weasel::UIStyleSettings"
  modified_time: "Thu Aug 25 11:50:28 2022"
  rime_version: 1.5.3
```
