### ISSUE TITLE
部署报错：缺失 .table.bin 文件

### ISSUE THREAD

**Issue by LawssssCat** [rime/home#1134]
之前用着没问题，后面把用户目录 `build` 文件清空了 “重新部署” 报了这个错

```txt
E0903 18:32:31.569679  9004 mapped_file.cc:112] attempt to open non-existent file 'C:\Users\lawsssscat\AppData\Roaming\Rime\build/easy_en.table.bin'.
E0903 18:32:31.569679  9004 table.cc:305] Error opening table file 'C:\Users\lawsssscat\AppData\Roaming\Rime\build/easy_en.table.bin'.
E0903 18:32:31.569679  9004 dictionary.cc:263] Error loading table for dictionary 'easy_en'.
```

清空前有留意到有 `easy_en.table.bin` 文件的

相对应的文件如下：

`easy_en.dict.yaml`

```yml
# Rime dictionary
# mim: set ts=8 sw=8 noet:
# encoding: utf-8
#
# easy_en - Easy English
#
# BlindingDark <blindingdark@outlook.com>
#
# Easy English
#

---
name: easy_en
version: "0.2"
sort: by_weight
use_preset_vocabulary: false
...

a	a
A	A
á	a
Á	A
à	a
À	A
....
....
....
```

```yml
easy_en:
  dictionary: easy_en
  enable_completion: true # 是否启用英文输入联想补全
  enable_sentence: false # 混输时不出现带有图案（太极/陰陽魚符号 “☯️” ）的英文
  # initial_quality: -1 # 英文候选词的位置, 数值越大越靠前
  initial_quality: -0.618 
  spelling_hints: 9
  prefix: ""
  tips: 〔英文〕
  # comment_format:
    # - xform/^.+$//
```

**Comment by LawssssCat** [comment]
@lotem 

请问是否要有 `easy_en.schema.yaml`  才会生成 `build/easy_en.table.bin`？
是否单单有 `easy_en.dict.yaml` 并且 在其他 schema （`my_luna_pinyin.schema.yaml`）中引用 `easy_en/dictionary: easy_en` 是不会生成 `build/easy_en.table.bin` 文件的？

**Comment by lotem** [comment]
應該要有。一個方案文件裏只有`translator/dictionary`指定的詞典會生成。不然各個方案交叉引用詞典，恐怕會重複生成詞典。更重要的是編譯詞典要用到方案裏的其他配置，比如拼寫運算規則`speller/algebra`，必須以一份方案裏的配置爲準。

**Comment by LawssssCat** [comment]
> 應該要有。一個方案文件裏只有`translator/dictionary`指定的詞典會生成。不然各個方案交叉引用詞典，恐怕會重複生成詞典。更重要的是編譯詞典要用到方案裏的其他配置，比如拼寫運算規則`speller/algebra`，必須以一份方案裏的配置爲準。

谢谢，明白了一半。

1. 要在schema中用translator/dictionary指定字典就要配有相应的schema。
2. （疑问）要在dict中用import_tables指定字典就会重复生成字典并统一保存在dict对应的.table.bin中？

请问第二点是这样吗？（我看.table.bin生成的大小刚好和import_tables的大小对的上，所以这样猜想）

**Comment by shewer** [comment]
單獨建立 bin 只要下列幾個條件

```yaml
# Rime schema settings
# encoding: utf-8
# 方案.schema.yaml
#
#

patch:    # desable include custom.yaml


schema:
  schema_id: essay
speller:
  algebra: # prism
    #- xform/^([a-z;,]).([a-z;,])$/$1$2\?/  # 取首尾二碼爲反查三碼字
    #- xform/^([a-z;,])..([a-z;,])$/$1$2\?\?/  # 取首尾二碼爲速成碼反查四碼字
    #- xform/^([a-z;,])...([a-z;,])$/$1$2\?\?\?/  # 取首尾二碼爲速成碼反查五碼字
    #- xlit|abcdefghijklmnopqrstuvwxyz|dmatwfyzljxiekbhsocrugqnpv|
translator:
  dictionary: essay
```
利用 其他方案的 schema/dependencies: [ essay ]  觸發更新製作 bin
