### ISSUE TITLE
词库默认的权重是不是太小？

### ISSUE THREAD

**Issue by iDvel** [rime/home#1151]
举个例子，我的拼音词库的三种写法：
```yaml
抽根烟
抽根烟	chou gen yan
抽根烟	chou gen yan	1
```
初始的输出结果是这样的：
![2022-10-12-000193](https://user-images.githubusercontent.com/14658234/195377366-7d267e70-99b6-453a-bfd4-88034b1c1520.gif)

使用前两种写法时，默认的结果是组合了「抽 chou」「跟 gen」「淹在 yan zai」「看看 kan kan」，
当我给它一个 1 的权重时，或者我手动输入一次「抽根烟」后，结果就正常了，就变成「抽根烟再看看」了。
  
默认的权重不是 1 吗，感觉如果让前两种和最后一种完整写法一致的话，体验比较好，因为很多词库都没有注音或权重。

**Comment by lotem** [comment]
默認值不是1。

要讓結果符合人類的預期，需要賦予程序必要的知識。爲符合本例預期結果的「抽根烟」一詞加大權重，是一種有效的方法。

如果用家把所有詞的詞頻都設爲一樣的值，程序無從計算出「抽根烟再看看」優於其他組合。那時，認爲程序理應識別出在人類的意識中權重更大的詞句，抱持這樣的預期，是毫無道理的。

**Comment by iDvel** [comment]
词库中常用词汇是有权重的，但也有大量没权重的扩展词库，最后发现还是给这些词库都 +1 权重比较舒服。
对于没注音的词库的是通过设置 `columns` 解决的：
```yaml
---
name: xxx
version: "1"
sort: by_weight
columns:
  - text
  - weight
...
你好世界	1
```
