### ISSUE TITLE
递归 import_tables 不起作用

### ISSUE THREAD

**Issue by balthild** [rime/home#1174]
假如有以下词典文件

- a.dict.yaml
- b.dict.yaml
- a1.dict.yaml
- a2.dict.yaml
- b1.dict.yaml
- b2.dict.yaml

其中 a1、a2、b1、b2 内定义了若干短语，而 a 和 b 中只有 import_tables，内容分别如下：

a.dict.yaml:
```yaml
name: a
version: "1"
sort: by_weight

import_tables:
  - b
  - a1
  - a2
```

b.dict.yaml:
```yaml
name: b
version: "1"
sort: by_weight

import_tables:
  - b1
  - b2
```

这样部署之后，发现只有 a1、a1 被导入了，b1、b2 并没有被导入。这是预期现象吗？如果我需要导入 b1、b2，是否必须手动把它们从 b 中拷贝到 a 来？

实际上我准备使用的词典文件的 import_tables 列表中不只有两个项目，此处仅为简化说明。而且这个词典不由我自己维护，在更新版本时，其 import_tables 列表可能会发生变化。因此我才期望用 import_tables 导入词典时，能一并递归导入其下的 import_tables，避免每次更新版本都要重新检查列表的变化和拷贝这个列表。
