### ISSUE TITLE
bug: 基於option的switch在沒有設置reset的時候也會有類似reset的行爲

### ISSUE THREAD

**Issue by fhfuih** [rime/home#1188]
我是Apple Silicon 最新版鼠鬚管0.15.2，擁有以下配置：
```yaml
patch:
  # ...
  switches/=:
    - name: ascii_mode
      # reset: 0
      states: 
        - 中
        - A
    - options: # 這是有問題的設置項
        - zh_simp
        - zh_hk
      states:
        - 简
        - 港
    - name: ascii_punct
      states:
        - "。，"
        - "．，"
    - name: full_shape
      states: 
        - 半角
        - 全角
  zh_simp:
    option_name: zh_simp
    opencc_config: t2s.json
  zh_hk:
    option_name: zh_hk
    opencc_config: t2hk.json
  # ...
```
在switch的第二項中，我故意沒有給`reset`，期待的行爲是切換窗口時保留當前簡繁狀態。但是實際行爲是：切換窗口時rime自動總是自動切換到繁體（即便之前手動設置過簡體），但是切換窗口並且確實處於繁體狀態時，打開`ctrl-\``菜單，顯示打勾勾選的是簡體。但是如果我再強行選擇一次簡體，rime就會真的切換回簡體狀態。此時再切換窗口又會回到“輸出繁體但是菜單顯示正勾選簡體”的狀態。
