### ISSUE TITLE
如何可以做到全局記憶上次輸入的狀態？（非按照個別程序來記憶）

### ISSUE THREAD

**Issue by camxcube** [rime/home#1190]
我知道 Rime 可以記憶上次的輸入狀態，例如中英模式、全/半形和簡繁體等。

但是呢，這個記憶是基於每個程序單獨來記憶的，所以例如說當在程序 A 裏切換到了輸出簡體模式，然後切換到了程序 B 的時候，並不是保留輸出簡體模式。

所以說究竟要如何做到只要在其中一個程序切換好了一個模式，然後切換到任何其他程序時，仍然是那個切換好的模式呢？

---

我的電腦信息：
default.custom.yaml 裏的代碼：
```
patch:
  menu/page_size: 9

  schema_list:
  - schema: cangjie5.basic2
  - schema: flypy_cam

  ascii_composer:
    switch_key:
      Shift_L: commit_code

  switcher:
    abbreviate_options: true 
    caption: " "
    fold_options: true
    hotkeys:
      - "Control+grave"
    option_list_separator: ","
    save_options:
      - ascii_mode
      - full_shape
      - ascii_punct
      - simplification
      - extended_charset

  key_binder:
    bindings:
      - {accept: Tab, send: Page_Down, when: composing}
      - {accept: "Shift+Tab", send: Page_Up, when: composing}
      - {accept: "Control+Shift+1", select: .next, when: always}
      - {accept: "Control+Shift+2", toggle: ascii_mode, when: always}
      - {accept: "Control+Shift+3", toggle: full_shape, when: always}
      - {accept: "Control+Shift+4", toggle: simplification, when: always}
      - {accept: "Control+Shift+5", toggle: extended_charset, when: always}
      - {accept: "Control+Shift+exclam", select: .next, when: always}
      - {accept: "Control+Shift+at", toggle: ascii_mode, when: always}
      - {accept: "Control+Shift+dollar", toggle: simplification, when: always}      
      - {accept: "Control+Shift+numbersign", toggle: full_shape, when: always}
      - {accept: "Control+Shift+percent", toggle: extended_charset, when: always}
      - {accept: "Shift+space", toggle: full_shape, when: always}
      - {accept: "Control+period", toggle: ascii_punct, when: always}
```

輸入法版本：Squirrel 0.15.2
OS 系統版本：macOS Monterey 12.6.2
