### ISSUE TITLE
朙月拼音中，如何配置輸出opencc的香港繁體字？

### ISSUE THREAD

**Issue by justtkcn** [rime/home#1277]
嘗試直接在schema.yaml裡面加入

```yaml
switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
#  - name: simplification
#    states: [ 漢字, 汉字 ]
  - name: ascii_punct
    states: [ 。，, ．， ]
  - options: [zh_cn, zh_tw,zh_hk]
    states:
      - 大陸簡體
      - 臺灣正體
      - 香港繁體
    reset: 3  #默認輸出大陸簡體，如果要默認輸出臺灣正體，請改0為1
engine/filters:
  - simplifier@zh_tw
  - simplifier@zh_cn
  - simplifier@zh_hk
  - uniquifier
zh_tw:
  option_name: zh_tw
  opencc_config: t2tw.json
zh_cn:
  option_name: zh_cn
  opencc_config: t2s.json
zh_hk:
  option_name: zh_hk
  opencc_config: t2hk.json

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - table_translator@custom_phrase
    - reverse_lookup_translator
    - script_translator
  filters:
    - simplifier
    - uniquifier
```
最後都不太行，輸出簡體字都是繁體字，，，輸出香港繁體字也不是對的
