### ISSUE TITLE
在软件内设置默认中文还是英文，并且可以切换中英文输入

### ISSUE THREAD

**Issue by mikaizhu** [rime/home#1282]
我的操作系统：
-  Mac OS
- 
我在Squirrel yaml文件中，进行了如下配置：

```
app_options:
  net.kovidgoyal.kitty:
    # ascii_mode: true
    vim_mode: true
  md.obsidian:
    vim_mode: true
  com.google.Chrome:
    ascii_mode: false
  org.yuanli.utools:
    ascii_mode: true
```
当我打开谷歌浏览器时，输入法会自动切换为中文，但是我想在谷歌浏览器中切换中英文，却发现不能操作。

如何**打开某个软件，可以设置默认的中文或英文输入法，并且可以随意切换中英文？**
