### ISSUE TITLE
win7 

### ISSUE THREAD

**Issue by fanrongqitiancai** [rime/home#1291]
我的系统是win7。下载了weasel-0.14.3.0-installer。安装后，下载了明月拼音的配置文件，链接是这个https://github.com/ssnhd/rime/ 。我把  “配置文件”  里所有的文件复制到用户文件夹里，覆盖以前的所有文件后。我修改任何一个预设的参数，点击重新部署，部署完成。输入法界面没有任何改变。是什么原因？需要重启电脑？还是其它什么原因？
weasel.custom.yaml文件内容如下：
```
customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Weasel::UIStyleSettings"
  modified_time: "Tue May  9 09:42:37 2023"
  rime_version: 1.5.3
patch:
	style:
		color_scheme:fan
	
	preset_color_schemes:
		fan:
			name: 第一
			border_color: 0x6980f1                    # 颜色 - 边框
			text_color: 0x003000                    # 颜色 - 输入中 - 文字

```
效果是这样的
![image](https://user-images.githubusercontent.com/9015263/236976750-d0c0480c-33f9-4d05-8f72-2199fdc7b3ca.png)
