### ISSUE TITLE
请问空码时按空格，能上屏英文编码+空格吗？最好不改码表

### ISSUE THREAD

**Issue by dalilda** [rime/home#1299]
我现在使用小鹤双拼方案，输入cat，再按空格，是上屏英文”cat“
我想上屏英文后再自动加一个空格，最终效果是”cat “
最好不改码表。

**Comment by LEOYoon-Tsaw** [comment]
按一下空格

**Comment by dalilda** [comment]
可是这样的话，就要按两下空格了。。

**Comment by LEOYoon-Tsaw** [comment]
很難準確判斷你的意圖的，不想加空格的時候給你加了，你又會問怎麼這程序如此智障，多加的空格刪起來更不方便

**Comment by dalilda** [comment]
我的码表编码长度都是1到4
我想要这样的效果：
在中英混输的时候，我打了几个中文字，然后要输入一个英文单词，如果我输入1-3个字母没候选字词了；或者输快了，到第4个字母，因为有重码，没有上屏时
我就继续安心输入字母，最后按回车上屏英文。继续打中文。

如果要输入两、三个英文单词。前两个英文单词我可以用空格上屏最后一个用回车上屏。
在这里面，输入第一个单词的时候，如果我按到了3个字母，还是有候选，我就直接按shift切到英文模式输入。如果顺利的话，输入这三个单词的过程中都不需要按shift键，也不需要多按空格。

如果是输好多个英文单词，就直接按shift切英文模式。

-------

现在在打长度1-4的单词时，有重码按回车上屏英文。(ok）
无重码，按回车上屏英文(ok)，按空格上屏英文加空格。(不ok）


打长度4以上的单词时，如果前4个字母匹配到了字词，自动上屏中文，前4个字母消失。第5个字母自动变成下一个次编码的第1个字母。(ok)

如果前4个字母没有匹配到任何字词，空码后面可以继续输入英文字母。
继续输入几个英文字母时：
按下回车，上屏英文。(ok)
但是按下空格，上屏英文加空格。(不ok）
或者长度超过maxlength以后自动清除编码。（ok)

**Comment by dalilda** [comment]
就是说我不想因为一个句子里的一个单词而按shift切换英文模式，再按shift切换回来。
也不想打断输入中文时只需要按一次空格的节奏。

就正常输入英文，需要后面带空格时我就按空格，不需要空格时我就按回车。
输入过程中，发现是要重码了，才按shift。

**Comment by dalilda** [comment]
额忘了说，我的码表里没有英文，都是中文
空码时按空格，是上屏编码加空格，不是从候选栏里上屏英文。和回车上屏编码对应。
与正常时候按空格上屏首选项不一样。

**Comment by dalilda** [comment]
中文句子里输入英文单词。
只有一个英文单词的话，可以用enter上屏英文编码。

有两个单词的话
> 一起来学习computer science吧。
第一个按空格，第二个按回车。

如果三个以上单词，按shift切换英文模式。


如果中文段落里频繁出现连续的一两个单词，来回按shift很麻烦，有时候按一下空格有时候按两下空格很打断节奏

**Comment by dalilda** [comment]
解决了：
```
punctuator:
  import_preset: default
  use_space: true
  half_shape:
    " ": {commit: " "}

key_binder:
  bindings:
    - { when: has_menu, accept: space, send_sequence: "{1}"  } # 上屏首选项
```

这样就能实现有候选项时，空格上屏候选项。空码时上屏英文+空格了。
