### ISSUE TITLE
Windows10下Alt快捷键不起使用

### ISSUE THREAD

**Issue by ForyoungYu** [rime/home#1351]
我在Win10系统下设定了如下快捷键，部署后都不起使用，并且日志里也没有错误。

```yaml
# default.custom.yaml
patch:
  "key_binder/bindings":
    - { accept: Alt+j, send: Down, when: composing }   
    - { accept: Alt+k, send: Up, when: composing }
    - { accept: Alt+i, send: Escape, when: composing }
    - { accept: Alt+d, send: "Shift+Delete", when: composing }
    - { accept: Alt+h, send: Page_Up, when: has_menu }
    - { accept: Alt+l, send: Page_Down, when: has_menu }
````

如果将以上的`Alt`换成`Alt_L`，日志里会说:
```text
# Error Log
parse error: unrecogized modifier 'Alt_L'
invalid key binding #4.
```

请问该如何解决。
