### ISSUE TITLE
iTerm中使用RIME快捷键时遇到的问题

### ISSUE THREAD

**Issue by Idevlnull** [rime/home#1355]
在iTerm2中，通过control+shift+4切换简繁体，或者通过control+period切换中英文标点时，切换功能正常，但是字符4或者小数点会上屏，配置如下，同样的这套配置在Terminal或者MacVim中正常，系统版本macOS 12.3，iTerm2版本3.4.9beta1。

default.custom.yaml
```
patch:
  menu/page_size: 8
  ascii_composer/good_old_caps_lock: false
  ascii_composer/switch_key:
    Caps_Lock: noop
    Shift_L: commit_code
    Shift_R: inline_ascii
    Control_L: noop
    Control_R: noop
  key_binder/bindings:
    - { when: paging, accept: bracketleft, send: Page_Up }
    - { when: has_menu, accept: bracketright, send: Page_Down }
    - { when: composing, accept: Tab, send: Right }
    - { when: composing, accept: Shift+Tab, send: Left }
    - { when: always, accept: Control+period, toggle: ascii_punct}
    - { when: always, accept: Control+Shift+4, toggle: simplification }

```
squirrel.custom.yaml
```
patch:
  style/color_scheme: azure 
  style/font_point: 18 
  style/horizontal: true 
  app_options/com.alfredapp.Alfred:
    ascii_mode: true
  app_options/com.runningwithcrayons.Alfred:
    ascii_mode: true
  app_options/com.googlecode.iterm2:
    ascii_mode: true
    vim_mode: true
    no_inline: true
  app_options/com.apple.Terminal:
    ascii_mode: true
    vim_mode: true
    no_inline: true

```
luna_pinyin_simp.custom.yaml
```
patch:
  switches/@0/reset: 1

```
