### ISSUE TITLE
用组合键切换，不会记忆开关状态

### ISSUE THREAD

**Issue by xiaoqun2016** [rime/home#138]
已知在default.yaml中有如下设定：  
```yaml
switcher:
  save_options:
    - extended_charset  
```
所以rime要记忆extended_charset这个开关的状态？  

但是用Control+Shift+5打开extended_charset，重启之后又变成关闭状态了（不会记忆）。  
若是用F4或Control+grave打开方案选单来切换extended_charset，则会记忆。  

记忆策略不统一，有时候会感觉有点混乱呢
（小狼毫与同文都会这样）
