### ISSUE TITLE
快捷鍵切換到特定輸入方案

### ISSUE THREAD

**Issue by MaxHasBeenUsed** [rime/home#1435]
簡單搜索了一下，發現 issue 裏面有很多類似的需求，但全都被並非我所期待的解決辦法標爲 completed  了：#471 #454 #274

期望實現的功能：能夠自定義快捷鍵切換到**特定**的輸入方案。

比如如果使用輸入方案 A、B，和 C， 可以設定快捷鍵 `Shift+Q` 切換到方案 A，快捷鍵 `Shift+W` 切換到方案 B，`Shift+E`切換到 C。

如此設定完成後，不僅可以快速切換輸入方案，更可以避免輸入方案 >=3 之後循環轉動方案輪盤的不確定感。

**Comment by U1805** [comment]
可以的，设置 key_binder 用 `select` 就好啦  

```yaml
key_binder:
  import_preset: default
  bindings:
    - { when: always, accept: Control+1, select: luna_pinyin } 
```
