### ISSUE TITLE
mac Squirrel 0.16.2版本 按下Shfit + 字母键，就直接输入了大写字母，而不是将大写字母作为候选词进行输入

### ISSUE THREAD

**Issue by sweepingmonk123** [rime/home#1445]
不知道是不是我的设置错误？

`default.custom.yaml`

```
patch:
  schema_list:
    - schema: luna_pinyin_simp      # 朙月拼音
    - schema: double_pinyin_flypy   # 小鹤双拼

  switcher:
    hotkeys:
      - "Control+grave"            # 输入选项菜单 Control + `

  menu/page_size: 9   # 候选词个数

# 若caps切换大小写无效,打开系统偏好设置-键盘-输入法-取消勾选[使用大写锁定键切换“美国”输入模式]
  ascii_composer/good_old_caps_lock: true   # 若为true，caps只切换大小写
  ascii_composer/switch_key:
    Caps_Lock: commit_code                    
    Shift_L: commit_code                    # 左Shift   关闭noop
    Shift_R: commit_code                    # 右Shift
    Control_L: noop                         # 左Control
    Control_R: noop                         # 右Control

  key_binder/bindings: # 翻页(若要开启,去掉前面的#号)
    - { when: composing, accept: ISO_Left_Tab, send: Shift+Left }
    - { when: composing, accept: Shift+Tab, send: Shift+Left }  # "Shift+Tab" 键向左选拼音分词
    - { when: composing, accept: Tab, send: Shift+Right }       # "tab" 键选拼音分词   
    #- { when: composing, accept: Tab, send: Page_Down }        # "tab" 键翻页
    - { when: paging, accept: minus, send: Page_Up }            # "-"上一页
    - { when: has_menu, accept: equal, send: Page_Down }        # "="下一页
    - { when: paging, accept: bracketleft, send: Page_Up }      # "["上一页
    - { when: has_menu, accept: bracketright, send: Page_Down } # "]"下一页
    #- { when: paging, accept: comma, send: Page_Up }            # ","上一页
    #- { when: has_menu, accept: period, send: Page_Down }       # "."下一页
    #- {accept: semicolon, send: 2, when: has_menu}  # 候选2 用分号
    #- {accept: apostrophe, send: 3, when: has_menu} # 候选3 用单引号
 
# 快捷键(若要开启,去掉前面的#号)
    #- {accept: "Control+a", send: Home, when: composing}                   # 光标移至首
    #- {accept: "Control+e", send: End, when: composing}                    # 光标移至尾
    #- {accept: "Control+Shift+1", select: .next, when: always}             # 切换输入方案
    #- {accept: "Control+Shift+2", toggle: ascii_mode, when: always}        # 中英文切换
    #- {accept: "Control+Shift+3", toggle: full_shape, when: always}        # 全角/半角切换
    - {accept: "Control+Shift+4", toggle: simplification, when: always}    # 繁简体切换
    #- {accept: "Control+Shift+5", toggle: extended_charset, when: always}  # 通用/增广切换（显示生僻字）

# 回车清码（若要开启,去掉前面的#号）
    #- {accept: Return, send: Escape, when: composing}   
```

`double_pinyin_flypy.custom.yaml文件`

```
patch:
  schema/name: 小鹤双拼
  switches:
    # - name: ascii_mode
    #   reset: 0
    #   states: [ 中文, 西文 ]
    # - name: emoji_suggestion
    #   reset: 1
    #   states: [ "text", "😊" ]
    # - name: full_shape
    #   states: [ 半角, 全角 ]
    - name: simplification
      reset: 1
      states: [繁, 简]
    # - name: ascii_punct
    #   states: [ 。，, ．， ]
  engine/translators:
    # - lua_translator@date_translator
    # - lua_translator@week_translator
    - punct_translator
    - script_translator
    - table_translator@custom_phrase
  engine/filters:
    # - simplifier@emoji_suggestion
    - simplifier
    - uniquifier
    - charset_filter@gbk
    # - single_char_filter
  engine/processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  # emoji_suggestion:
  #   opencc_config: emoji.json
  #   option_name: emoji_suggestion
  #   tips: all
  reverse_lookup: {}

  #載入朙月拼音擴充詞庫
  'translator/dictionary': luna_pinyin.extended
  'translator/preedit_format': {}



  # 加载easy_en依赖
  "schema/dependencies/@1": easy_en
  # 载入翻译英文的码表翻译器，取名为 english
  "engine/translators/@4": table_translator@english
  # english翻译器的设定项
  english:
    dictionary: easy_en
    spelling_hints: 9
    enable_completion: true      # 是否启用英文输入联想补全
    enable_sentence: false        # 混输时不出现带有图案的英文
    initial_quality: -0.5           # 英文候选词的位置，可以尝试 0 到 0.5 左右的数值。数值越大，英文单词出现的就越靠前。

  # 自定义符号上屏
  punctuator:
    import_preset: symbols
    symbols:
      "/sz": ["①", "②", "③", "④", "⑤", "⑥", "⑦", "⑧", "⑨", "⑩"]
      "/xh": [✱, ★, ☆, ✲]
      # "/dq": [🌍,🌎,🌏,🌐,🌑,🌒,🌓,🌔,🌕,🌖,🌗,🌘]
      # "/sg": [🍇,🍉,🍌,🍍,🍎,🍏,🍑,🍒,🍓,🍗,🍦,🎂,🍺,🍻]
      # "/dw": [🙈,🐵,🐈,🐷,🐨,🐼,🐾,🐔,🐬,🐠,🦋]
      # "/bq": [😀,😁,😂,😃,😄,😅,😆,😉,😊,😋,😎,😍,😘,😗]
      # "/ss": [💪,👈,👉,👆,👇,✋,👌,👍,👎,✊,👊,👋,👏,👐]
    half_shape:
      "/": "、"
      "#": "#"
      "*": "*"
      "`": "`"
      "~": "~"
      "@": "@"
      "=": "="
      '\': ["\\", "|"]
      "%": "%"
      "$": ["¥", "$"]
      "|": "|"
      "{": "「"
      "}": "」"
      "[": "【"
      "]": "】"
      "<": "《"
      ">": "》"

  recognizer/patterns/punct: "^/([0-9]0?|[A-Za-z]+)$"

    

  ### 双拼使用自定义词典 custom_phrase.txt
  custom_phrase:
    dictionary: ""
    user_dict: custom_phrase
    db_class: stabledb
    enable_completion: false
    enable_sentence: false
    initial_quality: 1
  "engine/translators/@5": table_translator@custom_phrase

# Rx: BlindingDark/rime-easy-en:customize:schema=double_pinyin_flypy
  # __include: easy_en:/patch
  # easy_en/enable_sentence: false
# Rx: lotem/rime-octagram-data:customize:schema=luna_pinyin,model=hans
  __include: grammar:/hant
# Rx: BlindingDark/rime-lua-select-character:customize:schema=luna_pinyin
  # __include: lua_select_character:/patch # 需要lua_selector打开本行注释

# librime-lua 输入动态时间和日期
  "engine/translators/@6": lua_translator@date_translator
```
