### ISSUE TITLE
想做一个双拼日语输入法, 双拼转换出来的罗马字无法击中词库

### ISSUE THREAD

**Issue by mannfuri** [rime/home#1458]
配置如下,还在测试中,现在只是把r转为enn, 把f转为ann
```
speller:
  alphabet: "abcdefghijklmnopqrstuvwxyz-_"
  #delimiter: ""
  algebra:
    - derive/(.)enn$/$1r/
    - derive/(.)ann$/$1f/
```

字典文件内的相关词语如下
主要看标绿线的三个词
![图片](https://github.com/rime/home/assets/91338215/732b0740-a385-4515-ab1b-482687d5528a)

基于双拼的输出如下
![图片](https://github.com/rime/home/assets/91338215/fde993a6-0b7c-408c-aaa8-a31310fc30bb)

一般全拼的输出如下
![图片](https://github.com/rime/home/assets/91338215/d8b2b40e-5e45-4fe1-acf8-a98609a7c5b4)

如果这个转换的词,不是第一个,就可以击中词典. 如下两图.
![图片](https://github.com/rime/home/assets/91338215/a40bd2e6-557a-40d3-a252-daa5616dedc8)
![图片](https://github.com/rime/home/assets/91338215/f6625774-21c6-4b49-8531-9e962158d2ce)
