### ISSUE TITLE
Caps_Lock打開時輪入中文？ 

### ISSUE THREAD

**Issue by hbghlyj** [rime/home#1479]
想用Caps Lock 進行輸入法的切換，和mac系統相同，已設置成功，非常感謝。
```
patch:
  ascii_composer:
    good_old_caps_lock: false
    switch_key:
      Caps_Lock: inline_ascii
      Shift_L: noop
      Shift_R: noop
```
想用Caps Lock 進行輸入法的切換，但跟mac系統相反：打開Caps Lock 時輪入中文，關閉時Ascii mode，請問如何設置？
