### ISSUE TITLE
配置文件的问题

### ISSUE THREAD

**Issue by hwypengsir** [rime/home#1523]
我的ibus-rime版本
```
sudo dpkg -l  ibus-rime | grep -A  2 Version 
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  ibus-rime      1.5.0-3      amd64        Rime Input Method Engine for IBus
```
配置文件：
```
ls   ~/.config/ibus/rime
build  installation.yaml  luna_pinyin.custom.yaml   luna_pinyin.userdb  sync	user.yaml
```
我已经设置成使用简体汉字

```
cat   luna_pinyin.custom.yaml
# encoding: utf-8
patch:
  switches:
    - name: ascii_mode
      reset: 0
      states: ["中文", "西文"]
    - name: full_shape
      states: ["半角", "全角"]
    - name: simplification
      reset: 1
      states: ["漢字", "汉字"]
    - name: ascii_punct
      states: ["。，", "．，"]
```
现在我进行了下面的操作：
```
cd  ~/.config/ibus/rime
cp  luna_pinyin.custom.yaml  luna_pinyin_simp.custom.yaml
rf  luna_pinyin.custom.yaml 
```
为何这样做不行呢？
