### ISSUE TITLE
如何关闭ctrl+shift+3的快捷键

### ISSUE THREAD

**Issue by shanghaox** [rime/home#1532]
ctrl+shift+3切换全半角的功能用不上，和其他软件快捷键冲突，希望能关闭。
我找了一下配置文件，没有找到快捷键的配置。烦请各位大佬解答

**Comment by lotem** [comment]
輸入方案（舉例）裏設置爲使用預定義的快捷鍵 `default:/key_binder/bindings`：
https://github.com/rime/rime-luna-pinyin/blob/79aeae200a7370720be98232844c0715f277e1c0/luna_pinyin.schema.yaml#L95

後者定義了這個快捷鍵：
https://github.com/rime/rime-prelude/blob/dd84abecc33f0b05469f1d744e32d2b60b3529e3/default.yaml#L50

修改快捷鍵：
```yaml
# luna_pinyin.custom.yaml
patch:
  key_binder:
    bindings:
      # 從 default.yaml 裏把有用的抄下來
```
