### ISSUE TITLE
无法指定应用程序默认英文

### ISSUE THREAD

**Issue by demonxinghen** [rime/home#1537]
我的系统是win11
weasel.custom.yaml的配置是：
`
patch:
  app_options/cmd.exe:
    ascii_mode: true
`
double_pinyin_flypy.schema.yaml的配置是：
`
switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: simplification
    reset: 1
    states: [ 漢字, 汉字 ]
`
但是打开cmd程序后，默认输入依然是中文

**Comment by fxliang** [comment]
供参考
```yaml
patch:
  app_options:
    nvy.exe:
      vim_mode: true
      ascii_mode: true
    nvim-qt.exe:
      vim_mode: true
    neovide.exe:
      vim_mode: true
    gvim.exe:
      ascii_mode: true
      vim_mode: true
    firefox.exe:
      inline_preedit: true
      ascii_mode: true
    mintty.exe:
      ascii_mode: true
    vscodium.exe:
      vim_mode: true
    conhost.exe:
      ascii_mode: true
```

**Comment by xuejianxianzun** [comment]
我也遇到了这个问题。在  `weasel.custom.yaml` 里，对 cmd.exe 的默认英文状态无效。但试了其他一些程序（如 qq.exe、notepad.exe 是有效的）。原因不清楚，这有点不方便。

```yaml
  app_options/cmd.exe:
    ascii_mode: true
  app_options/notepad.exe:
    ascii_mode: true
```

**Comment by fxliang** [comment]
> 我也遇到了这个问题。在 `weasel.custom.yaml` 里，对设置 cmd.exe 默认英文输入状态无效。但试了其他一些程序（如 qq.exe、notepad.exe）是有效的。不清楚原因，但这确实有点不方便。
> 
> ```yaml
>   app_options/cmd.exe:
>     ascii_mode: true
>   app_options/notepad.exe:
>     ascii_mode: true
> ```

向上一个回复就有答案，因为`cmd.exe`实际运行的是`conhost.exe`

**Comment by xuejianxianzun** [comment]
> ```yaml
> ascii_mode: true
> ```

抱歉，我试了还是不行：
![image](https://github.com/user-attachments/assets/8331a332-8eaf-46d3-93b8-e6995066c1aa)
我从运行里打开 cmd.exe，依然是默认中文。但作为对照组的 QQ 实现了默认英文。

**Comment by guoche21** [comment]
+1，只有 `notepad.exe` 有效，其他 `exe` 比如企业微信、Cursor  和终端都无效，大小写试了都没用

环境为 windows10，使用 `tasklist` 命令查看了进程名也是也是正确的

```
Cursor.exe                   19840 Console                    1    123,320 K
msedge.exe                   24456 Console                    1     13,664 K
audiodg.exe                  15372 Services                   0     12,468 K
Code.exe                     12236 Console                    1    148,944 K
Code.exe                     18692 Console                    1     29,756 K
Code.exe                      6704 Console                    1    188,192 K
Code.exe                     20648 Console                    1     50,764 K
Code.exe                     21592 Console                    1    199,972 K
Code.exe                     17848 Console                    1    139,460 K
Code.exe                     17096 Console                    1    121,272 K
Code.exe                      4476 Console                    1     94,600 K
msedge.exe                   23644 Console                    1     21,304 K
msedge.exe                   23120 Console                    1    189,936 K
msedge.exe                   24352 Console                    1    115,332 K
SearchProtocolHost.exe       16268 Services                   0     15,744 K
SearchProtocolHost.exe       15868 Console                    1      8,976 K
msedge.exe                   24812 Console                    1     30,936 K
svchost.exe                  25244 Services                   0      8,068 K
svchost.exe                  25324 Services                   0      7,796 K
SearchFilterHost.exe         24104 Services                   0      7,740 K
OpenConsole.exe              25452 Console                    1      9,700 K
cmd.exe                      20520 Console                    1      4,864 K
tasklist.exe                  8672 Console                    1      9,408 K
WmiPrvSE.exe                 14440 Services                   0     10,692 K
```

`weasel.custom.yaml`
```yaml
patch:
  app_options/Cursor.exe:
    ascii_mode: true
  app_options/cursor.exe:
    ascii_mode: true
  app_options/Code.exe:
    ascii_mode: true
  app_options/code.exe:
    ascii_mode: true
  app_options/cmd.exe:
    ascii_mode: true
  app_options/notepad.exe:
    ascii_mode: true
 ```

`build` 文件夹里面的 `weasel.yaml`

```yaml
__build_info:
  rime_version: 1.11.2
  timestamps:
    weasel: 1734937200
    weasel.custom: 1734937835
app_options:
  Code.exe:
    ascii_mode: true
  Cursor.exe:
    ascii_mode: true
  cmd.exe:
    ascii_mode: true
  code.exe:
    ascii_mode: true
  cursor.exe:
    ascii_mode: true
  firefox.exe:
    inline_preedit: true
  windowsterminal.exe:
    ascii_mode: true
  wt.exe:
    ascii_mode: true
  wxwork.exe:
    ascii_mode: false
```
