### ISSUE TITLE
宫保拼音：键盘控式 里是否可以定义Alt键或者日式JIS键盘的“变换”键输入？

### ISSUE THREAD

**Issue by EchoMinx** [rime/home#155]
直接使用
```
chord_composer:
  alphabet: 'gtbfrvdecswxa”Alt_R"hynjum ki,/lo.'
  algebra:
    - 'xlit|gtbfrvdecswxa"Alt_R"hynjum ki,/lo.|gtpzdbclfsczHhXYRiuVaNIUWeoE|'
```
或者
```
key_binder:
  import_preset: default
  bindings:
    - {accept: "Alt_R", send: ;, when: always}
```
都会导致崩溃_(:3J∠)_
