### ISSUE TITLE
mac上是否有办法实现按shift进行中日文切换的操作？

### ISSUE THREAD

**Issue by BlueWhitePants** [rime/home#1572]
对于按shift，rime原本的操作是进行中英文切换；我想是否能够将之改为在中日文之间切换？
我在default.custom.yaml中尝试修改，比如添加- { when: always, accept: Shift_L, select: japanese }，但是并不能实现，即使我设置了Shift_L: noop

**Comment by LEOYoon-Tsaw** [comment]
試試Shift+Shift_L

**Comment by BlueWhitePants** [comment]
> 試試Shift+Shift_L

好像不太行:-(

**Comment by LEOYoon-Tsaw** [comment]
```yaml
key_binder:
  bindings:
    - { when: always, accept: Shift+Shift_L, select: luna_pinyin }
```
切實可用
