### ISSUE TITLE
如何只在反查中使用繁简转换，方案中不使用繁简转换？（五代仓颉，反查使用拼音）

### ISSUE THREAD

**Issue by BH2WFR** [rime/home#1579]
已知反过来可以这么写（方案使用繁简转换，但反查不使用繁简转换）
simplifier:
  tips: all  # 簡化字模式下提示對應的傳統漢字
  excluded_types: [ reverse_lookup ] # 反查不使用繁简转换

如何做到与上述内容相反，在方案中不使用繁简转换，但在反查中使用繁简转换？

**Comment by LEOYoon-Tsaw** [comment]
simplifier can use tags:
```yaml
zh_simp:
  opencc_config: t2s.json
  option_name: simplification
  tags: [ pinyin, jyutping, abc ]
  tips: none
```
