### ISSUE TITLE
鼠须管从0.15.0升级到1.0.1之后，和color_scheme相关的配置失效

### ISSUE THREAD

**Issue by evilucifero** [rime/home#1583]
Macbook Pro 16-inch, 2019
macOS 14.4.1
Intel Core

squirrel.custom.yaml
```
# Squirrel settings
# encoding: utf-8

config_version: "0.22"

patch:
  us_keyboard_layout: false

  # for veteran chord-typist
  chord_duration: 0.1  # seconds

  # options: always | never | appropriate
  show_notifications_when: appropriate

  # Show notifications via Notification Center instead of Growl.
  # (Only valid if OS version is at least 10.8 and
  #  'show_notifications_when' is NOT set to 'never'.)
  show_notifications_via_notification_center: true

  style:
    color_scheme: dark_temple
    horizontal: true
    inline_preedit: false
    corner_radius: 10
    border_height: 0
    border_width: 0
    line_spacing: 1
    spacing: 5
    font_face: 'Lucida Grande'
    font_point: 18
    label_font_point: 16

  app_options:
    com.alfredapp.Alfred:
      ascii_mode: true
    com.runningwithcrayons.Alfred-2:
      ascii_mode: true
    com.blacktree.Quicksilver:
      ascii_mode: true
    com.apple.Terminal:
      ascii_mode: true
      no_inline: true
    com.googlecode.iterm2:
      ascii_mode: true
    org.vim.MacVim:
      ascii_mode: true
      no_inline: true
    #com.apple.dt.Xcode:
    #  ascii_mode: true
    #com.barebones.textwrangler:
    #  ascii_mode: true
    #com.macromates.TextMate.preview:
    #  ascii_mode: true
    #com.sublimetext.2:
    #  ascii_mode: true
    #org.gnu.Aquamacs:
    #  ascii_mode: true
    #org.gnu.Emacs:
    #  ascii_mode: true
```

部署完毕以后的 squirrel.custom.yaml
```
__build_info:
  rime_version: 1.11.2
  timestamps:
    squirrel: 1717178200
    squirrel.custom: 1717477828
app_options:
  com.alfredapp.Alfred:
    ascii_mode: true
  com.apple.Terminal:
    ascii_mode: true
    no_inline: true
  com.blacktree.Quicksilver:
    ascii_mode: true
  com.googlecode.iterm2:
    ascii_mode: true
  "com.runningwithcrayons.Alfred-2":
    ascii_mode: true
  org.vim.MacVim:
    ascii_mode: true
    no_inline: true
chord_duration: 0.1
config_version: 1.0
keyboard_layout: last
preset_color_schemes:
  apathy:
    author: "LIANG Hai"
    back_color: 0xFFFFFF
    border_height: 0
    border_width: 0
    candidate_format: "%c %@ "
    comment_text_color: 0x999999
    corner_radius: 5
    font_face: "PingFangSC-Regular,HanaMinB"
    font_point: 16
    hilited_candidate_back_color: 0xFFF0E4
    hilited_candidate_text_color: 0xEE6E00
    horizontal: true
    inline_preedit: true
    label_font_face: "STHeitiSC-Light"
    label_font_point: 12
    name: "冷漠／Apathy"
    text_color: 0x424242
  aqua:
    author: "佛振 <chen.sst@gmail.com>"
    back_color: 0xeeeceeee
    candidate_text_color: 0x000000
    comment_text_color: 0x5a5a5a
    hilited_candidate_back_color: 0xeefa3a0a
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xfcac9d
    hilited_text_color: 0x000000
    name: "碧水／Aqua"
    text_color: 0x606060
  azure:
    author: "佛振 <chen.sst@gmail.com>"
    back_color: 0xee8b4e01
    candidate_text_color: 0xffeacc
    comment_text_color: 0xc69664
    hilited_candidate_back_color: 0x00000000
    hilited_candidate_text_color: 0x7ffeff
    hilited_text_color: 0xffeacc
    name: "青天／Azure"
    text_color: 0xcfa677
  clean_white:
    author: "Chongyu Zhu <lembacon@gmail.com>, based on 搜狗「简约白」"
    back_color: 0xeeeeee
    border_height: 6
    border_width: 6
    candidate_format: "%c %@"
    candidate_text_color: 0x000000
    comment_text_color: 0x808080
    corner_radius: 6
    font_point: 16
    hilited_candidate_back_color: 0xeeeeee
    hilited_candidate_label_color: 0xa0c98915
    hilited_candidate_text_color: 0xc98915
    hilited_text_color: 0x000000
    horizontal: true
    label_color: 0x888888
    label_font_point: 12
    name: "简约白／Clean White"
    text_color: 0x808080
  dark_temple:
    author: "佛振 <chen.sst@gmail.com>, based on ir_black"
    back_color: 0x222222
    candidate_text_color: 0xd8e3e6
    comment_text_color: 0x606cff
    hilited_back_color: 0x222222
    hilited_candidate_back_color: 0x10000000
    hilited_candidate_text_color: 0x92f6da
    hilited_text_color: 0xffcf9a
    name: "暗堂／Dark Temple"
    text_color: 0x92f6da
  dust:
    author: "Superoutman <asticosmo@gmail.com>"
    back_color: 0xeeffffff
    border_color: 0xE0B693
    border_height: 3
    border_width: 8
    candidate_format: "%c %@ "
    candidate_text_color: 0x555555
    comment_text_color: 0x999999
    corner_radius: 2
    font_face: "HYQiHei-55S Book,HanaMinA Regular"
    font_point: 14
    hilited_candidate_back_color: 0xfff0e4
    hilited_candidate_label_color: 0x555555
    hilited_candidate_text_color: 0x000000
    hilited_comment_text_color: 0x9e9e9e
    hilited_text_color: 0x9e9e9e
    horizontal: true
    inline_preedit: true
    label_color: 0xcbcbcb
    label_font_face: SimHei
    label_font_point: 10
    name: "浮尘／Dust"
    text_color: 0x424242
  google:
    author: "skoj <skoj@qq.com>"
    back_color: 0xFFFFFF
    border_color: 0xE2E2E2
    candidate_text_color: 0x000000
    comment_text_color: 0x6D6D6D
    hilited_back_color: 0xFFFFFF
    hilited_candidate_back_color: 0xCE7539
    hilited_candidate_text_color: 0xFFFFFF
    hilited_comment_text_color: 0xEBC6B0
    hilited_text_color: 0x000000
    name: "谷歌／Google"
    text_color: 0x666666
  ink:
    author: "佛振 <chen.sst@gmail.com>"
    back_color: 0xeeffffff
    candidate_text_color: 0x000000
    comment_text_color: 0x5a5a5a
    hilited_candidate_back_color: 0xcc000000
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0x808080
    hilited_text_color: 0x000000
    name: "墨池／Ink"
    text_color: 0x5a5a5a
  lost_temple:
    author: "佛振 <chen.sst@gmail.com>, based on ir_black"
    back_color: 0xee303030
    comment_text_color: 0xbb82e6ca
    hilited_candidate_back_color: 0x82e6ca
    hilited_candidate_text_color: 0x000000
    hilited_comment_text_color: 0xbb203d34
    hilited_text_color: 0x82e6ca
    name: "孤寺／Lost Temple"
    text_color: 0xe8f3f6
  luna:
    author: "佛振 <chen.sst@gmail.com>"
    back_color: 0xdd000000
    candidate_text_color: 0xeceeee
    comment_text_color: 0xa5a5a5
    hilited_candidate_back_color: 0x40000000
    hilited_candidate_text_color: 0x7fffff
    hilited_comment_text_color: 0x449c9d
    hilited_text_color: 0x7fffff
    name: "明月／Luna"
    text_color: 0xa5a5a5
  mojave_dark:
    author: "xiehuc <xiehuc@gmail.com>"
    back_color: 0x252320
    border_color: 0x020202
    border_height: 6
    border_width: 6
    candidate_format: "%c %@"
    candidate_text_color: 0xdedddd
    comment_text_color: 0xdedddd
    corner_radius: 5
    font_face: PingFangSC
    font_point: 16
    hilited_back_color: 0x252320
    hilited_candidate_back_color: 0xcb5d00
    hilited_candidate_label_color: 0xffffff
    hilited_candidate_text_color: 0xffffff
    hilited_corner_radius: 3
    hilited_text_color: 0xdedddd
    horizontal: true
    inline_preedit: true
    label_color: 0x888785
    label_font_point: 14
    name: "沙漠夜／Mojave Dark"
    text_color: 0xdedddd
  native:
    name: "系統配色"
  psionics:
    author: "雨過之後、佛振"
    back_color: 0x444444
    candidate_text_color: 0xeeeeee
    comment_text_color: 0x808080
    hilited_back_color: 0x444444
    hilited_candidate_back_color: 0xd4bc00
    hilited_candidate_label_color: 0xfafafa
    hilited_candidate_text_color: 0xfafafa
    hilited_comment_text_color: 0x444444
    hilited_text_color: 0xeeeeee
    name: "幽能／Psionics"
    text_color: 0xc2c2c2
  purity_of_essence:
    author: "佛振"
    back_color: 0xfafafa
    candidate_text_color: 0x000000
    comment_text_color: 0x808080
    hilited_back_color: 0xfafafa
    hilited_candidate_back_color: 0x444444
    hilited_candidate_text_color: 0xeeeeee
    hilited_text_color: 0x000000
    name: "純粹的本質／Purity of Essence"
    text_color: 0x2c2ccc
  purity_of_form:
    author: "雨過之後、佛振"
    back_color: 0x444444
    candidate_text_color: 0xeeeeee
    comment_text_color: 0x808080
    hilited_back_color: 0x444444
    hilited_candidate_back_color: 0xfafafa
    hilited_candidate_text_color: 0x000000
    hilited_text_color: 0xeeeeee
    name: "純粹的形式／Purity of Form"
    text_color: 0xc2c2c2
  solarized_dark:
    author: "雪齋 <lyc20041@gmail.com>"
    back_color: 0xF0352A0A
    border_color: 0x2A1F00
    candidate_text_color: 0x7389FF
    comment_text_color: 0xC38AFF
    hilited_back_color: 0xC9DADF
    hilited_candidate_back_color: 0x403516
    hilited_candidate_label_color: 0xCC8947
    hilited_candidate_text_color: 0x989F52
    hilited_comment_text_color: 0x289989
    hilited_text_color: 0xBE706D
    label_color: 0x478DF4
    name: "曬經・月／Solarized Dark"
    preedit_back_color: 0xD7E8ED
    text_color: 0x756E5D
  solarized_light:
    author: "雪齋 <lyc20041@gmail.com>"
    back_color: 0xF0E5F6FB
    border_color: 0xEDFFFF
    candidate_text_color: 0x595E00
    color_space: display_p3
    comment_text_color: 0x005947
    hilited_back_color: 0x4C4022
    hilited_candidate_back_color: 0xD7E8ED
    hilited_candidate_label_color: 0x2566C6
    hilited_candidate_text_color: 0x3942CB
    hilited_comment_text_color: 0x8144C2
    hilited_text_color: 0x2C8BAE
    label_color: 0xA36407
    name: "曬經・日／Solarized Light"
    preedit_back_color: 0x403516
    text_color: 0xA1A095
  solarized_rock:
    author: "Aben <tntaben@gmail.com>, based on Ethan Schoonover's Solarized color scheme"
    back_color: 0x362b00
    border_color: 0x362b00
    candidate_text_color: 0x969483
    comment_text_color: 0xc098a12a
    hilited_candidate_back_color: 0x8236d3
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0x362b00
    hilited_text_color: 0x98a12a
    name: "曬經石／Solarized Rock"
    text_color: 0x8236d3
  starcraft:
    author: "Contralisk <contralisk@gmail.com>, original artwork by Blizzard Entertainment"
    back_color: 0xee000000
    border_color: 0x1010a0
    candidate_text_color: 0x30bb55
    comment_text_color: 0x1010d0
    hilited_back_color: 0x000000
    hilited_candidate_back_color: 0x00000000
    hilited_candidate_text_color: 0x70ffaf
    hilited_comment_text_color: 0x1010f0
    hilited_text_color: 0xfecb96
    name: "星際我爭霸／StarCraft"
    text_color: 0xccaa88
show_notifications_via_notification_center: true
show_notifications_when: appropriate
style:
  border_height: 0
  border_width: 0
  color_scheme: dark_temple
  corner_radius: 10
  font_face: "Lucida Grande"
  font_point: 18
  horizontal: true
  inline_preedit: false
  label_font_point: 16
  line_spacing: 1
  spacing: 5
us_keyboard_layout: false
```
