### ISSUE TITLE
Where can I find the documentation on the key "speller/initials"?

### ISSUE THREAD

**Issue by rodrigo-morales-1** [rime/home#1607]
I'm not a Chinese native speaker, but I'm learning Chinese and I like using RIME.

I want to create my own custom schema, so I'm looking at some schemas that the community have created so that I can better understand how RIME schemas are created.

I have noticed that many schemas define the key `initials`. In `bopomofo.schema.yaml`,`initials` is set as shown below [(link)](https://github.com/rime/rime-bopomofo/blob/c7618f4f5728e1634417e9d02ea50d82b71956ab/bopomofo.schema.yaml#L67):

```
(...omitted lines...)
speller:
  alphabet: '1qaz2wsxedcrfv5tgbyhnujm8ik,9ol.0p;/- 6347'
  initials: '1qaz2wsxedcrfv5tgbyhnujm8ik,9ol.0p;/-'
  finals: " 6347"
  delimiter: "'"
(...omitted lines...)
```

In `double_pinyin_mspy.schema.yaml` , `initials` is set as shown below [(link)](https://github.com/rime/rime-double-pinyin/blob/69bf85d4dfe8bac139c36abbd68d530b8b6622ea/double_pinyin_mspy.schema.yaml#L52):

```
(...omitted lines...)
speller:
  alphabet: zyxwvutsrqponmlkjihgfedcba;
  initials: zyxwvutsrqponmlkjihgfedcba
  delimiter: " '"
  algebra:
(...omitted lines...)
```

So, my question is: Where can I find the documentation on the key "initials"?

I know of the existence of https://github.com/rime/home/wiki/RimeWithSchemata , but that page doesn't contain documentation on the key `initials`.
