### ISSUE TITLE
script_translator正则上屏

### ISSUE THREAD

**Issue by yueduz** [rime/home#164]
```
speller:
  alphabet: "qwertasdfgzxcvbyuiophjklnm "
  initials: "qwrtsdfgzxcvbyphjklnm"
  delimiter: "'"
  # finals: " eiuoa"
  uvleader: "[eiuoa ] $"
  fourkey: "[eiuoa ] $"
  punckey: "[eiuoa ] $"
  use_space: true
  algebra:
    - 'xlit|;| |'
    - "fuzz/^(\\w)(\\w).+$/$1$2/"
    - "fuzz/^(\\w)(\\w)(\\w).+$/$1$2$3/"
    - "fuzz/^(\\w)(\\w)(\\w)(\\w).+$/$1$2$3$4/"
    - "fuzz/^(\\w)(\\w)(\\w)(\\w)(\\w).+$/$1$2$3$4$5/"
```
我在这里使用  uvleader  fourkey  punckey都没有办法上屏。
码表：
```
...
而	v;
我	w;
下	x;
一	y;
在	z;
吖	vkou
啊	vk
锕	vja
...
```
码表没有一简字，一简字后面都加了分号，我又使用- 'xlit|;| |'将分号转成空格，所以我既要空格作为编码又要空格用来上屏。存在的编码只有三种情况，
```
/^[qwrtsdfgzxcvbyphjklnm] $/
/^[qwrtsdfgzxcvbyphjklnm][eiuoa]$/
/^[qwrtsdfgzxcvbyphjklnm][qwrtsdfgzxcvbyphjklnm][eiuoa]*$/
```
第一种情况就按两次空格上屏，且空格作为编码只会在这种情况下出现。不知道表达清楚没有。请问能不能实现？
------------------------
补充 ：
我使用 finals: " eiuoa"的话，第一种和第二种情况都能实现，第三种末尾[eiuoa]多次出现或不出现就搞不定了。
