### ISSUE TITLE
想請指教dict.yaml問題

### ISSUE THREAD

**Issue by sheaahhoi1** [rime/home#1666]
dict.yaml
以下文件,為何無法正常讀取任何內容?
受上傳限制添加.TXT結尾
[quick35+6.ext2recode.dict.yaml.txt](https://github.com/user-attachments/files/17088198/quick35%2B6.ext2recode.dict.yaml.txt)
是字庫量太長?但把我3個字碼庫放到最上也不能使用
字庫檔案不存在影響?
目錄名字問題?
但我直接改別人寫好的也無法進行正常取碼

輸入方案中translator部份
schema.yaml
```
translator:
  dictionary: quick35+6.ext2recode
  prism: quick35+6.ext2recode
  enable_charset_filter: true           # 开启字符集过滤,限制生辟字
  enable_completion: true               # 是否显示编码未输入完整的词条
  enable_sentence: true                # 句子输入模式
  enable_user_dict: true               # 是否开启用户词典（用户词典记录动态字词频，用户词）
  enable_encoder: true               # 是否开启自动造词
  encode_commit_history: true          # 是否对已上屏词自动成词（仅 table_translator 有效）
  max_phrase_length: 25          # 最大自动成词词长【number】
  enable_completion: true          # 提前显示尚未输入完整码的字【true 或 false】
  sentence_over_completion: true         # 在无全码对应字而仅有逐键提示时也开启智能组句【true 或 false】
  preedit_format:
    - "xlit|abcdefghijklmnopqrstuvwxyz;'|日月金木水火土竹戈十大中一弓人心手口尸廿山女田難卜符··|"
  comment_format:
    - "xlit|abcdefghijklmnopqrstuvwxyz~|日月金木水火土竹戈十大中一弓人心手口尸廿山女田難卜符～|"
  #disable_user_dict_for_patterns:
  #  - "^z.*$"
  #  - "^yyy.*$"
  initial_quality: 1.2
```

但在小型的dict.yaml引用同時引用3個字碼庫是正常
```
import_tables:
  #字碼庫是正常
  - quick3_8m6_2022          #  3代詞庫
  - quick5_2022      # 5代詞庫
  - cangjie6           # 6代詞庫
```
