### ISSUE TITLE
如何去掉使用反查找不到匹配时出现的前导键

### ISSUE THREAD

**Issue by vincentaxhe** [rime/home#1691]
```
  translators:
    - punct_translator
    - table_translator
    - reverse_lookup_translator
    - reverse_lookup_translator@pinyin_lookup
    - reverse_lookup_translator@english
    - reverse_lookup_translator@emoji

reverse_lookup:
  extra_tags:
    - pinyin_lookup
    - english
    - emoji

pinyin_lookup:
  tag: pinyin_lookup
  dictionary: pinyin
  prefix: "i"
  tips: "〔拼〕"
  preedit_format:
    - xform/^i//
    - xform/([nl])v/$1ü/
    - xform/([nl])ue/$1üe/
    - xform/([jqxy])v/$1u/

english:
  tag: english
  dictionary: easy_en
  prefix: "u"
  tips: "〔En〕"
  enable_completion: true
  preedit_format:
    - xform/^u//

emoji:
  tag: emoji
  dictionary: emoji
  prefix: ";"
  tips: "〔emoji〕"
  enable_completion: true
  preedit_format:
    - xform/^;//

```
我给自己用的音形码输入法用不到的ui键作为拼音反查和英文输入切换键，当先打u使用英文时，如果没找到单词，用return上屏会把u包含进去，怎么样能不包含u，当进入u英文输入时，无论输入什么，找到就用空格上屏，找不到就用return上屏，都不会包含第一个u。
