### ISSUE TITLE
1.11.2 版本输入法方案 custom 文件无法生效

### ISSUE THREAD

**Issue by LittleYe233** [rime/home#1695]
在 Arch Linux 中已经安装 librime 1.11.2 和 fcitx5，使用的输入方案是[四叶草](https://github.com/fkxxyz/rime-cloverpinyin?tab=readme-ov-file)，在 `~/.local/share/fcitx5/rime/clover.custom.yaml` 中写入：

```yaml
patch:
  "style/font_point": 14
  "style/color_scheme": trans
  "style/color_scheme_dark": trans
  "preset_color_schemes/trans":
    name: trans
    text_color: 0x000000
    back_color: 0xffffff
    border_color: 0xface5b
    hilited_candidate_text_color: 0xffffff
    hilited_candidate_back_color: 0xb9aaf5
```

以上配置均无法生效。恳请赐教。
