### ISSUE TITLE
如何解决.(点号)作地球拼音声调的候选上屏问题？

### ISSUE THREAD

**Issue by zgdlime** [rime/home#17]
用;,./四个符号代表地球拼音1234声(- 'xlit 1234 ;,./')，3个符号正常;
其中.(点号)代表声调，首选用空格可上屏，非首选用数字不能选择上屏，
不知如何解决候选词选择上屏问题？

**Comment by zgdlime** [comment]
我真是太聪明了，搞掂了喔
地球拼音是地球上的人用的拼音哦

**Comment by jakwings** [comment]
能说一下怎么解决的吗……我对此有兴趣。囧

**Comment by lotem** [comment]
我猜是受翻頁功能影響了。
取消 `, .` 的翻頁功能就可以了吧。

**Comment by jakwings** [comment]
@lotem 和那沒直接關係。原來是被 `recognizer` 干擾了，打個補丁搞定：

``` yaml
patch:
  recognizer:
    patterns:
      uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
```

話說，打補丁時直接忽略空値，有沒有好的方法取消掉默認認値呢？
