### ISSUE TITLE
配置自定义快捷键切换中英文标点不生效

### ISSUE THREAD

**Issue by SaarChaffee** [rime/home#1704]
default.custom.yaml 如下：
```yml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.16.3
  generator: "Rime::SwitcherSettings"
  modified_time: "Wed Nov 13 23:37:53 2024"
  rime_version: 1.11.2
patch:
  "menu/page_size": 5
  "schema_list":
    - {schema: luna_pinyin}
    - {schema: luna_pinyin_fluency}
    - {schema: jyut6ping3}
    - {schema: luna_pinyin_simp}
  "switcher/hotkeys":
    - "Control+Shift+F"
  "key_binder/bindings/+":
    __append:
    - { when: always, accept: Control+comma, toggle: ascii_punct }
    - { when: always, accept: Control+period, toggle: ascii_punct }
    - { when: always, accept: Control+Shift+period, toggle: ascii_punct }
```

配置了切换中英文标点的数个快捷键，只有 ctrl + . 的能生效，另外两个没反应的。因为 ctrl + . 有时候别的地方会用到所以希望换一下不用 key_bindings.yaml 中的 windows_compatible_mode_switch。
