### ISSUE TITLE
能不能指定simplifier只对特定translator生效

### ISSUE THREAD

**Issue by oheheda** [rime/home#1709]
我想实现同一个方案中混输拼音和日文，所以定义了两个翻译器，方案部分配置如下
```yaml
engine:
  filters:
    - simplifier
    - "simplifier@emoji_suggestion"
    - "reverse_lookup_filter@japanese_revers_lookup"
    - uniquifier
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - script_translator
    - "script_translator@japanese"
translator:
  dictionary: luna_pinyin
  prism: pinyin_japanese
  enable_user_dict: true

japanese: 
  comment_format:
    - "xlit|q|ー|"
  dictionary: japanese
  enable_user_dict: true
  enable_sentence: true 
  enable_completion: true
  preedit_format:
    - "xlit|q|ー|"
  spelling_hints: 1
```
现在simplifier会对两个翻译器的结果都进行简化，导致部分日文单词的汉字变成了简体的，但是同时我又希望保留使用拼音打中文时的简繁转换功能，请问如何配置才能够令simplifier只对某个翻译器的结果进行转换或者排除某个翻译器呢，我已经翻遍了wiki中的每一页，但是没有发现如何进行相关的配置

**Comment by ksqsf** [comment]
不能实现

**Comment by lotem** [comment]
可以設置 `tag`

**Comment by oheheda** [comment]
我现在了解到translator/tag是用于指定该translator生效的tag，但没有发现如何才能令translator的结果附加特定的tag供simplifier去区分来自哪个translator。

**Comment by ksqsf** [comment]
混输的情况确实无法实现吧（tag都是"abc"）。如果是带标记的，或者如果支持给candidate打上标记，就可以区分了。translator的tag也是用来筛选segment的，不会增加tag。

如果愿意接受额外输入标记：

```
engine:
  translators:
    - script_translator@japanese
  filters:
    - simplifier@simplifer # librime bug

japanese:
  tag: japanese

simplifier:
  tags: [abc]

recognizer:
  patterns:
    japanese: '^/r[a-z]*'
```
