### ISSUE TITLE
改成用數字選字的正確方法是什麼

### ISSUE THREAD

**Issue by fmnijk** [rime/home#1745]
我把default.custom.yaml改成這樣，只有page_size有效果。
```
patch:
  menu:
    page_size: 10
    alternative_select_keys: 1234567890
```
  
有人說要到build裡面的XXX.schema.yaml把`alternative_select_keys: ABCDEFGHIJ`刪掉，我總感覺這樣涉及對預設的修改。

順便問下如何用Numpad的Enter選字
我是想設定成鍵盤左右邊的兩種數字鍵和兩種Enter鍵(搭配方向鍵)都能用來選字
謝謝
