### ISSUE TITLE
想要；‘和设置成 第二候选项和第三候项要怎么做

### ISSUE THREAD

**Issue by aizigao** [rime/home#178]
我试过这样设置
```yaml
  # 绑定；’ 为第二选则和第三选则
    - {when: has_menu, accept: semicolon, send: 2}
```
但是没有用，貌似操作姿势不对，求解答

**Comment by aizigao** [comment]
yaml 缩进问题， 打扰了

```
# default.custom.yaml

patch:
  schema_list:
    - schema: xinshijiwubi
    - schema: luna_pinyin_simp

  menu:
    page_size: 5

  key_binder:
    bindings:
      - { when: has_menu, accept: semicolon, send: 2 }
      - { when: has_menu, accept: apostrophe, send: 3 }

  ascii_composer:
    good_old_caps_lock: true
    switch_key:
      Shift_L: noop
      Shift_R: noop 
      Eisu_toggle: clear
```
