### ISSUE TITLE
我找不到正确的输入法方法.

### ISSUE THREAD

**Issue by rigba** [rime/home#1794]
对不起， 我说一点儿中文。我会说英文。

Hello,

I'm writing this because I'm having some difficulty navigating the documentation to find what I'm looking for as I'm not very fluent in Chinese.

I am self-learning 中文 and having difficulty remembering tones. I want to practice remembering the tones but the default Microsoft Pinyin IME lets you be lazy by not having to make the user manually type out the tones. 

So to summarise, I am looking for a "拼音输入方案“ that forces the user to manually type out the tones. In practice this would look like:

Intended Output: `我每天都喝咖啡`
Desired input `wo3mei2tian1dou1he1ka1fei1` -> enter
MS拼音： `womeitianduohekafei` -> enter

I have tried: https://github.com/rime/rime-terra-pinyin but its not what I'm looking for as the input methods are clunky having to use `- / < \`. It's also in traditional Chinese although I'm sure I could figure out a way to fix that.

pls help :(((( my apologies 

AI 翻译:

你好，

我写这封信是因为在浏览 GitHub 仓库的文档时遇到了一些困难，由于我的中文不太流利，所以没法找到我需要的信息。

我是自学中文，而在记忆声调方面遇到困难。我想练习记声调，但默认的微软拼音输入法让用户可以快速输入声调，这使得我没有强制要求自己去记。

总结来说，我在寻找一种“拼音输入方案”，可以强制用户手动输入声调。实际上，这样的输入应该是：

预期输出：我每天都喝咖啡 期望输入：wo3mei2tian1dou1he1ka1fei1 -> 单击输入 MS拼音：womeitianduohekafei -> 单击输入

我尝试过：https://github.com/rime/rime-terra-pinyin，但它不是我需要的，因为它的输入方式有些繁琐，需要使用 - / < \。另外，它是繁体中文，虽然我可以想办法解决这个问题。

请帮忙:((((

**Comment by LEOYoon-Tsaw** [comment]
Terra pinyin 地球拼音 or Zhuyin 注音, which ship with rime suit you. 

The former is based on pinyin, and uses - / < \ as tone 1-4. The latter is used in Taiwan and is a different system of phonetic input which also requires tone.

**Comment by lotem** [comment]
改配置
``` yaml
# terra_pinyin.custom.yaml
# 聲調寫 12345
# 選詞用空格或 67890
patch:
  menu/alternative_select_keys: 67890
  recognizer:
  speller/alphabet: 'zyxwvutsrqponmlkjihgfedcba12345'
  speller/initials: zyxwvutsrqponmlkjihgfedcba
  speller/finals: 12345
  speller/algebra:
 ```
