### ISSUE TITLE
在哪里设置候选词个数？

### ISSUE THREAD

**Issue by hwypengsir** [rime/home#1825]
我设置了候选词20个，发现无法使用。

进入设置文件夹
```
cd  ~/.config/ibus/rime
ls 
build			     luna_pinyin.extended.dict.yaml
default.custom.yaml	     luna_pinyin_simp.custom.yaml
installation.yaml	     luna_pinyin_simp.yaml
luna_pinyin.41448.dict.yaml  luna_pinyin.userdb
luna_pinyin.8105.dict.yaml   user.yaml
luna_pinyin.base.dict.yaml
```
设置参数
```
vim  luna_pinyin_simp.custom.yaml
patch:
  #设定简化字为默认选项
  switches:
    - name: ascii_mode
      reset: 0
      states: [ 中文, 西文 ]
    - name: full_shape
      states: [ 半角, 全角 ]
    - name: zh_simp           # 注意這裏（※1）
      reset: 1
      states: [ 漢字, 汉字 ]

  menu/page_size: 20 # 候选词个数

  "translator/dictionary": luna_pinyin.extended
```
重新启动
`ibus-daemon -xdr`
别说显示20个字，选字的菜单根本就不出现了，重新启动电脑后，还是这样。
menu/page_size: 10
这下正常了，也就是仅仅显示10个。
我找的文件不对吗？
