### ISSUE TITLE
enable_word_completion: false 未能解决"候选词补全问题

### ISSUE THREAD

**Issue by ajtcmkg** [rime/home#1829]
问题承接自DIscussions发布的帖子: [截图与复现](https://github.com/rime/home/discussions/1813)
根据开发者的描述,在全新系统中安装小狼毫依旧无法成功
```yaml
# <方案>.custom.yaml
patch:
  translator/enable_word_completion: false
```
候选词补全无法取消, 而且可能因为这是新加入的功能, 在[帮助文档](https://rime.im/docs/)无法搜索到该功能
在Issues重复上报问题很抱歉,但Discussions的帖子始终未有回复
十分感谢

**Comment by fxliang** [comment]
要nightly 才有新的librime，或者自行更新复制rime.dll

**Comment by ajtcmkg** [comment]
感谢两位的帮助,希望未来的小狼毫可以开箱即用
根据上面的回复,以下在Windows手动关闭 **候选词补全**
1.右击任务栏小狼毫图标,选择程序文件夹
2.替换 rime.dll .[进入librime下载](https://github.com/rime/librime/releases),个人选择 Windows-clang-x64,解压得到rime.dll [更详细的操作参考](https://www.mintimate.cc/zh/guide/faQ.html)
3.由于需要修改"程序文件夹"中的文件,必须先结束rime的进程,否则无法修改文件.然后替换程序文件夹的rime.dll
4.按照以下在用户文件夹根据所用方案进行操作, 比如默认的 朙月拼音 luna_pinyin.custom.yaml
```yaml
# <方案>.custom.yaml
patch:
  translator/enable_word_completion: false
```
5.重新部署
