### ISSUE TITLE
是否有办法在patch中删除列表项?

### ISSUE THREAD

**Issue by 424778940z** [rime/home#1836]
如题, 看文档有说如何追加新项目到列表, 但没有说如何在patch里删除已有项目

如下面例子, 想在patch中删掉注释掉的两行, 不清楚如何操作, 或者是否可能

目前比较不便的是每次更新或者拉取git最新的预制配置, 会覆盖本地手动修改的版本, 而放在.custom.yaml的patch中则不会有这种问题

```yaml
# 输入引擎
engine:
  translators:
    - punct_translator
    # - table_translator@melt_eng         # 英文输入
    # - table_translator@cn_en            # 中英混合词汇
    - table_translator@radical_lookup   # 部件拆字反查
```
