### ISSUE TITLE
求解答,如何设置候选词 竖着,stacked,从左到右显示

### ISSUE THREAD

**Issue by Shawn-Summer** [rime/home#1844]
我使用的主题配置为:

```yaml
      candidate_list_layout: stacked
      text_orientation: vertical
      inline_preedit: true
```
然后我发现他显示为:

![Image](https://github.com/user-attachments/assets/8a9fae39-a5d6-4b6a-9f21-b650aa3ac26d)

这些候选词是从右到左排列的,怎么让它从左往右排列?
