### ISSUE TITLE
注音如何輸入全拼/關閉連續輸入

### ISSUE THREAD

**Issue by minstrike520** [rime/home#1846]
如題，請問當前的設定檔是否有辦法讓輸入法限制使用者必須將完整注音輸入，而不是預設的連續輸入、可省略音調或韻母等？
我在[使用說明/關閉逐鍵提示](https://github.com/rime/home/wiki/CustomizationGuide#%E9%97%9C%E9%96%89%E9%80%90%E9%8D%B5%E6%8F%90%E7%A4%BA)中有看到相關的設定，然而依以下方法照做之後，並沒有達成想要的效果。
```yaml
# weasel.custom.yaml
# ...
patch:
  "translator/enable_competion": false
```

**Comment by minstrike520** [comment]
另外，我也在輸入法的設定中嘗試設定相關項目，但是仍然沒有效果：
```yaml
translator:
  dictionary: moetaigi
  # ...
  enable_sentence: false # <--------
  # ...
```
