### ISSUE TITLE
朙月拼音中，如何配置為臺灣正體與大陸簡體切換？

### ISSUE THREAD

**Issue by xuhdev** [rime/home#185]
朙月拼音中，默認似乎更接近香港繁體。如何配置成臺灣正體與大陸簡體切換？

**Comment by hazdzz** [comment]
預設為「臺灣標準正體」，非「香港標準正體」。也許是你選擇的字體是香港標準的。

**Comment by Enig123** [comment]
請問新版如何設定爲「臺灣正體」？

**Comment by dqwyy** [comment]
```yaml
switches:
  - options: [zh_cn, zh_tw]
    states:
      - 大陸簡體
      - 臺灣正體
    reset: 0  #默認輸出大陸簡體，如果要默認輸出臺灣正體，請改0為1
engine/filters:
  - simplifier@zh_tw
  - simplifier@zh_cn
  - uniquifier
zh_tw:
  option_name: zh_tw
  opencc_config: t2tw.json
zh_cn:
  option_name: zh_cn
  opencc_config: t2s.json
```
