### ISSUE TITLE
请问如何让wubi_pinyin输入方案即支持emoji表情又支持拼音输入？

### ISSUE THREAD

**Issue by northleafup** [rime/home#186]
新建了wubi_pinyin.custom.yaml文件，添加了emoji的配置，为何就不能通过拼音输入汉字了呢？
```
patch:
  schema/dependencies:
    - emoji
    - symbols
  reverse_lookup:
    dictionary: emoji
    enable_completion: true
    prefix: "`"
    tips: [emoji]
  punctuator:
    import_preset: symbols
  recognizer:
    import_preset: default
    patterns:
      reverse_lookup: "^z[a-z]*'?$"
      punct: "^/([a-z]+|[0-9]0?)$"

```
请问我该如何修改这个配置文件，使五笔拼音输入法，即能支持表情输入，又能支持拼音输入呢，谢谢！

**Comment by ijse** [comment]
遇到同样问题。

目前看来是跟 `reverse_lookup` 这一配置项有关。

**Comment by northleafup** [comment]
@ijse 目前这个问题已解决，这个配置可以达到以下的效果：
1. 输入拼音就当作是拼音输入法，同时显示出所打汉字的五笔码
2. 可以直接按五笔的方式输入汉字
3. 输入“/” 后接英文字母（如“/jt”)可以输入一些特殊符号，输入“/”后接数字（如“/1”）可以输入数字的大写，比如①
4. 输入“`”， 就是数字1左边的按键，即tab键上方的按钮，可以输入表情，比如“`cry”，是输入哭的表情
5. 以下文件中my_symbols，需要将~/Library/Rime目录下的symbols.yaml文件复制一份（不建议直接更改原始文件），并改名为my_symbols.yaml，将来就可以按需在这个文件中添加所需要的特殊符号了。

以下是我的wubi_pinyin.custom.yaml文件内容，仅供参考：

--------wubi_pinyin.custom.yaml 开始--------
```yaml
patch:
  schema: 
    dependencies:
    - pinyin_simp
    - my_symbols
    - emoji
  switches:
    - name: ascii_mode
      reset: 0
      states: [ 中文, 西文 ]
    - name: full_shape
      states: [ 半角, 全角 ]
    - name: extended_charset
      states: [ 常用, 增廣 ]
    - name: ascii_punct
      states: [ 。，, ．， ]
  
  engine:
    processors:
      - ascii_composer
      - recognizer
      - key_binder
      - speller
      - punctuator
      - selector
      - navigator
      - express_editor
    segmentors:
      - ascii_segmentor
      - matcher
      - affix_segmentor@myemoji
      - abc_segmentor
      - punct_segmentor
      - fallback_segmentor
    translators:
      - punct_translator
      - reverse_lookup_translator
      - table_translator
      - script_translator@myemoji
  
  speller:
    delimiter: " ;'"
    #max_code_length: 4  # 四碼頂字上屏
  
  translator:
    dictionary: wubi86
    prism: wubi_pinyin
    enable_charset_filter: true
    enable_sentence: true
    enable_encoder: true
    encode_commit_history: true
    max_phrase_length: 4
    disable_user_dict_for_patterns:
      - "^z.*$"
  
  abc_segmentor:
    extra_tags:
      - reverse_lookup
  myemoji:
    # script_translator@emoji
    dictionary: emoji
    preedit_format:
      - "xform/^([a-z]*)$/【Emoji】$1/"
    # affix_segmentor@myemoji
    tag: myemoji
    prefix: '`'
    tips: 〔Emoji〕
    closing_tips: 〔Emoji〕 
  reverse_lookup:
    dictionary: pinyin_simp
    prefix: "`"
    suffix: "'"
    tips: 〔拼音〕
    preedit_format:
      - xform/([nl])v/$1ü/
      - xform/([nl])ue/$1üe/
      - xform/([jqxy])v/$1u/
  
  punctuator:
    import_preset: my_symbols
  
  key_binder:
    import_preset: default
  
  recognizer:
    import_preset: default
    patterns:
      myemoji: "`[a-z']*;?$"
      punct: "^/[0-9]?[a-z]*$"
      reverse_lookup: "`[a-z]*'?$"

```
--------wubi_pinyin.custom.yaml 结束--------
