### ISSUE TITLE
[求助]Mac + Karabiner Element：重定义选字键出错 key_binder+punctuator无法处理选字 会先输入中文标点

### ISSUE THREAD

**Issue by WesleyBlancoYuan** [rime/home#1890]
> Hi, 以上设置在Mac里面又出现了问题。Karabiner存在的情况下，出现上屏的按键如果对应了中文标点，则会再次出现符号和第一个候选字上屏的问题。
> 
> 比如输入"dashi"，数字键１，２，５可以正常选字，但是按３会输入“大师（”，按４会输入“大师《“。我理解这两字应该先用punctuator处理，然后用selector，但以下设置不起作用：
> 
> ```yaml
> # default.custom.yaml
> customization:
>   distribution_code_name: Weasel
>   distribution_version: 0.9.30
>   generator: "Rime::SwitcherSettings"
>   modified_time: "Tue Oct 17 09:30:32 2017"
>   rime_version: 1.1.2
> patch:
>   engine:
>     processors:
>       - punctuator
>       - key_binder
>       - selector
>     segmentors:
>       - abc_segmentor
>       - punct_segmentor   # 劃界，與前後方的其他編碼區分開
>       - fallback_segmentor
>     translators:
>       - echo_translator
>       - punct_translator  # 轉換
>       - table_translator
>   schema_list:
>     - {schema: luna_pinyin}
>   punctuator:
>     import_preset: default #導入預設
>     full_shape:
>       "(" : "("
>       "<" : "<"
> 
>   ascii_composer/switch_key:
>     # commit_code: commit the letters
>     # commit_text: commit the characters
>     # clear: does not commit
>     # noop: disable
> 
>     # Enable Shift switching language
>      # Shift_L: commit_code
>      # Shift_R: commit_code
>     # Disable Shift switching language
>      Shift_L: noop
>      Shift_R: noop
> 
> ```
> 
> ```yaml
> # luna_pinyin.custom.yaml
> # Luna custom
> # encoding: utf-8
> patch:
>   switches:
>     - name: full_shape
>       reset: 1
>       states: ["半角", "全角"]
>     - name: simplification
>       reset: 1
>       states: ["漢字", "汉字"]
>     - name: ascii_punct
>       reset: 0
>       states: ["句讀", "符號"]
>   # "menu/alternative_select_keys":
>   #   '{[(</\>)]}'    # not working
> 
>   # first launch type English
>   "switches/@0/reset": 0 #表示將 switcher 列表中的第一個元素（即 ascii_mode 開關）的初始值重設爲狀態1（即「英文」）。
> 
>   "key_binder/bindings":
>     # Change language with Ctrl+|
>     - {accept: "Control+bar", toggle: ascii_mode, when: always}
>     # pageup/pagedown to choose characters with ,/.
>     - {when: has_menu, accept: period, send: Page_Down}
>     - {when: has_menu, accept: comma, send: Page_Up}
>     # For SymmeTri
>     - {accept: braceleft, send: 1, when: has_menu}      # 大括号選1
>     - {accept: bracketleft, send: 2, when: has_menu}    # 中括号選2
>     - {accept: parenleft, send: 3, when: has_menu}      # 括号選3
>     - {accept: less, send: 4, when: has_menu}           # 小括号選4
>     - {accept: slash, send: 5, when: has_menu}          # 斜杠选5
>     - {accept: backslash, send: 6, when: has_menu}      # 反斜杠选6
>     - {accept: greater, send: 7, when: has_menu}        # 右小括号选7
>     - {accept: parenright, send: 8, when: has_menu}     # 右括号选8
>     - {accept: bracketright, send: 9, when: has_menu}   # 右中括号选9
>     - {accept: braceright, send: 0, when: has_menu}     # 右大括号选0
> ```
> 
> 我已经用Key Codes.app和Karabiner-EventViewer.app查看了按键event，两个程序都显示系统收到了`(`半角字符。
> 
> ![Image](https://github.com/user-attachments/assets/962ad71f-0a61-4559-bd00-09f20ecd4a2c)
> 
> 请指教一下，万分感谢 

 _Originally posted by @WesleyBlancoYuan in [#191](https://github.com/rime/home/issues/191#issuecomment-2865598646)_

**Comment by WesleyBlancoYuan** [comment]
我找到解决方法了：
首先：`selector` 要放在`key_binder`之前：

```
% cat ~/Library/Rime/default.custom.yaml
patch:
  schema_list:
    - {schema: luna_pinyin}
  # engine只能放在這個文件 不能放在luna拼音文件
  engine:
    processors:
      - key_binder # 在其他processor之前判斷 是否是換頁用的符號
      - selector   # 先选字
      - punctuator # 然后處理標點
  punctuator:
    import_preset: default #導入預設
    full_shape:
      "{": "{"
      "(": "("
      "<": "<"
    half_shape:
      "{": "{"
      "(": "("
      "<": "<"
```
其次：应该用Shift+某些键来放在accept部分，因为Mac是没有virtual key的，无论是Karabiner还是其他的系统内置工具，都是用实际的key code+modifier来映射，没有中间层。
**这里必须要建议一下：源代码里接受的是`Shift`这样的modifier，而不是https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md 里面写的 `Shift_L/R`. 这一点是文档没有写明的。在Copilot的帮助下我才找到正确的modifier名字：**

> Here's how I find it:
> 1. librime source code — key_event.cc
> 
> The modifier parser in librime only recognizes these modifier names: Shift, Control, Alt, Super, Release. When it encounters Shift_L, it logs:
>     
>     parse error: unrecognized modifier 'Shift_L'
>.   
> Shift_L and Shift_R are key names (physical keys), not modifier names (abstract flags). The distinction:
> 
> - Shift = modifier flag applied to a key combo (e.g., "Shift+braceleft")
> - Shift_L / Shift_R = the actual left/right Shift keys themselves (used in ascii_composer/switch_key)
> 
> 2. Your own Squirrel logs confirmed it
> 
> The WARNING log at $TMPDIR/rime.squirrel/ had repeated entries from your earlier test:
>    
>     E20260415 11:44:18 key_event.cc:69] parse error: unrecognized modifier 'Shift_L'
>     W20260415 11:44:18 key_binder.cc:181] invalid key binding #31, with invalid accept pattern: Shift_L+bracketleft.
> 
> 3. Rime documentation (Rime_description.md) lists the modifier vocabulary but it's easy to miss the distinction from key names used elsewhere in the config.

我建议在文档里面写明。

所以，最后的luna pinyin的设置应该如下（仅限Mac+Karabiner Element启用时；Windows用原帖 [#191](https://github.com/rime/home/issues/191) 的无shift版本）：

```
% cat ~/Library/Rime/luna_pinyin.custom.yaml
# Luna custom
patch:
  switches:
    - name: full_shape
      reset: 1
      states: ["半角", "全角"]
    - name: simplification
      reset: 1
      states: ["漢字", "汉字"]
    - name: ascii_punct
      reset: 0
      states: ["句讀", "符號"]

  "menu/page_size": 10


  # first launch type English
  "switches/@0/reset": 0 #表示將 switcher 列表中的第一個元素（即 ascii_mode 開關）的初始值重設爲狀態1（即「英文」）。

  "key_binder/bindings":
    # Change language with Ctrl+|
    - {accept: "Control+bar", toggle: ascii_mode, when: always}
    # pageup/pagedown to choose characters with ,/.
    - {when: has_menu, accept: period, send: Page_Down}
    - {when: has_menu, accept: comma, send: Page_Up}
    # For SymmeTri
    - {accept: Shift+braceleft, send: 1, when: has_menu}      # 大括号選1
    - {accept: bracketleft, send: 2, when: has_menu}    # 中括号選2
    - {accept: Shift+parenleft, send: 3, when: has_menu}      # 括号選3
    - {accept: Shift+less, send: 4, when: has_menu}           # 小括号選4
    - {accept: slash, send: 5, when: has_menu}          # 斜杠选5
    - {accept: backslash, send: 6, when: has_menu}      # 反斜杠选6
    - {accept: Shift+greater, send: 7, when: has_menu}        # 右小括号选7
    - {accept: parenright, send: 8, when: has_menu}     # 右括号选8
    - {accept: bracketright, send: 9, when: has_menu}   # 右中括号选9
    - {accept: Shift+braceright, send: 0, when: has_menu}     # 右大括号选0

  # menu:
  #  alternative_select_keys: '{[(</\>)]}' #如編碼字符佔用數字鍵則須另設選字鍵；not working

  ascii_composer/switch_key:
    # commit_code: commit the letters
    # commit_text: commit the characters
    # clear: does not commit
    # noop: disable

    # Enable Shift switching language
     # Shift_L: commit_code
     # Shift_R: commit_code
    # Disable Shift switching language
     Shift_L: noop
     Shift_R: noop
```
