### ISSUE TITLE
dict.yaml 为什么要分成两个部分? 明明用yaml就可以

### ISSUE THREAD

**Issue by alkene0005** [rime/home#1891]
不论如何, 至少应该增加如下的配置方式 `custom.dict.yaml`
```yaml
name: custom
version: '2023-10-02'
sort: by_weight 
entries:
  - ['t恤', 'ti xu', 999]
  - ['b站', 'bi zhan', 666]
```

为什么一定要这样 🤔?

答: yaml文件规范是空格为缩进, 而tsv部分以\t为缩进, 导致各种编辑器编辑很恶心

另外: 即便纯用yaml有一些其他缺点, 但为什么不增加支持这种方式呢, 这种纯yaml很适合个人临时增加一些词
