### ISSUE TITLE
每页候选词超过10个时，如何选取编号过10的那些候选词？

### ISSUE THREAD

**Issue by moonroper** [rime/home#1892]
下面这个配置每页12个候选词，
```
customization:
  distribution_code_name: Weasel
  distribution_version: 0.16.3
  generator: "Rime::SwitcherSettings"
  modified_time: "Sat May 10 20:23:12 2025"
  rime_version: 1.13.1
patch:
  menu:
    alternative_select_keys: "1234567890{}"
    page_size: 12
  schema_list:
    - {schema: luna_pinyin_fluency}``
```

![Image](https://github.com/user-attachments/assets/a327f9e7-90b0-4629-a65d-ce6965e36d20)
UI提示当页最后两字选词符号为左右括号，
![Image](https://github.com/user-attachments/assets/4da5e585-8959-40b9-918c-b7889061ee63)
但输入左括号后，没有直接上屏“月”，而是提示几种括号的可选变体。
有没有办法配置左括号后为直接上屏“月”字？
