### ISSUE TITLE
按照VK code选字 而且不输入额外符号

### ISSUE THREAD

**Issue by WesleyBlancoYuan** [rime/home#191]
我改变了键盘布局，让上排数字键默认（no shift）状态输入符号，按shift输入数字。而且我修改了键盘布局的virtual key code (vk code)，使得vk_n和数字相符。并且，我修改了注册表，让小狼毫使用我的键盘布局dll。

在字母和翻页部分，小狼毫表现完美，和Windows 10的微软拼音输入法中一样，我的键盘方案可以正常使用。

但是在数字键选字部分，小狼毫不如windows 10微软拼音：必须用shift+上排键才能选择，也就是说，选字时不检测VK code，而是检测scan code。但Win 10微软拼音输入法正常。（Win 7微软拼音输入法也出错）

比如，我的123三个键分别是`{`/`1`, `[`/`2`, `(`/`3`。假如我输入“dashi”，要选第三个词“大使”，直接按`(`/`3`会出现`大师（`，迫使我用Shift+3来选字，这不科学。

windows程序的热键应该检测vk Code，至少文档里面提到了这点：

[Legacy User Interaction Features > Keyboard and Mouse Input > Keyboard Input > About Keyboard Input](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646267(v=vs.85).aspx#_win32_Hot_Key_Support)

Scan Code
The scan code is the value that the keyboard hardware generates when the user presses a key. It is a device-dependent value that identifies the key pressed, as opposed to the character represented by the key. An application typically ignores scan codes. Instead, it uses the device-independent virtual-key codes to interpret keystroke messages.

希望修复！除了这点都完美：翻页也是检测vk code的。

**Comment by WesleyBlancoYuan** [comment]
谢谢。我现在创建了`default.custom.yaml`文件，写入以下内容：


```
patch:
  "menu/alternative_select_keys":
    {[(</\>)]}


  "key_binder/bindings":
    import_preset: default
    # For SymmeTri
    - {accept: braceleft, send: 1, when: has_menu}      # 大括号選1
    - {accept: bracketleft, send: 2, when: has_menu}    # 中括号選2
    - {accept: parenleft, send: 3, when: has_menu}      # 括号選3
    - {accept: less, send: 4, when: has_menu}           # 小括号選4
    - {accept: slash, send: 5, when: has_menu}          # 斜杠选5
    - {accept: backslash, send: 6, when: has_menu}      # 反斜杠选6
    - {accept: greater, send: 7, when: has_menu}        # 右小括号选7
    - {accept: parenright, send: 8, when: has_menu}     # 右括号选8
    - {accept: bracketright, send: 9, when: has_menu}   # 右中括号选9
    - {accept: braceright, send: 0, when: has_menu}     # 右大括号选0
```
重新部署后并没有用。这大概会是因为什么？

**Comment by lotem** [comment]
1. `'{[(</\>)]}'` YAML 中有語法意義的字符須放入引號
2. 對 `menu/alternative_select_keys` 的修改只對輸入方案有效，需要在 `<方案ID>.custom.yaml` 打補丁
3.  `import_preset: default` 不能出現在列表中：語法錯誤
4. 通過 `menu/alternative_select_keys` 修改選字按鍵後，數字將不再用作選字，再通過 `key_binder` 改鍵則本已用於選字的符號將會改爲輸出數字

**Comment by WesleyBlancoYuan** [comment]
谢谢！社区支持真热情……喜欢这个社区。我发现的确是修改`luna_pinyin.custom.yaml`就行。
我大概发现问题了：我已经在选单中看到了选字的符号变成了英文的`{[(</`，但是由于是中文状态，这几个键输出的是中文符号，也就是`｛［（〈 /`，而不是英文的对应符号，所以无法选字。假如我把`alternative_select_keys`换成`｛［（〈／＼〉）］｝`则出现选单乱码，比如：

![jjjj](https://user-images.githubusercontent.com/12695200/31652507-a5dd0a70-b31f-11e7-8340-f8b1a080c92e.png)


有办法在保留中文标点的情况下解决这个问题吗？我也不太愿意把中文状态的标点都换成英文的，不过实在不行也得换。

**Comment by WesleyBlancoYuan** [comment]
我搞定了……还是使用`key_binder/bindings`，写在`luna_pinyin.custom.yaml`里面，不用`alternative_select_keys`. 现在一切正常了。谢谢！

看来`braceleft`这些在rime里面相当于虚拟键。

```
# Luna custom
# encoding: utf-8


patch:
  # "menu/alternative_select_keys":
  #   '{[(</\>)]}'

  "switches/@0/reset": 1  #表示將 switcher 列表中的第一個元素（即 ascii_mode 開關）的初始值重設爲狀態1（即「英文」）。

  "key_binder/bindings":
    # For SymmeTri
    - {accept: braceleft, send: 1, when: has_menu}      # 大括号選1
    - {accept: bracketleft, send: 2, when: has_menu}    # 中括号選2
    - {accept: parenleft, send: 3, when: has_menu}      # 括号選3
    - {accept: less, send: 4, when: has_menu}           # 小括号選4
    - {accept: slash, send: 5, when: has_menu}          # 斜杠选5
    - {accept: backslash, send: 6, when: has_menu}      # 反斜杠选6
    - {accept: greater, send: 7, when: has_menu}        # 右小括号选7
    - {accept: parenright, send: 8, when: has_menu}     # 右括号选8
    - {accept: bracketright, send: 9, when: has_menu}   # 右中括号选9
    - {accept: braceright, send: 0, 
```when: has_menu}     # 右大括号选0

**Comment by WesleyBlancoYuan** [comment]
Hi, 以上设置在Mac里面又出现了问题。Karabiner存在的情况下，出现上屏的按键如果对应了中文标点，则会再次出现符号和第一个候选字上屏的问题。
比如输入"dashi"，数字键１，２，５可以正常选字，但是按３会输入“大师（”，按４会输入“大师《“。我理解这两字应该先用punctuator处理，然后用selector，但以下设置不起作用：

```yaml
# default.custom.yaml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.9.30
  generator: "Rime::SwitcherSettings"
  modified_time: "Tue Oct 17 09:30:32 2017"
  rime_version: 1.1.2
patch:
  engine:
    processors:
      - punctuator
      - key_binder
      - selector
    segmentors:
      - abc_segmentor
      - punct_segmentor   # 劃界，與前後方的其他編碼區分開
      - fallback_segmentor
    translators:
      - echo_translator
      - punct_translator  # 轉換
      - table_translator
  schema_list:
    - {schema: luna_pinyin}
  punctuator:
    import_preset: default #導入預設
    full_shape:
      "(" : "("
      "<" : "<"

  ascii_composer/switch_key:
    # commit_code: commit the letters
    # commit_text: commit the characters
    # clear: does not commit
    # noop: disable

    # Enable Shift switching language
     # Shift_L: commit_code
     # Shift_R: commit_code
    # Disable Shift switching language
     Shift_L: noop
     Shift_R: noop

```

```
# luna_pinyin.custom.yaml
# Luna custom
# encoding: utf-8
patch:
  switches:
    - name: full_shape
      reset: 1
      states: ["半角", "全角"]
    - name: simplification
      reset: 1
      states: ["漢字", "汉字"]
    - name: ascii_punct
      reset: 0
      states: ["句讀", "符號"]
  # "menu/alternative_select_keys":
  #   '{[(</\>)]}'    # not working

  # first launch type English
  "switches/@0/reset": 0 #表示將 switcher 列表中的第一個元素（即 ascii_mode 開關）的初始值重設爲狀態1（即「英文」）。

  "key_binder/bindings":
    # Change language with Ctrl+|
    - {accept: "Control+bar", toggle: ascii_mode, when: always}
    # pageup/pagedown to choose characters with ,/.
    - {when: has_menu, accept: period, send: Page_Down}
    - {when: has_menu, accept: comma, send: Page_Up}
    # For SymmeTri
    - {accept: braceleft, send: 1, when: has_menu}      # 大括号選1
    - {accept: bracketleft, send: 2, when: has_menu}    # 中括号選2
    - {accept: parenleft, send: 3, when: has_menu}      # 括号選3
    - {accept: less, send: 4, when: has_menu}           # 小括号選4
    - {accept: slash, send: 5, when: has_menu}          # 斜杠选5
    - {accept: backslash, send: 6, when: has_menu}      # 反斜杠选6
    - {accept: greater, send: 7, when: has_menu}        # 右小括号选7
    - {accept: parenright, send: 8, when: has_menu}     # 右括号选8
    - {accept: bracketright, send: 9, when: has_menu}   # 右中括号选9
    - {accept: braceright, send: 0, when: has_menu}     # 右大括号选0
```

请指教一下，万分感谢
