### ISSUE TITLE
能否给 enable_correction 纠错添加权重？

### ISSUE THREAD

**Issue by tty228** [rime/home#1953]
应该优先显示实际输入的按键，或者可选单字时不启用，仅对词组启用？
这个功能主要是用于在输入较长句子时，如果中途出现一两个字母的错误可以避免删除整段输入，但实际使用中，有时候正确的输入，给出了大量的其它结果，并且正确的输入没有在第一个，这在单字时尤为明显

小鹤双拼：

![Image](https://github.com/user-attachments/assets/28572881-be17-4ae1-90e5-06b4eec57de8)

![Image](https://github.com/user-attachments/assets/8dca43b8-db4e-49a3-b12b-86f225a41abc)

![Image](https://github.com/user-attachments/assets/b67fe6d6-a18e-46e2-8d12-9848485335f7)

Windows 10
小狼毫  0.17.4

**Comment by lotem** [comment]
纠错会降低权重，但是想要调整到理想的效果恐怕很难。

**Comment by isudfv** [comment]
@tty228 我看 example 里 enable_correction 就是放在主翻译器里的 `translator/enable_correction: true`，可以麻烦再细致讲解下你的方案吗。

**Comment by tty228** [comment]
> [@tty228](https://github.com/tty228) 我看 example 里 enable_correction 就是放在主翻译器里的 `translator/enable_correction: true`，可以麻烦再细致讲解下你的方案吗。


```
# double_pinyin_flypy.custom.yaml
patch:
  engine/translators/+:
    - script_translator@corrected	# 添加次翻译器：自动纠错

  #translator/+:
    #translator/prism: double_pinyin_flypy		# 多方案共用一个词库时，为避免冲突，需要用 prism 指定一个名字；如主翻译器未指定名称，需取消注释并设置该项

  corrected:
    enable_correction: true		# 基于 QWERT 键位的纠错。
    dictionary: rime_ice		# 挂载词库 rime_ice.dict.yaml，，需修改为和主翻译器相同的值
    prism: double_pinyin_flypy		# 多方案共用一个词库时，为避免冲突，需要用 prism 指定一个名字；需修改为和主翻译器相同的值
    spelling_hints: 2			# 设定多少字之内显示正确拼音
    initial_quality: 0.1		# 权重，建议设置至少低于英文

  #speller/algebra/+:
    # 首字母简拼，开启后会导致 3 个字母时 kj'x 变成 k'jx 的问题
    #- abbrev/^(.).+$/$1/	# 全部开启
```

建议配合跨翻译器去重 Lua，使用次翻译器的话，去重功能是失效的：
（万象拼音自带了这个功能，雾凇的话需要设置一下）

```
-- lua/dedup_candidates.lua
-- dedup_candidates_filter: 跨翻译器去重

local function filter(input, env)
    local seen = {}
    
    for cand in input:iter() do
        local text = cand.text
        if not seen[text] then
            seen[text] = true
            yield(cand)
        end
    end
end

return filter
```

```
# patch
patch:
  engine/filters/+:
    - lua_filter@dedup_candidates_filter        # 跨翻译器去重
```

```
-- rime.lua
dedup_candidates_filter = require("dedup_candidates")
```

有一些需要注意的地方
1. 如果要开启简拼的话识别率会特别低，不建议开启，或者只在自定义短语中加入部分需要使用的简拼
2. 如果需要移植到手机版本，建议注释 spelling_hints 拼音显示，或者减小数值
3. 如果是词库里面没有的词组，需要手动拼接的情况下，因为开启纠错会产生大量的词语，造成备选的词组在候选栏里面会非常靠后，输入人名的时候也是差不多的情况：<img width="1031" height="108" alt="Image" src="https://github.com/user-attachments/assets/f0ec3aa1-a3e2-4201-bacd-388c08e36687" />
暂无比较完美的解决方案，我是使用了这个 Lua：
https://github.com/rime/home/issues/406

<img width="429" height="90" alt="Image" src="https://github.com/user-attachments/assets/3ee6c7ad-724d-47e3-bee7-ccf78ddd4c29" />
 
<img width="566" height="90" alt="Image" src="https://github.com/user-attachments/assets/716aae21-f281-4625-884a-a93c662801f7" />
