### ISSUE TITLE
用五笔打出字后，能不能查出这个字的拼音

### ISSUE THREAD

**Issue by jinweizhiyuan** [rime/home#205]
有时候用五笔能打出字来，就是不知道字的拼音怎读，加上个五笔反查拼音就完美了

**Comment by vesper305** [comment]
但是, Mac上三指查词不是有汉语词典吗, 何必要添加这么个功能呢

**Comment by jinweizhiyuan** [comment]
@vesper305 输入法加入这个功能更好，我用的是windows没有三指查词这个功能，总不能五笔打完字后，去百度查吧，有点麻烦，休验好

> 但是, Mac上三指查词不是有汉语词典吗, 何必要添加这么个功能呢

**Comment by vesper305** [comment]
Sorry, 考虑不周.
如果是这样的话, 确实可以在候选词中加入(是否开启?)显示拼音. 我记得以前搜狗输入法似乎就有这个功能(对生僻字分部分输入之后, 第一行最后一个候选就是拼音).

**Comment by jinweizhiyuan** [comment]
期待加入这个功能

**Comment by lotem** [comment]
能。
請自助設置拼音反查。

**Comment by lotem** [comment]
配置方法是 使用 `reverse_lookup_filter`，參照下例的中古音反查
https://gist.github.com/lotem/e964a81c1ea457a6ae92
改爲拼音反查
```yaml
engine:
  filters:
    - reverse_lookup_filter@pinyin_lookup
    - uniquifier
pinyin_lookup:
  tags:  abc
  dictionary: terra_pinyin
  overwrite_comment: true  # 覆蓋其他提示
  comment_format: # 參考 terra_pinyin.schema.yaml 的拼寫運算改寫聲調符號
```
