### ISSUE TITLE
mac os 下 punctuator 相关的符号没有效果

### ISSUE THREAD

**Issue by hejunping** [rime/home#285]
系统是:mac os 10.11.1
default.custom.yaml
配置如下:

```
 patch:
   schema_list:
     - schema: wubi_pinyin
     - schema: emoji
   "switcher/caption": "〔切换〕"
   #中英文切换的方式
   "ascii_composer/good_old_caps_lock":  true
   "ascii_composer/switch_key":
     Shift_L: commit_code
```

输入全角半角的符号:"!@#$%^&*(" 直接显示没有选项,不知道哪里出错了,还是需要其它配置,谢谢!
