### ISSUE TITLE
小狼毫自訂詞庫無法自動同步到另一台電腦

### ISSUE THREAD

**Issue by 2ipm1nd** [rime/home#287]
您好，我自行利用教學的詞庫製作說明附加了好幾個詞庫，利用雲端硬碟同步後發現：

假設我在A電腦製作好詞庫後同步

A電腦→B雲端(A電腦同步資料夾)——**自訂詞庫存在**

B雲端→C電腦(C電腦同步資料夾)——**自訂詞庫皆不存在**

C電腦即使執行同步也沒辦法將詞庫複製下來，請問有辦法讓他能自動同步嗎？還是只能手動複製呢？

**Comment by lotem** [comment]
> C電腦(B電腦同步資料夾)

B不是雲端嘛？配置文件應在：C電腦(A電腦同步資料夾)

**Comment by 2ipm1nd** [comment]
>
>
> > C電腦(B電腦同步資料夾)
>
> B不是雲端嘛？
> YAML文件的備份應在：C電腦(A電腦同步資料夾)

抱歉，我筆誤。
主要是這樣我從A電腦同步到B雲端，會出現A電腦的ID資料夾假設為A-PC
此時的A電腦用戶資料夾及“A-PC”資料夾都有自訂詞庫。
然後C電腦執行同步到B雲端，出現C電腦的ID資料夾，假設為C-PC
此時C電腦用戶資料夾及“C-PC”資料夾都沒有出現自訂詞庫。
需要手動將“A-PC”資料夾裡面的詞庫貼到C電腦用戶資料夾才行

想要同步的檔案名稱如下

`custom_phrase.txt`——自定義短語

`luna_pinyin.extended.dict.yaml`——擴展詞庫？

```yaml


name: luna_pinyin.extended
version: "2018-11-19"
sort: by_2ipm1nd
use_preset_vocabulary: true
import_tables:

- luna_pinyin
- luna_pinyin.qqinput
- luna_pinyin.d3
- luna_pinyin.chengyu
- luna_pinyin.taiwan01
- luna_pinyin.hydraulic
- luna_pinyin.hydraulic2
```

`luna_pinyin.chengyu.dict.yaml`——自定義詞庫
`luna_pinyin.d3.dict.yaml`——自定義詞庫
`luna_pinyin.hydraulic.dict.yaml`——自定義詞庫
`luna_pinyin.hydraulic2.dict.yaml`——自定義詞庫
`luna_pinyin.qqinput.dict.yaml`——自定義詞庫
`luna_pinyin.taiwan01.dict.yaml`——自定義詞庫

是否有解決之道呢？
