### ISSUE TITLE
【需求】英文打了一半，才發現是中文輸入模式，要按[Shift]要直接切換為英文模式，並上屏打了一半的英文。

### ISSUE THREAD

**Issue by dean0224** [rime/home#316]
很多時候要打英文，打了一半，才發現是中文輸入模式，這時候就很麻煩了。 
這個時候，如果按[SHIFT]， 只會在中文輸入框裡面變成 [A] 英文，並不會變成真正的英文輸入模式。 如果按[ENTER] 上屏之後，又變回[中]中文。 還要再按一次[SHIFT] 才會真正變成[A]英文模式。 不管怎樣都要按好幾次。  

理想的結果是，中文輸入模式下，打了英文，直接按[SHIFT]就可以把英文上屏並換成純英文輸入模式，繼續打英文。 這樣。
謝謝

**Comment by nameoverflow** [comment]
```yaml
# default.custom.yaml
patch:
  ascii_composer:
    good_old_caps_lock: true
    switch_key:
      Shift_L: commit_code
```
