### ISSUE TITLE
WIN10系統紫光雙拼的問題。

### ISSUE THREAD

**Issue by whyAtGh** [rime/home#320]
下面是我的方案，模仿紫光雙拼寫的，結果一部分亂掉了，u和i不能寫出zh和sh，分號；寫不出ing。
```
speller:
  alphabet: zyxwvutsrqponmlkjihgfedcba  # 呃，倒背字母表完全是個人喜好
  delimiter: " '"  # 隔音符號用「'」；第一位的空白用來自動插入到音節邊界處
  algebra:  # 拼寫運算規則，這個纔是實現雙拼方案的重點。寫法有很多種，當然也可以把四百多個音節碼一條一條地列舉
    - erase/^xx$/             # 碼表中有幾個拼音不明的字，編碼成xx了，消滅他
    - derive/^([jqxy])u$/$1v/
    - xform/^zh/U/            # 替換聲母鍵，用大寫以防與原有的字母混淆
    - xform/^ch/A/
    - xform/^sh/I/
    - xform/^([aoe].*)$/O$1/  # 添上固定的零聲母o，先標記爲大寫O
    - xform/iao$/B/           # 對像這樣讓iao提前出場
    - xform/ao$/Q/            # 替換韻母鍵
    - xform/ian$/F/           # ※2
    - xform/er$|iu$/J/        # 對應兩種韻母的；音節er現在變爲OR了
    - xform/[iu]ang$/G/       # ※1
    - xform/ing$/;/
    - xform/uo$/O/
    - xform/uan$/L/           # ※3
    - xform/i?ong$/H/
    - xform/[iu]a$/X/
    - xform/en$/W/
    - xform/eng$/T/
    - xform/ang$/S/           # 檢查一下在此之前是否已轉換過了帶介音的ang；好，※1處有了
    - xform/an$/R/            # 如果※2、※3還無有出現在上文中，應該把他們提到本行之前
    - xform/ei$/K/
    - xform/in$|uai$/Y/       # 讓uai提前出場
    - xform/ai$/P/
    - xform/ie$/D/
    - xform/ou$/Z/
    - xform/un$/M/
    - xform/[uv]e$|ui$/N/
    - xlit/QWERTYOPASDFGHJKLZXCVBNM/qwertyopasdfghjklzxcvbnm/  # 最後把雙拼碼全部變小寫
```

謝謝！
