### ISSUE TITLE
小狼毫地球拼音设置标点补丁时，对 '=' 重映射后，会影响到对 '/' 映射。何解？

### ISSUE THREAD

**Issue by kangdalei** [rime/home#335]
win7，小狼毫（0.13.0.0）使用地球拼音，在方案 terra_pinyin.custom.yaml 里对标点符号进行设置：

```
patch:
  punctuator/import_preset: symbols
  punctuator/half_shape:
    "_" : [ "_", "——" ]
```

symbols.yaml文件里有一行
`'=' : [ '=', 々, 〃 ]`

到目前为止，一切正常。但是我想输入 '=' 时候， '=' 直接上屏 ，因为后两个字符很少用。

两种办法，一是在symbols.yaml里直接注释掉 '=' : [ '=', 々, 〃 ] 这行。ok，办法行得通。
另一种办法在terra_pinyin.custom.yaml 里添加修正，正如对 '_' 作的那样：

```
patch:
  punctuator/import_preset: symbols
  punctuator/half_shape:
    "_" : [ "_", "——" ]
    '=' :  '='
	
  recognizer/patterns/punct: "^/([A-Z|a-z]*|[0-9]|10)$"
```

重新部署后，输入 '/' 时，
![图片](https://user-images.githubusercontent.com/31817131/54337044-a462eb00-4668-11e9-92a4-32c13973d7b0.png)

连锁导致特殊符号的输入 /fh /dn 等待都失效了。

为何对 '=‘ 的修改会造成这样？莫非 ’=‘ 有特殊用法？
