### ISSUE TITLE
怎么才能设置打字的时候显示的边框宽度,小狼豪输入法宽度太大了,搜索的时候没有人提到如何设置

### ISSUE THREAD

**Issue by 1445453337** [rime/home#340]

**Comment by Trim21** [comment]
```yaml
  "style/layout/border_height": 5   # 窗口边界高度，大於圆角半径才有效果
  "style/layout/border_width": 5   # 窗口边界宽度，大於圆角半径才有效果
  "style/layout/margin_x": 4 # 窗口边界距离
  "style/layout/margin_y": 4 # 窗口边界距离
  "style/layout/spacing": 3 #候选竖排时候与候选词的间距 
  "style/layout/candidate_spacing": 1 # 候选间距
```
