### ISSUE TITLE
speller/auto_select_unique_candidate 是否已弃用？

### ISSUE THREAD

**Issue by Ace-Who** [rime/home#362]
「Rime方案製作詳解」的 [tumblr 版本](https://rime-aca.tumblr.com/post/67241713724/rime%E6%96%B9%E6%A1%88%E8%A3%BD%E4%BD%9C%E8%A9%B3%E8%A7%A3)有介绍 `auto_select_unique_candidate` 这个选项，实测没有效果（已设定 `speller/auto_select: true`）。[GitHub 版本](https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md)则没有这个选项，而是代之以 `auto_select_pattern`，看描述并不能实现前者的功能。

顺便一提，两个版本还有一处不同是 `fluency_editor` 和 `fluid_editor`，目前 luna_pinyin_fluency.schema 使用的是前者（tumblr 版）。

------

参考备用：

- [auto_select時空碼不上屏問題](https://github.com/rime/librime/issues/54)

**Comment by Ace-Who** [comment]
```
# cangjie5.custom.yaml

patch:
  speller/auto_select: true
  speller/auto_select_unique_candidate: true
  translator/enable_user_dict: false
  translator/enable_encoder: false
  translator/enable_sentence: false
  abc_segmentor/extra_tags: []
```
