### ISSUE TITLE
改進配置管理器打補丁的方式

### ISSUE THREAD

**Issue by lotem** [rime/home#364]
目前 /plum/ 通過bash腳本支持的補丁配方，實現方式十分複雜。例如：
```yaml
# default.custom.yaml
patch:
  menu/page_size: 3
__patch:
# Rx: custom:clear_schema_list: {
  - patch/+:
      schema_list: []
# }
# Rx: custom:add:schema=combo_pinyin_kbcon {
  - patch/+:
      schema_list/+/+:
        - schema: combo_pinyin_kbcon
# }
# Rx: custom:add:schema=bopomofo {
  - patch/+:
      schema_list/+/+:
        - schema: bopomofo
# }
```

其中每組 `# Rx: ... {`  `# }` 之間的代碼是一副配方添加的，所有配方補丁寫入 `default.custom.yaml:/__patch` 列表，這種格式可以一直向後追加補丁而不會出現 YAML map k有重複 key 的問題，只要按照約定的縮進量追加文本行即可，不需要做YAML解析，因此適合用bash腳本實現。這種方式基本不會破壞原有的用戶手寫補丁，如上例的 `patch` 節點。

不過配方補丁先對 `default.custom.yaml:/patch` 打補丁，然後生成的 `patch` 再以自動補丁的形式在配置文件編譯過程中應用到 `default.yaml:/` 配置文件。這很不直觀，而且需要複雜的轉義如 `schema_list/+/+`，挑戰着配方作者的碼力。

原先 [`rimekit`](https://github.com/lotem/rimekit) 以及 `rime_patch` 程序未完成的工作，都會直接改動YAML文件（儘量寫補丁文件）。這樣是比較直觀的，即以應用配方替代手工編輯配置。改進的配置管理器應當採用這種模式。唯一的問題是怎樣讓配方補丁和用戶已有的手寫補丁相容，最好能撤銷所有補丁配方；能保留用戶手寫的註釋就更好了（YAML序列化無法留存註釋，可能得藉助於版本控制）。
總之改進配置管理器，也包括摸索出一套工作流，以及管理輸入法配置的最佳實踐。
