### ISSUE TITLE
输入框ui不正常

### ISSUE THREAD

**Issue by z1shiki** [rime/home#367]
> 版本:weseal 0.13 
> OS:Windows10 专业版 1809

问题: 在有些情况下输入框会变化成如图所示的样子
![微信图片_20190510190206](https://user-images.githubusercontent.com/17572740/57523369-5fe98800-7357-11e9-9e82-3c3448300037.png)

原本应有的样子是
![微信图片_20190510191051](https://user-images.githubusercontent.com/17572740/57523393-70016780-7357-11e9-8265-b558f2a04691.png)

尝试过直接重新部署 无法解决问题.在清空过weasel.custom.yaml内容后重新部署可以解决问题,再重新加上自己的设置项也可以正常显示.

我的weasel.custom.yaml配置项如下
```
patch: 
  style: 
    color_scheme: google 
    font_point: 16 
    horizontal: true 
```

输入方案的定制内容较多不贴在此.想知道这个界面问题的发生原因以及解决方法.
