### ISSUE TITLE
single_char_filter 的作用疑问与在一个用例中的副作用

### ISSUE THREAD

**Issue by Ace-Who** [rime/home#370]
## 作用是什么？

[Rime方案制作详解](https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md):

> single_char_filter 單字過濾器，如加載此組件，則屛敝詞典中的詞組〔僅table_translator有效〕

[cangjie5.schema.yaml](https://github.com/rime/rime-cangjie/blob/master/cangjie5.schema.yaml):

```yaml
...
engine:
...
  filters:
    - simplifier
    - uniquifier
    - single_char_filter
...
```

实际使用中，候选中是有词组的，如「屏蔽 sttfk」「詞組 yrvfm」。那么「屏蔽词组」是什么意思呢？

## 一个用例中的不解现象

之前参考 https://github.com/rime/librime/issues/184#issuecomment-404392645 在仓颉中实现相同功能。

```yaml
# cangjie5.custom.yaml
patch:
  translators:
    - punct_translator
    - reverse_lookup_translator
    - table_translator@fixed
    - table_translator
  # 惟独没加这两行
  # engine/filters:
  #  - uniquifier
  fixed:
    __include: cangjie5.schema:/translator
    enable_user_dict: true
    enable_encoder: true
    initial_quality: 1000
    disable_user_dict_for_patterns:
      - '.*'
```

结果有不少情况下——但又不是全部——候选出现重复。比如「复 oahe」「情 pqmb」「况 imrhu」「全部 ogyrl」和自造词。将 single_char_filter 移除，或将 uniquifier 移至末尾，就没有这个现象了。根据 [RimeWithSchemata](https://github.com/rime/home/wiki/RimeWithSchemata)，看不出有何必要将 uniquifier 放在 single_char_filter 之后，也不明白为何 cangjie5.schema.yaml 又不是这样做的。

**Comment by nameoverflow** [comment]
single_char_filter 是把单字提到最前，并不是屏蔽词组。

**Comment by Ace-Who** [comment]
@nameoverflow 谢谢，我在 http://rimeime.github.io/release/squirrel/ 也看到这个解释。第二个问题是怎么回事呢？

**Comment by ZenLian** [comment]
如果想只打单字而完全不显示词组，可以用 lua 自定义过滤器。贴一下我刚摸索到的方法，可在词组和单字模式间切换，供参考：
```lua
-- rime.lua
function single_char_filter(input, env)
  on = env.engine.context:get_option("single_char")
  for cand in input:iter() do
    if not on or utf8.len(cand.text) == 1 then
      yield(cand)
    end
  end
end
```
```yaml
# wubi.custom.yaml
patch:
  switches/+:
    - name: single_char
      states: [词组, 单字]
      reset: 1
  engine/filters/+:
    - lua_filter@single_char_filter
```
