### ISSUE TITLE
数字区的enter键无效。

### ISSUE THREAD

**Issue by lunarjoll** [rime/home#374]
在拼音模式下按回车键可以输入英文，但数字区的回车键没有用。

**Comment by lunarjoll** [comment]
系统 ：archlinux

**Comment by Ace-Who** [comment]
试试自定义 `KP_Enter` 键的行为。

```yaml
# default.custom.yaml
patch:
  key_binder/bindings/@next: { when: composing, accept: KP_Enter, send: Enter }
```
