### ISSUE TITLE
如何配置每次启动默认五笔输入，不记忆中间切换的输入方案（拼音）？

### ISSUE THREAD

**Issue by lccc7liu** [rime/home#379]
大家好，使用Rime，觉得很好用，也希望去把它配置得更好，这里向大家请教一下。
如何配置每次启动默认五笔输入，不记忆中间切换的输入方案（拼音）？
每个程序当我切换Rime输入的时候，我希望默认五笔，而现在Rime会记忆中间切换的输入方案，这个如何配置，我查找了半天，没找到方案。
谢谢！

**Comment by lccc7liu** [comment]
有人能提供一些建议吗？

**Comment by Ace-Who** [comment]
据我了解没有这个功能。可以试试在 user.yaml 上做文章。

**Comment by lotem** [comment]
設置整個選項
https://github.com/rime/librime/blob/master/src/rime/gear/schema_list_translator.cc#L136

**Comment by lccc7liu** [comment]
> 
> 
> 設置整個選項
> https://github.com/rime/librime/blob/master/src/rime/gear/schema_list_translator.cc#L136

我在default.yaml里的switcher添加了fix_schema_list_order，好像还是不起作用，是我修改有问题？
switcher:
  caption: "銆旀柟妗堥伕鍠€?
  hotkeys:
    - "Control+grave"
    - "Control+Shift+grave"
    - F4
  save_options:
    - full_shape
    - ascii_punct
    - simplification
    - extended_charset
  fix_schema_list_order:
    - schema: wubi86
    - schema: luna_pinyin
    - schema: luna_pinyin_fluency
    - schema: luna_pinyin_simp
    - schema: luna_pinyin_tw

**Comment by Ace-Who** [comment]
不要修改 default.yaml 文件。

「每次启动」和「每个程序切换」是两种不同的情境，不知道符不符合你的需求，但是我测试出的做法是：

```yaml
# default.custom.yaml

patch:
  schema_list:
    - <自己填写>
    - <自己填写>
    - <自己填写>
    ……
  switcher/fix_schema_list_order: true
```
