### ISSUE TITLE
删词快捷键删掉了未选中的自造词

### ISSUE THREAD

**Issue by Ace-Who** [rime/home#381]
Windows 7 + Weasel 0.14.0.135

郑码自造词「导读」，键入 hdsa，光标移至其他候选词，按 <kbd>Ctrl</kbd> + <kbd>Delete</kbd> 或 <kbd>Shift</kbd> + <kbd>Delete</kbd>，结果「导读」被删除了。

**Comment by Ace-Who** [comment]
退回 0.13 也会这样。再造一个词「导谎」，键入 hdsa，前两个候选词是「导读」「导谎」。若光标移至「导谎」，删词，则两词都被删。若光标移至其它候选词，比如单字，删词，则「导读」被删。看起来是首个候选一定会被删。

**Comment by Ace-Who** [comment]
退回 0.13 后，发现 WeaselServer.exe 一直占用 CPU 25% 左右，Tim 卡死。重启后，Tim 和 Notepad2 反复卡死，无法自造词（自造词不出现在候选中），WeaselServer.exe 一直占用 CPU 40%-70%。

**Comment by Ace-Who** [comment]
```yaml
# zhengma_mod.schema.yaml

...
engine:
  ...
  translators:
    -punct_translator
    -table_translator@fixed  # 注释掉这行就没有问题了，那么有什么办法保留这个功能，又保证删词正常呢？
    ...
...

fixed:
  __include: translator
  enable_user_dict: true
  enable_encoder: true
  initial_quality: 1000
  disable_user_dict_for_patterns:
    - '.*'
...
```
