### ISSUE TITLE
拼写运算 derive 不适用于形码自造词吗？

### ISSUE THREAD

**Issue by Ace-Who** [rime/home#384]
```yaml
# zhengma_mod.schema.yaml

......
speller:
  algebra:
    - derive/z/e/
    - derive/t/p/
......
```

自造词含 z 或 t 的，用 z 和 t 能打出，用 e 和 p 就不出现在候选中。固态词典中的词就没有这个问题。
