### ISSUE TITLE
特殊符号引导符'/' 如何更换

### ISSUE THREAD

**Issue by ryan00zou** [rime/home#385]
尝试过将'/'更换成'\'，把特殊符号和punct的地方都进行了相应替换，但是并不能实现。请问如何能把引导符替换为别的按键。谢谢

**Comment by Ace-Who** [comment]
详细说明一下修改了哪里。

**Comment by ryan00zou** [comment]
改动地方1: patch: 'recognizer/patterns/punct': "^/([a-z]+|[0-9])$"   把punct后面的/ 换成 \或者\\
2: symbols.custom.yaml中 /fh, /dn等的/换成了\。
都没有效果。

**Comment by Ace-Who** [comment]
`punctuator/import_preset` 指定的文件，我记得是不接受 .custom.yaml 文件的补丁的。所以，请复制一份程序目录的 symbols.yaml 到用户目录，然后直接修改它。

**Comment by ryan00zou** [comment]
你好，用户文件夹复制并改名了
mysymbols.yaml
patch:
  punctuator/import_preset: mysymbols
  recognizer/patterns/punct: '^\\([0-9]0?|[A-Za-z]+)$'
  symbols:
#符號、電腦
    '\fh': [ ©, ®, ℗
   '\dn': [ , ❖, ⌘, 

输入方案xhup.schema.yaml
punctuator:
  import_preset: mysymbols
recognizer:
  import_preset: default
patterns:
    punct: "^\\([0-9]0?|[a-z]+)$"
    reverse_lookup: "`[a-z]*'?$"
这样'/'确实不能引导了，但是按'\fh'还是不行

**Comment by Ace-Who** [comment]
代码块请用单独成行的

\```yaml

和

\```

包裹，不然看不出缩进问题。如：

\```yaml
```yaml
# mysymbols.yaml

……
patch:  # 该文件中的这个 patch 节点应该是用来说明如何在 <schema_id>.custom.yaml 中打补丁的，不起实际作用
  ……

punctuator:
  full_shape:
    ……
  half_shape:
    ……
  symbols:
    '\fh': [ …… ]
    '\dn': [ …… ]
    ……
```
\```

和

\```yaml
```yaml
# xhup.custom.yaml

patch:
  punctuator/import_preset: mysymbols
  recognizer/patterns/punct: '^\\([0-9]0?|[A-Za-z]+)$'
  ……
```
\```

**Comment by Ace-Who** [comment]
如果把 mysymbols.yaml 中的 patch 节点的 symols 改为 mysymbols，如你所做的那样，即

```yaml
# mysymbols.yaml

patch:
  punctuator/import_preset: mysymbols
  recognizer/patterns/punct: '^\([0-9]0?|[A-Za-z]+)$'

……
```

那么方案补丁也可以引用它，写为

```yaml
# xhup.custom.yaml

__patch: mysymbols:/patch

……
```

**Comment by Ace-Who** [comment]
更正：实验确认，symbols.custom.yaml 补丁是可行的，应该是别的地方有问题，比如补丁格式，应写在 patch 节点中。

**Comment by Ace-Who** [comment]
利用 symbols.custom.yaml 打补丁的方法：

```yaml
# symbols.custom.yaml

patch:
  punctuator/symbols:
    '\fh': [ …… ]
    '\dn': [ …… ]
    ……
```

```yaml
# xhup.custom.yaml

patch:
  __include: symbols:/patch

```

**Comment by ryan00zou** [comment]
@Ace-Who 可以了，非常感谢，看来可能是之前
```yaml
  #symbols.custom.yaml
  patch:
    punctuator/import_preset: symbols
    recognizer/patterns/punct: '^\\([0-9]0?|[A-Za-z]+)$'
  ……
```
和
```yaml
  #xhup.custom.yaml
  recognizer:
    import_preset: default
    patterns:
      punct: "^\([0-9]0?|[a-z]+)$"
      reverse_lookup: "`[a-z]*'?$"
```
中punct后面的双引号引起的问题。
感谢！！！

**Comment by StayTherapy** [comment]
😂😂 , 遇到了同样的问题, 多谢多谢.

这个配置真的跟解谜一样, 习惯了 `\` 作为转义符号, 想把 symbols 引导符也换成 `\`, 只换个符号不够, 想把文件名也换了, 结果弄一晚上没弄好, 主要是误以为 `symbols.yaml` 里面 `punctuator/symbols` 里的 `symbols` 跟文件名一样是可以自定义的, [Schema.yaml 詳解](https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md) 已经很详细了, 但是好像没有指出 `symbols` 也是个属性.

所以参考楼上简单来说自定义符号就是 4 个条件(只列出关键配置):
```yaml
# 1 创建 [名称].yaml 符号文件; 内置的符号文件名为 symbols.yaml, 可以沿用(沿用就没那么多事了), 也可以复制一份修改
# 2 [方案].schema.yaml 中指定符号文件
punctuator
  import_preset: [名称]
# 3 [方案].schema.yaml 中指定触发符号翻译的正则, 因为 \ 在正则里是关键符号, 所以用 \\ 把它自己转义了, 如果用 / 就不用转义 
recognizer
  patterns
    punct: '^\\[a-z]+$'
# 4 [名称].yaml 符号文件按如下格式写, 强调下, symbols 也是关键字;
# 一般 full_shape, half_shape 也一起在这里定义了, 注意至少包含 \\ (YAML 中被转义的 \ )的定义, 否则输入框不认
punctuator:
  symbols:
    '\bg': [ ☰, ☱, ☲, ☳, ☴, ☵, ☶, ☷ ]
    # 其他符号
  full_shape:
    "\\": ["、", "＼"]
  half_shape:
    "\\": ["、", "\\", "＼"] 
```
