### ISSUE TITLE
仓颉五怎么设置简入繁出？

### ISSUE THREAD

**Issue by flyingns** [rime/home#388]
请教，谢谢。

**Comment by Ace-Who** [comment]
```yaml
# cangjie5.custom.yaml

patch:
  switches:
    - name: ascii_mode
      reset: 0
      states: [ 中文, 西文 ]
    - name: full_shape
      states: [ 半角, 全角 ]
    - name: simplification
      states: [ 漢字, 汉字 ]
    # 增设一个开关来控制简入繁出
    - name: traditionalization
      # 初始状态，0 = 禁用，1 = 启用
      reset: 0
      # 首字分别用简体的「简」和繁体的「簡」，便于在方案选单中区分
      states: [ 简体保持, 簡入繁出 ]
    - name: extended_charset
      states: [ 常用, 增廣 ]
    - name: ascii_punct
      states: [ 。，, ．， ]

  engine/filters:
    - simplifier@simplify  # 保留原有的「简化」即「繁入简出」功能
    - simplifier@traditionalize  # 简入繁出
    - single_char_filter
    - uniquifier

  simplify:
    option_name: simplification
    tips: all

  traditionalize:
    opencc_config: s2t.json
    option_name: traditionalization
    tips: all

  # 增设一个快捷键来开关简入繁出过滤器（可选）
  key_binder/bindings:
    - {accept: "Control+Shift+F", toggle: traditionalization, when: always}
```
