### ISSUE TITLE
请问为什么在0.13版本鼠须管中无法切换输入法了？

### ISSUE THREAD

**Issue by cookpu** [rime/home#390]
更新0.13后就彻底一头雾水 怎么也切换不出来繁体和别的输入法 明明文件夹里有
[THANK YOU.zip](https://github.com/rime/home/files/3318994/THANK.YOU.zip)
mac系统版本OSX10.13.6 不知道是哪里设置出错 附上设置文件 希望大神帮忙 十分感谢。

**Comment by Ace-Who** [comment]
误：

```yaml
patch:
  schema_list:
    - schema: double_pinyin_flypy
    - schema: luna_pinyin_simp
    - schema: luna_pinyin_tw
```

正：

```yaml
patch:
  schema_list:
    - {schema: double_pinyin_flypy}
    - {schema: luna_pinyin_simp}
    - {schema: luna_pinyin_tw}
```
