### ISSUE TITLE
请问怎么设置在五笔拼音状态下按z键可以重复输出？

### ISSUE THREAD

**Issue by uoow** [rime/home#396]
这个功能在五笔里是普遍用上了，不知道RIME有没有这个选项。如：输出“五笔”后，再按一次z键，空格，则再输出”五笔“一次。

**Comment by Ace-Who** [comment]
「普通用上了」是什么意思？不知道「拼音状态」是指什么，以及为什么要求在该状态下实现这个功能。

以下是撇开这些问题的解法，以五笔 86 方案为例。

```yaml
# wubi86.custom.yaml

patch:
  engine/translator/@next: history_translator@history

history:
  input: z
  size: 1
  initial_quality: 1
```

**Comment by uoow** [comment]
抱歉。打错了，应该是“普遍用上了”。「五笔拼音」是指RIME里的输入方案，这个状态。简单来说就是要z键重复输出。
用你所说的设置并不生效。代码如下：
# wubi_pinyin.custom.yaml

patch: 
  "switches/@0/reset": 1
  "engine/translator/@next": history_translator@history
  
  "key_binder/bindings":
    - { when: has_menu, accept: semicolon, send: 2 }
    - { when: has_menu, accept: apostrophe, send: 3 }
    
history:
  input: z
  size: 1
  initial_quality: 1

**Comment by Ace-Who** [comment]
`engine/translator` 改为 `engine/translators`。

**Comment by uoow** [comment]
我也发现了这个问题，但还是不生效。

**Comment by Ace-Who** [comment]
这就不知道为什么了。看看有没有错误志—— `%TEMP%\rime.weasel.%COMPUTERNAME%.%USERNAME%.log.ERROR.<DATE-TIME>`，确定一下是否部署成功。部署会重新生成 `%APPDATA%\Rime\build\wubi_pinyin.yaml`，看看修改时问和内容对不对。

**Comment by Ace-Who** [comment]
抱歉，是我的错：

```yaml
# wubi86.custom.yaml

patch:
  engine/translators/@next: history_translator@history

  history:
    input: z
    size: 1
    initial_quality: 1
```

**Comment by uoow** [comment]
没看明白，还是修改原来那个文件吗？然后把history那一段都退两格？但是依然不生效。本人愚钝，还请明示！@Ace-Who

**Comment by Ace-Who** [comment]
对。

**Comment by uoow** [comment]
试过了，还是无效。
`#wubi_pinyin.custom.yaml
patch: 
  "switches/@0/reset": 1
  "engine/translators/@next": history_translator@history
  
  "key_binder/bindings":
    - { when: has_menu, accept: semicolon, send: 2 }
    - { when: has_menu, accept: apostrophe, send: 3 }
  

  history:
    input: z
    size: 1
    initial_quality: 1`

**Comment by bosconb** [comment]
我的设置部分，小鹤音形方案，;f触发。

```
engine:
  translators:
    - punct_translator
    - reverse_lookup_translator
    - history_translator@history
```

```
history:
   input: ;f
   size: 1
   initial_quality: 1
```

**Comment by uoow** [comment]
@Ace-Who 知道原因了，你给的设置方法没错，可以用，但不能与拼音词典一起用，不然会解释为拼音的开头的。我在另一台电脑上测试，重装了并把设置复制过去，但忘记添加拼音词典，得出了z键是可以重复输出的，但没法同时用拼音；在添加拼音词典后z键却不生效了

**Comment by lotem** [comment]
從樓上的描述看，應該已經有效。出現在拼音候選之後。

**Comment by Ace-Who** [comment]
@uoow 确实用 `z` 不行，翻到最后也没出现，不知道为什么，可能与 pinyin_simp 是 reverse_lookup_translator 有关。`input: zv` 是可以的。

**Comment by uoow** [comment]
@lotem 问题并没有解决。因为五笔拼音方案依赖于拼音词典，我上面说测试生效是因为没有添加该词典，一旦添加后，z键首先匹配了拼音，那个设置z键重复输出的就失效了。能否指导一下怎么改设置，可以在按z键时，首选匹配的是重复，候选才是拼音内容。
@Ace-Who 所以，现在就有两种折衷方法。1、用五笔86方案，用这个设置z键就可以重复输出，敲z+拼音字母则输出拼音内容；2、用五笔拼音方案，然后将重复键设为v，因为没有拼音字是v开头的，所以匹配不到拼音内容，则设置生效。但是这样的话1的效率就不够高，2就要改变习惯。
暂时就QQ五笔用得没问题，它基本不更新了，就想转到小狼毫

**Comment by Ace-Who** [comment]
经过测试，可以不使用作为 reverse_lookup_translator 的 pinyin_simp 来混输拼音，而改为添加一个 pinyin 翻译器来负责混输拼音。副作用是混输的拼音候选词不会显示五笔码提示。但是仍然可以像之前一样使用引导键「`」进行拼音反查，此时使用的时 reverse_lookup_translator，所以会显示五笔码。

另一个副作用是拼音也可以自造词了。

```yaml
# wubi_pinyin.custom.yaml

patch:
  engine/segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - affix_segmentor@pinyin
    - punct_segmentor
    - fallback_segmentor
  engine/translators/@4: script_translator@pinyin
  engine/translators/@5: history_translator@history

  abc_segmentor/extra_tags: [ pinyin ]

  pinyin:
    tag: pinyin
    dictionary: pinyin_simp
    initial_quality: 0.2	

  history:
    input: z
    size: 1
```

**Comment by uoow** [comment]
@Ace-Who 最后的这个设置好像解决问题了，试用一番。
另外，最后的注意事项不太理解，这个历史记录了哪些内容？刚刚试用一下好像没什么影响

**Comment by Ace-Who** [comment]
「重复」即调用「历史输入」。

**Comment by uoow** [comment]
知道了，试了确实是，但没影响。已经够用，刚想将它作唯一输入法（因为发现了好多starcraft的主题，喜欢！开发者应该也是星际1的玩家？）就发现问题了，也有人提了Issue，在OneNote上还有兼容问题。那就再观望观望

**Comment by xiaoqun2016** [comment]
把 history_translator 放在主翻译器前面就行了
```yaml
#
patch:
  engine/translators/@before 0: history_translator
  history/input: z
```
