### ISSUE TITLE
五笔拼音 和 拼音 自动造词 不能加载的问题。

### ISSUE THREAD

**Issue by momoca** [rime/home#398]
我使用wubi_pinyin和pinyin_simp两个都有用。但我发现一个问题，在pinyin_simp中自动造词的词不会出现在wubi_pinyin的混合输入法里。这是为什么。
但自定义的拼音词库就可以出现。为什么呢？

**Comment by Ace-Who** [comment]
可能是因为 wubi_pinyin 方案里的 pinyin_simp 是以 reverse_lookup_translator 的形式存在的，所以只使用固态词典，不使用用户词典。

**Comment by momoca** [comment]
@Ace-Who  是的，我刚刚开始使用rime，这个reverse_lookup有办法解决么？

**Comment by Ace-Who** [comment]
有。我没用五笔拼音，所以仅供参考，未经测试。

```yaml
# wubi_pinyin.schema.yaml

patch:
  engine/segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - affix_segmentor@pinyin
    - punct_segmentor
    - fallback_segmentor
  engine/translators/@next: script_translator@pinyin

  abc_segmentor/extra_tags: [ pinyin ]

  pinyin:
    tag: pinyin
    dictionary: pinyin_simp
    initial_quality: 0.2	# 調整該編譯器出字優先度
```
