### ISSUE TITLE
提问：是否有限制候选非单字候选词语量的设置？

### ISSUE THREAD

**Issue by Hermittttt** [rime/home#406]
限制非单字候选词在拼音输入法里面应该是一个比较有用的选项，在输入时如果发现前一页/两页候选词中没有自己想要输入的内容，可能会更倾向于输入单字。
不知RIME目前是否有相关的设定项，如果有的话希望不吝赐教。

**Comment by Ace-Who** [comment]
应该可以通过自定义 lua_filter 实现，没有实际做过。

**Comment by Ace-Who** [comment]
```lua
-- rime.lua
limit_multi_char_word_filter = require("limit_multi_char_word")
```

```lua
-- lua//limit_multi_char_word.lua
-- limit_multi_char_word_filter: 候选项重排序，将10项以后的多字词组调序，放到末尾

local function filter(input)
  local l = {}
  local limit = 10
  local i = 0
  for cand in input:iter() do
    i = i + 1
    if i > limit and utf8.len(cand.text) > 1 then
      table.insert(l, cand)
    else
      yield(cand)
    end
  end
  for i, cand in ipairs(l) do
    yield(cand)
  end
end

return filter
```

```yaml
# 方案.custom.yaml
patch:
  engine/filters/+:
    - lua_filter@limit_multi_char_word_filter
```
