### ISSUE TITLE
仅有1输入方案时:如何配置[中文+全角+中符,英文+半角+英符]1键联动切换?

### ISSUE THREAD

**Issue by qidizi** [rime/home#417]
比如**码html场景**时,有**代码正确**+**文案符号准确**的双重需求, 
所以此时需要[中文+全角+中文符号,英文+半角+英文符号]**一键联动切换**的功能  

*  假设说我只有五笔输入一种方案话,如何配置,才可以做到如上一键切换,如 初始时 是**中文+全角+中文符号**0状态,按下shift就切换到**英文+半角+英文符号**1状态,再按一下,又回到0状态,请问,那位有了解如何配置的吗?  

* 变通方案是我配置五笔(配置成中文+全角+中文符号) 与 任何(英文+半角+英文符号)2种方案,然后通过切换方案热键来达到

**Comment by qidizi** [comment]
目前使用变通方案“自己弄个纯英文“方案来切换：　　

```
mac:build qidizi$ cat ../us_en.schema.yaml 
schema:
  schema_id: us_en
  name: 英文
  version: "0.1"
  author:
    - qidizi
  description: |
    为实现英文+半角+英文符号的变通方案

switches:
  # 需要用来重置从其它方案切换过来的初始状态
  - name: ascii_mode
    reset: 1
    states: [ 中文, 英文 ]
  - name: full_shape
    reset: 0
    states: [ 半角, 全角 ]
  - name: ascii_punct
    reset: 1
    states: [ 。，, ．， ]


engine:
  processors:
    # 只需要绑定热键切换到中文即可
    - key_binder

key_binder:
  # 使用全局热键配置
  import_preset: default

```

defaul

```


  key_binder:
    bindings:
      # 按键影射也就是组合键达到其它用途，如按ctrl+p相当于按了向上箭头键；
      # 只保留左右箭头键做为翻页（当弹出输入法菜单时有效）
      - {accept: "Left", send: Page_Up, when: has_menu}
      - {accept: "Right", send: Page_Down, when: has_menu}
      # 一键切换到英文，ｓｅｌｅｃｔ是方案的ｉｄ
      - {accept: "Control+Shift+F11", select: us_en, when: always}
      # 一键切换到中文
      - {accept: "Control+Shift+F12", select: wubi_pinyin, when: always}


```

不知道是否还有更加便捷方式来处理？
