### ISSUE TITLE
Mac OSX 10.11 Spotlight 中文输入时无法commit code转换成ascii输出

### ISSUE THREAD

**Issue by soimy** [rime/home#42]
测试发现 inline_ascii, commit_code, commit_text 均无效
相关部分配置如下：

```
ascii_composer:
  good_old_caps_lock: true
  switch_key:
    #Shift_L: inline_ascii
    Shift_L: commit_code
    Shift_R: commit_text
    Control_L: noop
    Control_R: noop
    Caps_Lock: clear
    Eisu_toggle: clear
```
