### ISSUE TITLE
求助：email模式问题，怎么匹配

### ISSUE THREAD

**Issue by ryan00zou** [rime/home#427]
在输入含有短横线和下划线的邮箱时无法自动识别成email模式
比如jo-hn@qq.com

请问应该如何设置才能像网址www.一样自动识别，谢谢。

**Comment by Ace-Who** [comment]
recognizer/patterns/email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"

**Comment by ryan00zou** [comment]
> ```
> recognizer/patterns/email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
> ```

default.yaml里的这个配置没有动，在schema.yaml里写了也不行，按短横线时 - 没反映
```
recognizer:
  import_preset: default
  patterns:
    #uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    uppercase: "" #中文状态大写锁定直接上屏
    reverse_lookup: "[a-z`]*`+[a-z`]*"
    punct: ""
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
```
