### ISSUE TITLE
有没有办法设置一个快捷键，无论当前时中文还是英文模式，强行切换到英文模式

### ISSUE THREAD

**Issue by cy18** [rime/home#454]
主要是用在Keepass密码自动输入的时候，有时候当前状态是中文，输入就会有问题。如果有办法设定一个快捷键强行切换到英文模式，就可以解决这个问题了。

**Comment by Ace-Who** [comment]
两个方法：

1. 在系统的输入法设置中添加一个「美式键盘」之类的无输入方案键盘，通过系统的输入语言热键切换到这个键盘。

2. 在 rime 中添加一个固定为 `ascii_mode` 的输入方案，通过 rime 的热键切换到这个方案，默认有几种方式可在最近两种方案之间切换：a) <kbd>Control</kbd> + <kbd>Shift</kbd> + <kbd>1</kbd>；b) <kbd>F4</kbd>, <kbd>F4</kbd>, <kbd>Space</kbd>；c) <kbd>Control</kbd> + <kbd>`</kbd>, <kbd>Control</kbd> + <kbd>`</kbd>, <kbd>Space</kbd>。

**Comment by cy18** [comment]
> 
> 
> 两个方法：
> 
>     1. 在系统的输入法设置中添加一个「美式键盘」之类的无输入方案键盘，通过系统的输入语言热键切换到这个键盘。
> 
>     2. 在 rime 中添加一个固定为 `ascii_mode` 的输入方案，通过 rime 的热键切换到这个方案，默认有几种方式可在最近两种方案之间切换：
> 
> 
>     * Control + Shift + 1
> 
>     * F4, F4, Space
> 
>     * Control + `, Control + `, Space

这方法可以，谢谢

**Comment by lotem** [comment]
有。
---

以快捷键F1为例：
``` yaml
patch:
  key_binder/bindings/+:
    - {when: composing, accept: F1, unset_option: ascii_mode}
```
