### ISSUE TITLE
怎样才能不显示使用 table_translator （例如五笔等）时，选词窗口内后选词的提示码？

### ISSUE THREAD

**Issue by Atlantis-Luna** [rime/home#460]
我试了好多办法，都没有办法去除那个提示，如图所示，谢谢~

<img width="770" alt="截屏2019-11-1418 42 36" src="https://user-images.githubusercontent.com/46293331/68854545-d30cf600-070e-11ea-99e2-38fde82aab6a.png">

**Comment by Ace-Who** [comment]
参考链接：https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md

关键词：`enable_completion`

**Comment by Atlantis-Luna** [comment]
> 参考链接：https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md
> 
> 关键词：`enable_completion`

不好意思，这个我已经看过了，但是看完了还是不知道要怎么弄，能否给个例子呢？谢谢~

**Comment by Ace-Who** [comment]
那么这样：

```yaml
# *.custom.yaml
patch:
  translator/comment_format:
    - xform/^~[a-z]+//
```
