### ISSUE TITLE
如何配置记忆具有多个备选项开关的状态

### ISSUE THREAD

**Issue by thelastlin** [rime/home#462]
例如有这样的一个开关配置：
```yaml

switches:
  - options: [gb2312,gbk,utf8]
    states: ["GB2312", "GBK", "UTF-8"]

```
发现在切换输入法状态的时候，都会自动跳到最后一个去，但是在设置选单里仍是显示选中的是原来选的选项。
要如何设置来记忆像这样的开关的状态？

--------------
OS: Windows 10 1909(18363.476)
RIME Distribution: weasel (0.14.3)
librime version: 1.5.3
