### ISSUE TITLE
可否增加 charset_filter/excluded_types 选项？

### ISSUE THREAD

**Issue by Ace-Who** [rime/home#469]
类似于 `simplifier/excluded_types`，虽然我没用过。

比如[我的方案](https://github.com/Ace-Who/rime-xuma/blob/master/schema/xuma_qshare.schema.yaml)：

```yaml
# 防止对 punct 进行过滤
gb2312:
  tags: [ abc, reverse_lookup, luna_pinyin_lookup, stroke_lookup ]
gbk:
  __include: gb2312
big5:
  __include: gb2312
```

为实现相同效果，只能将除 `punct` 之外的标签全部列出。
