### ISSUE TITLE
[Mac OS X]Intellij IDEA/PhpStorm 不能输入全角标点

### ISSUE THREAD

**Issue by hu2008yinxiang** [rime/home#47]
系统： Mac OS X El Capitan
鼠须管： 0.9.26.1

尝试了各种方案，也尝试了
```yaml
patch:
  "app_options/com.jetbrains.intellij":
    ascii_mode: false
    no_inline: false
    ascii_punct: true
```
都没用效果，无法输入中文句点感叹号逗号等全角符号，即是切换方案到全角也不行。PhpStorm也是这样
