### ISSUE TITLE
增加全局关闭输入法快捷方式

### ISSUE THREAD

**Issue by wordfeng** [rime/home#472]
在玩单机游戏的时候会弹出输入法（如Just Cause 系列）, 而在游戏中无法禁用输入法, 希望能增加一个全局控制开关, 直接一键关闭, 目前虽然也能做到, 但是操作比较麻烦。

**Comment by Ace-Who** [comment]
https://github.com/rime/home/issues/454

此外，还可在 weasel.custom.yaml 中定义：

```yaml
patch:
  app_options/<game>.exe:
    ascii_mode: true
```

来使初始状态固定为英文模式。
