### ISSUE TITLE
修改 squirrel.custom.yaml 中的 style/horizontal 值会令切换候选词的按键绑定失效

### ISSUE THREAD

**Issue by arzyu** [rime/home#481]
```yaml
# x.schema.yaml
key_binder:
  bindings:
    # Windows 10
    - { when: composing, send: Up, accept: "Control+k" }
    - { when: composing, send: Down, accept: "Control+j" }

    # macOS
    - { when: composing, send: Left, accept: "Control+k" }
    - { when: composing, send: Right, accept: "Control+j" }
```

设置切换候选词时，Windows 10 需要在 schema 配置文件中 send: Up/Down，而 macOS 要达到同样的目的需要 send: Left/Right。这样导致配置方案无法在 Windows / macOS 中通用。

另外，我也尝试将 key_binder 配置移到 `default.custom.yaml` 中，但是不起作用。

**问题补充**

经测试，修改 `squirrel.custom.yaml` 的 `style/horizontal` 会影响到上述 macOS 的按键功能，`horizontal: true` 时，macOS 切换候选词需要 send: Left/Right，当为 false 时，则需要 send: Up/Down。

修改 `weasel.costom.yaml` 中的 `style/horizontal` 值则不会影响 Windows 的对应按键功能，一律使用 send: Up/Down 来切换候选词。

按理说，修改外观配置不应当影响功能设置，所以这可能是 macOS squirrel 的问题。
