### ISSUE TITLE
punctuator配置无效

### ISSUE THREAD

**Issue by casouri** [rime/home#489]
`default.custom.yaml`里有这些配置：

```yaml
punctuator/half_shape:
  "\"": {pair: ["“", "”"]}
  "`": "`"
```

然而实际效果是：
<img width="145" alt="Screen Shot 2020-01-09 at 6 28 43 PM" src="https://user-images.githubusercontent.com/13118647/72113247-e652d100-330d-11ea-9710-b320391ce82f.png">
和
<img width="77" alt="Screen Shot 2020-01-09 at 6 28 38 PM" src="https://user-images.githubusercontent.com/13118647/72113255-ea7eee80-330d-11ea-984f-9a1ad2b2752e.png">

完整配置：
```yaml
patch:
  menu/page_size: 9
  schema_list:
    - schema: sougou_shuangpin # 只保留搜狗双拼
  switcher/fold_options: false # 不要折叠菜单
  ascii_composer/switch_key/Shift_L: commit_code # 直接上屏，切换英文
  punctuator/half_shape:
    "!": {commit: "！"}
    "\"": {pair: ["“", "”"]}
    "#": "#"
    "$": ["￥", "$", "€", "£", "¥", "¢", "¤"]
    "%": ["%", "％", "°", "℃"]
    "&": "&"
    "'": {pair: ["‘", "’"]}
    "(": "（"
    ")": "）"
    "*": ["*", "＊", "·", "・", "×", "※", "❂"]
    "+": "+"
    ",": {commit: "，"}
    "-": "-"
    .: {commit: "。"}
    "/": ["、", "/", "／", "÷"]
    ":": {commit: "："}
    ";": {commit: "；"}
    "<": ["《", "〈", "«", "‹"]
    "=": "="
    ">": ["》", "〉", "»", "›"]
    "?": {commit: "？"}
    "@": "@"
    "[": ["「", "【", "〔", "［"]
    "\\": ["、", "\\", "＼"]
    "]": ["」", "】", "〕", "］"]
    "^": {commit: "……"}
    _: "——"
    "`": "`"
    "{": ["『", "〖", "｛"]
    "|": ["·", "|", "｜", "§", "¦"]
    "}": ["』", "〗", "｝"]
    "~": ["~", "～"]
```

**Comment by lotem** [comment]
问题存在于用户自定义方案（`sougou_shuangpin`）。

**Comment by casouri** [comment]
`default.custom.yaml`不会覆盖任何自定义方案的配置吗？

**Comment by casouri** [comment]
1. 只有`default.custom.yaml`，內容爲
```yaml
patch:
  punctuator/half_shape:
    "`": "`"
    "\"": {pair: ["“", "”"]}
```
的時候：
- `：
<img width="206" alt="Screen Shot 2020-01-10 at 12 49 51 AM" src="https://user-images.githubusercontent.com/13118647/72129215-66dff480-3343-11ea-8e7c-090e961cea72.png">

- “：直接上屏


2. 只有`luna_pinyin.custom.yaml`，內容爲
```yaml
patch:
  punctuator/half_shape:
    "`": "`"
    "\"": {pair: ["“", "”"]}
```
的時候：

- `：
<img width="202" alt="Screen Shot 2020-01-10 at 12 50 17 AM" src="https://user-images.githubusercontent.com/13118647/72129254-9131b200-3343-11ea-92e5-2b9f041fd6d1.png">

- ”：直接上屏

**Comment by lotem** [comment]
> `default.custom.yaml`不会覆盖任何自定义方案的配置吗？

不會。

`default.custom.yaml` 會修改定義在 `default.yaml` 的配置。

**Comment by casouri** [comment]
那么为什么在只有`luna_pinyin.custom.yaml`的时候也不能正常工作呢?

**Comment by lotem** [comment]
圖示符合設計。

請明示您所預期的【正常工作】是怎樣的。

**Comment by casouri** [comment]
抱歉，可能我没明白文档的意思。我参考的是[这里](https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md)的文档。

我的理解是，
```yaml
patch:
  punctuator/half_shape:
    "`": "`"
```
的效果为：按下`` ` ``的时候，直接上屏，不弹出选单；

```yaml
patch:
  punctuator/half_shape:
    "\"": {pair: ["“", "”"]}
```
的效果为：按下`"`的时候，直接上屏，第一次上屏`<左引号>`，第二次上屏`<右引号>`。
另外，我也试过
```yaml
patch:
  punctuator/half_shape:
    "`": {commit: "`"}
```
我理解的效果为：直接上屏，如果已经有了输入，一起上屏。比如输入``zhongguo` ``会直接上屏``中国` ``。

请指正。

**Comment by lotem** [comment]
```yaml
patch:
  punctuator/half_shape:
    "`": "`"
```
這種寫法表示該按鍵字符唯一地轉換為 \`  符號。
`commit:` 指定上屏動作。其他情況下，是否自動上屏取決於程序裏的其他策略。例如圖示的筆畫輸入。

請修改輸入方案裏的配置。輸入方案未必引用了 `default.yaml` 裏的定義。
