### ISSUE TITLE
如何在启动ibus的时候默认进入ascii_mode

### ISSUE THREAD

**Issue by amosbird** [rime/home#49]
我配置了如下的patch写入`luna_pinyin.schema.custom.yaml`, 没有效果
```
patch:
  switches:
    - name: ascii_mode
      reset: 0
      states: [ 西文, 中文 ]
    - name: full_shape
      states: [ 半角, 全角 ]
    - name: simplification
      states: [ 汉字, 漢字 ]
    - name: ascii_punct
      states: [ .,, 。， ]

```
