### ISSUE TITLE
s2tw滤镜只实现了s2t的功能？

### ISSUE THREAD

**Issue by hyaray** [rime/home#501]
看了s2tw滤镜的json文件和txt文件，发现s2tw的原理是对s2t结果的进一步转换。
通过TWVariants.txt文件，查出"为"字的普通繁体和台湾繁体分别为：爲-為（臺灣）。
可实际使用发现和s2t的结果一样，只是把“为”字转为“爲”，难道opencc还会偷懒只执行一步？
如果把s2t和s2tw都开启，这时就可以输出台湾的“為”，但是这样，我如果打台湾繁体，还每次要开2个switch吗？
    - simplifier@s2t
    - simplifier@s2tw

**Comment by sgalal** [comment]
不應該呀

```sh
$ echo '为了' | opencc -c s2t
爲了
$ echo '为了' | opencc -c s2tw
為了
```

OpenCC 本身是正常的，是不是你的方案寫錯了

**Comment by Ace-Who** [comment]
应该是不正常。

**Comment by iDvel** [comment]
我是简体词库，用 `s2twp.json`：
```yaml
traditionalize:
  option_name: traditionalization
  opencc_config: s2twp.json
  tips: all
```
opencc 是正常的，Rime 打句子也是正常的，但是单字和两字词无法正确转换，仍然是香港繁体：
<img width="264" alt="图片" src="https://user-images.githubusercontent.com/14658234/201902600-6bc0d114-686f-4bbc-85cd-395b50bcdb31.png">
