### ISSUE TITLE
使用关闭码表的固态词典,添加用户词用无法使用

### ISSUE THREAD

**Issue by kktt007** [rime/home#505]
想请教下,我用了小鹤的固态词典,并没有dict.yaml文件,然后添加用户词典,在安卓上可以正常使用,但是linux下就不能看到用户词
```
  translators:
    - punct_translator
    - table_translator
    - lua_translator@date_translator
    - lua_translator@time_translator
    - table_translator@custom_phraseXT
    - table_translator@custom_phraseVD
    - table_translator@custom_phraseYH

custom_phraseYH:
  dictionary: ""
  user_dict: flypy_user
  db_class: stabledb
  enable_sentence: false
  enable_completion: false
  initial_quality: -1 #用户词和系统词重码居后
```

并且有flypy_uer.txt文件,但是安卓下可以使用,而linux下无法正常使用.(添加其他的输入法方案没有看到build里生成对应的文件,但是能正常使用.lua也不能使用时间功能)
