### ISSUE TITLE
當 engine/processors 中存在 ascii_composer 時, 西文時無法轉義符號

### ISSUE THREAD

**Issue by StephanoGeorge** [rime/home#525]
如小鶴雙拼中的設定:

```yaml
engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
```

當西文狀態時, 如下設定不生效:

```yaml
  punctuator:
    full_shape:
    half_shape:
      ',': ', '
```

或者我的理解有問題, 應該如何解決呢?

```
Ubuntu 19.10, rime 1.4.0, IBus 1.5.21
```
