### ISSUE TITLE
被导入码表的配置项生效问题

### ISSUE THREAD

**Issue by Ace-Who** [rime/home#534]
```yaml
# a.dict.yaml
---
name: a
sort: original
import_tables:
  - b
columns:
  ...
encoder:
  ...
...
```

那么是否 `b.dict.yaml` 中的 `columns` 是唯一生效的选项？即：

- `sort` 和 `encoder` 不生效。
- `columns` 生效。即 `b` 码表的列总是由 `b` 词典本身定义，这意味着不能以不同的列定义复用同一个码表。
