### ISSUE TITLE
Shift_L, unset_option: ascii_mode, 使用 Shift 鍵入大寫字母會導致切換中英文

### ISSUE THREAD

**Issue by Denis-Oakley** [rime/home#549]
default.custom.yaml
```yaml
patch:
  schema_list:
    - schema: double_pinyin_flypy
  punctuator:
    full_shape:
    half_shape:
      ',': ', '

  key_binder:
    bindings:
      - {accept: comma, send: Page_Up, when: paging}
      - {accept: period, send: Page_Down, when: has_menu}
      - {when: always, accept: Shift_L, unset_option: ascii_mode}
      - {when: always, accept: Shift_R, set_option: ascii_mode}

  ascii_composer:
    good_old_caps_lock: true
    switch_key:
      Caps_Lock: commit_code
      Control_R: noop
      Control_L: noop
      Shift_L: commit_code
      Shift_R: commit_code
```

double_pinyin_flypy.custom.yaml
```yaml
patch:
  switches:
    - name: simplification
      reset: 1
      states: [ 漢字, 汉字 ]

  'translator/dictionary': my

  reverse_lookup:
  recognizer:

__patch:
# Rx: emoji:customize:schema=double_pinyin_flypy {
  - patch/+:
      __include: emoji_suggestion:/patch
# }
```

在英文狀態下, 使用 Shift_L 鍵入大寫字母或符號, 會導致切換為中文, 中文下反之

```
Arch Linux
fcitx 4.2.9.7-3
fcitx-rime 0.3.2-3
```
