### ISSUE TITLE
patch代码不起作用

### ISSUE THREAD

**Issue by greymanking** [rime/home#552]
一个自定义的输入法，写了custom.yaml档，里面有：
patch:
  "speller/auto_select": false

查日志，有：
I0509 14:09:53.714964  4280 engine.cc:126] updated option: _auto_commit

但是打字仍然是无重码时直接上屏。

直接改方案的scheme.yaml文件，则能实现想要的功能。

这个custom不起作用的情况屡次遇到。我用的是小狼毫，Windows 7 64位。

**Comment by lotem** [comment]
您好。
這個功能可以正常工作。

不瞭解您的配置的具體情況。如要排查可能的配置錯誤，請檢查記錄部署操作的那部分日誌。
提醒一下，`patch:` 以下各項補丁要縮進書寫。

**Comment by greymanking** [comment]
您好。感谢快速回复。我将文件发到了您的邮箱，请您帮忙测试一下好吗？尽管功能都可以实现，但是改原文件而无法用打patch的方式，总是觉得不爽。这个问题折磨了我好几天，故冒昧向您求助。打扰了！

**Comment by Ace-Who** [comment]
可点击评论编辑框右下角 <kbd>M￬</kbd> 按钮了解 Markdown 语法。

**Comment by greymanking** [comment]
@Ace-Who 谢谢提醒。但是我确信缩进是没有问题的，我是在VS Code里面编辑的yaml文件。
这是schema.yaml文件的相关部分：

```
speller:
  auto_clear: max_length
  delimiter: "`"
  max_code_length: 4
  auto_select: true
```

这是schema.custom.yaml文件的内容：

```
patch:
  "speller/auto_select": false
```

**Comment by greymanking** [comment]
@Ace-Who 谢谢提醒。但是我确信缩进是没有问题的，我是在VS Code里面编辑的yaml文件。
这是schema.yaml文件的相关部分：

```
speller:
  auto_clear: max_length
  delimiter: "`"
  max_code_length: 4
  auto_select: true
```

这是schema.custom.yaml文件的内容：

```
patch:
  "speller/auto_select": false
```
