### ISSUE TITLE
朙月拼音香港繁體模式

### ISSUE THREAD

**Issue by LukeTu** [rime/home#561]
感謝開發者的辛勤勞動！

我注意到朙月拼音有臺灣正體的輸出模式，轉換方案則是由opencc提供。

請問可否在此基礎上加上opencc的香港繁體輸出模式？畢竟香港繁體和臺灣繁體仍有不少差異，且這些差異在拼音模式下非常容易被忽略。

本人已经把`luna_pinyin_tw.schema.yaml`下的opencc_config項改為`t2hk.json`以解決該問題。但不知道有沒有不完善的地方。現貼上代碼以供參考：

```
# Rime schema
# encoding: utf-8

schema:
  schema_id: luna_pinyin_tw
  name: 朙月拼音·臺灣正體
  version: "0.20"
  author:
    - 佛振 <chen.sst@gmail.com>
  description: |
    朙月拼音，臺灣正體字形輸出模式。

switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: ascii_punct
    states: [ 。，, ．， ]
  - name: zh_tw
    reset: 1
    # 啓用opencc字形轉換，但不在選單中顯示

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - table_translator@custom_phrase
    - script_translator
  filters:
    - simplifier
    - uniquifier

speller:
  alphabet: zyxwvutsrqponmlkjihgfedcba
  delimiter: " '"
  algebra:
    - erase/^xx$/
    - abbrev/^([a-z]).+$/$1/
    - abbrev/^([zcs]h).+$/$1/
    - derive/^([nl])ve$/$1ue/
    - derive/^([jqxy])u/$1v/
    - derive/un$/uen/
    - derive/ui$/uei/
    - derive/iu$/iou/
    - derive/([aeiou])ng$/$1gn/
    - derive/([dtngkhrzcs])o(u|ng)$/$1o/
    - derive/ong$/on/
    - derive/ao$/oa/
    - derive/([iu])a(o|ng?)$/a$1$2/

translator:
  dictionary: luna_pinyin
  prism: luna_pinyin_tw
  preedit_format:
    - xform/([nl])v/$1ü/
    - xform/([nl])ue/$1üe/
    - xform/([jqxy])v/$1u/

custom_phrase:
  dictionary: ""
  user_dict: custom_phrase
  db_class: stabledb
  enable_completion: false
  enable_sentence: false
  initial_quality: 1

simplifier:
  opencc_config: t2hk.json
  option_name: zh_tw

punctuator:
  import_preset: default

key_binder:
  import_preset: default

recognizer:
  import_preset: default

```

希望作者能在未來的版本更新中添加這個方案~
