### ISSUE TITLE
熱鍵Shift+Tab向上跳失敗 (模仿mozc缺省配置)

### ISSUE THREAD

**Issue by Un1Gfn** [rime/home#575]
Linux fcitx-rime 配置tab鍵切換候選詞，Tab可以成功向下跳，Control+Tab可以成功向上跳，**但是Shift+Tab不能向上跳**

~/.config/fcitx/rime/double_pinyin_mspy.custom.yaml

```yaml
# ~/.config/fcitx/rime/double_pinyin_mspy.custom.yaml

patch:
  punctuator/full_shape:
    '.' : [ "。" , "..." ]
  punctuator/half_shape:
    '.' : [ "。" , "..." ]
  key_binder/bindings:
    # - {accept: ISO_Left_Tab, send: Up, when: composing}
    - {accept: "Shift+Tab", send: Up, when: composing}
    - {accept: "Control+Tab", send: Up, when: composing}
    - {accept: Tab, send: Down, when: composing}
```

執行`grep -ie 'tab' ~/.config/fcitx/rime/build/double_pinyin_mspy.schema.yaml`看到實際的最終配置結果如下

```
    - {accept: ISO_Left_Tab, send: "Shift+Left", when: composing}
    - {accept: "Shift+Tab", send: "Shift+Left", when: composing}
    - {accept: Tab, send: "Shift+Right", when: composing}
    - {accept: "Shift+Tab", send: Up, when: composing}
    - {accept: "Control+Tab", send: Up, when: composing}
    - {accept: Tab, send: Down, when: composing}
```

怎樣可以配置Shift+Tab向上跳？

**Comment by Un1Gfn** [comment]
後面的回覆蓋前面的嗎？

**Comment by lotem** [comment]
> 熱鍵配置重複時，後面的會覆蓋前面的嗎？

會。

X keymap 可能把該組合鍵解釋成 `ISO_Left_Tab`.

**Comment by Un1Gfn** [comment]
已解決 感謝

```yaml
# ~/.config/fcitx/rime/double_pinyin_mspy.custom.yaml

patch:
  punctuator/full_shape:
    '.' : [ "。" , "..." ]
  punctuator/half_shape:
    '.' : [ "。" , "..." ]
  key_binder/bindings:
    # - {accept: "Control+ISO_Left_Tab", send: Up, when: composing}
    # - {accept: "Control+Tab", send: Up, when: composing}
    - {accept: "Shift+ISO_Left_Tab", send: Up, when: composing}
    - {accept: "Shift+Tab", send: Up, when: composing}
    - {accept: ISO_Left_Tab, send: Down, when: composing}
    - {accept: Tab, send: Down, when: composing}
```
