### ISSUE TITLE
請問要如何設置在 bopomofo 注音輸入法中反查漢語拼音

### ISSUE THREAD

**Issue by markwu** [rime/home#582]
目前預設的 bopomofo 注音輸入法是用倉頡來反查注音。

因為學習漢語拼音的需要，是否可以設定在候選字旁顯示拼音？

或是在地球/明月拼音中，設定為用注音來反查拼音？

**Comment by markwu** [comment]
謝謝 gitter 上 @shewer 的指導，已經成功了。加入了以下設定就可以了。

```
patch:
  # 載入擴充詞庫
  translator:
    spelling_hints: 4
    preedit_format:
      - "xlit|1qaz2wsxedcrfv5tgbyhnujm8ik,9ol.0p;/- 6347'|ㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄧㄨㄩㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦˉˊˇˋ˙ |"
```

**Comment by jk9112605** [comment]
@markwu 不好意思，我也正在學拼音。可以請教設置的細節嗎？
如果我是用地球輸入法，我要把你上述的文字貼到哪個文件呢？ 謝謝

**Comment by lotem** [comment]
> @markwu 不好意思，我也正在學拼音。可以請教設置的細節嗎？ 如果我是用地球輸入法，我要把你上述的文字貼到哪個文件呢？ 謝謝

樓主演示的是在注音輸入方案(`bopomofo`)裏顯示拼音。修改配置的補丁文件爲：
```yaml
# 文件: ${Rime用戶文件夾}/bopomofo.custom.yaml

patch:
  translator/spelling_hints: 4  # 詞中最多有幾個字才顯示拼音提示
  # 以下用以正確顯示拼音中的聲調
  translator/comment_format:
    __include: terra_pinyin.schema:/translator/comment_format
```

**Comment by lotem** [comment]
在地球拼音方案裏用大千注音反查比較棘手，因爲拼音的數字鍵選字和注音字母衝突。

**Comment by jk9112605** [comment]
謝謝回覆，我試成功了。以下分享步驟：
我的環境：win10 小狼毫 0.14.3
輸入法設定：
![image](https://user-images.githubusercontent.com/36611144/189454641-28d482a1-f621-4a55-9b35-4f3bc810fc56.png)
開啓用戶資料夾
我發現沒有bopomofo.custom.yaml，於是新增一個bopomofo.custom.yaml的檔案，並貼入以下內容
```
patch:
  translator/spelling_hints: 4  # 詞中最多有幾個字才顯示拼音提示
  # 以下用以正確顯示拼音中的聲調
  translator/comment_format:
    __include: terra_pinyin.schema:/translator/comment_format
```
再從新部署
切換到注音(Ctrl+`)就會發現後面會有拼音碼了。
![image](https://user-images.githubusercontent.com/36611144/189455483-428c62c4-8ecf-418d-804b-d37058c6dbf5.png)
感謝
