### ISSUE TITLE
请问如何重写Contorl+Return键的功能？

### ISSUE THREAD

**Issue by nb5p** [rime/home#623]
有这类需求的主要原因是很多网页和应用会检测文本框的按下Return键，导致输入内容没输入完因安回车上屏而直接触发接下来的行文，比如Github左上角的输入框。这个好像是MacOS输入法框架的问题，我咨询了一个开发输入法的朋友，他表示无法解决。

只能寻找其他代替方案，经过我的测试按组合键Contorl+Return上屏不会触发行为，所以想把Contorl+Return设置为Return键的功能

**Comment by Ace-Who** [comment]
```yaml
# *.custom.yaml
patch:
  key_binder/bindings/+:
    - { when: composing, accept: "Control+Return", send: Return }
```
