### ISSUE TITLE
使用的方案較多時，可否設定熱鍵直接跳至某個 schema？

### ISSUE THREAD

**Issue by GJRobert** [rime/home#624]
裝了臺語（臺灣閩南語）及臺灣客語的 schema 之後，我大概需要在嘸蝦米及這兩種語言之間切換；如果再考量到 IPA SAMPA 之類的，可能就再多一點。這樣的話單純 `Control+Shift+1` 在兩個 `.next` 間切換的話，可能還稍微不夠，還是得用到選單。

我可否設定直接跳至某 schema 的熱鍵？我在 default.custom.yaml 中設定下面的熱鍵但沒有作用：
```yaml
patch:
  ...
  key_binder:
    bindings:
      - { when: always, accept: Control+Shift+h, select: k_sy_g}
```
（其中 `k_sy_g` 為[臺灣客語輸入法的一個 schema](https://github.com/nienpoch/hakka_rime)）

如果我的需求是可行的，那麼應在哪個檔案，及如何設定呢？或是我有寫錯設定之處？

**Comment by lotem** [comment]
用 `Control+Shift+H`

**Comment by GJRobert** [comment]
太好了！大感謝佛振出手。把 `h` 換成大寫 `H` 後真的就奏功了。

我的 default.custom.yaml 插入了下面的段落
```yaml
patch:
  ...
  key_binder:
    bindings:
      #Directly switch schema
    - { when: always, accept: Control+Shift+H, select: k_sy_g }
    - { when: always, accept: Control+Shift+B, select: liur }
    - { when: always, accept: Control+Shift+X, select: ipa_xsampa }
    - { when: always, accept: Control+Shift+P, select: terra_pinyin }
    ...
```
但我順帶好奇的是，為什麼這邊的每一項 `- { ... }`，是跟 `bindings:` 同級呢？我以為它們是 `bindings` 的下級，結果我縮進（indent）了這些 `-{ ...}` 後，重新部署 RIME，整份 default.custom.yaml 反而都失效了。一定要變成像上面那樣，`bindings` 跟 `-{ ...}` 前面都是 4 個空格，才能成功。看來我對 YAML 語法還不太瞭解……
