### ISSUE TITLE
不知道为啥，全英文布局失灵

### ISSUE THREAD

**Issue by liuqin19980818** [rime/home#629]
使用全英文布局文件
`# luna_pinyin_simp.custom.yaml
patch:
# 指定自定义词库位置
  "translator/dictionary": luna_pinyin.my
# 标点符号全英文
  "punctuator/import_preset": alternative
# 自定义切换
    switches:
      - name: ascii_mode
        reset: 0
        states: [ "汉", "英" ]
      - name: full_shape
        states: [  "半角", "全角" ]
        reset: 0
      - name: simplification
        states: [ "繁", "简" ]
        reset: 0
      - name: ascii_punct
        states: [ "，。", ",." ]
        reset: 1`
之后在文件alternative.yaml中设置
`#alternative.yaml
#全局英文标点
punctuator:
  full_shape:
    " " : { commit: "　" }
    "," : { commit: ， }
    "." : { commit: 。 }
    "<" : [ 《, 〈, «, ‹ ]
    ">" : [ 》, 〉, », › ]
    "/" : [ 、, ／, "/", ÷ ]
    "?" : { commit: ？ }
    ";" : { commit: ； }
    ":" : ：
    "'" : { pair: [ "‘", "’" ] }
    "\"" : { pair: [ "“", "”" ] }
    "\\" : [ 、, ＼, "\\" ]
    "|" : [ ・, ｜, "|", "§", "¦" ]
    "`" : [ ｀, "`" ]
    "~" : [ 〜, "~", ～, 〰 ]
    "!" : { commit: ！ }
    "@" : [ ＠, "@", ☯ ]
    "#" : [ ＃, "#", ⌘ ]
    "%" : [ ％, "%", "°", "℃" ]
    "$" : [ ￥, "$", "€", "£", "¥", "¢", "¤" ]
    "^" : { commit: …… }
    "&" : [ ＆, "&" ]
    "*" : [ ＊, "*", ・, ×, ※, ❂, · ]
    "(" : （
    ")" : ）
    "-" : [ －, "-" ]
    "_" : ——
    "+" : [ ＋, "+" ]
    "=" : [ ＝, "=" ]
    "[" : [ 「, 【, 〔, ［ ]
    "]" : [ 」, 】, 〕, ］ ]
    "{" : [ 『, 〖, ｛ ]
    "}" : [ 』, 〗, ｝ ]
  half_shape:
    "," : { commit: "," }
    "." : { commit: "." }
    "<" : "<"
    ">" : ">"
    "/" : "/"
    "?" : { commit: "?" }
    ";" : { commit: ";" }
    ":" : { commit: ":" }
    "'" : "'"
    "\" : "\"
    "\\" : "\\"
    "|" : "|"
    "`" : "`"
    "~" : "~"
    "!" : { commit: "!" }
    "@" : "@"
    "#" : "#"
    "%" : "%"
    "$" : "$"
    "^" : "^"
    "&" : "&"
    "*" : "*"
    "(" : "("
    ")" : ")"
    "-" : "-"
    "_" : "_"
    "+" : "+"
    "=" : "="
    "[" : "["
    "]" : "]"
    "{" : "{"
    "}" : "}"
`
但是最后还是不能生效，是为什么呢

**Comment by liuqin19980818** [comment]
```yaml
# luna_pinyin_simp.custom.yaml
patch:
# 指定自定义词库位置
  "translator/dictionary": luna_pinyin.my
# 标点符号全英文
  "punctuator/import_preset": alternative
# 自定义切换
    switches:
      - name: ascii_mode
        reset: 0
        states: [ "汉", "英" ]
      - name: full_shape
        states: [  "半角", "全角" ]
        reset: 0
      - name: simplification
        states: [ "繁", "简" ]
        reset: 0
      - name: ascii_punct
        states: [ "，。", ",." ]
        reset: 1



```
```yaml


#alternative.yaml
#全局英文标点
punctuator:
  full_shape:
    " " : { commit: "　" }
    "," : { commit: ， }
    "." : { commit: 。 }
    "<" : [ 《, 〈, «, ‹ ]
    ">" : [ 》, 〉, », › ]
    "/" : [ 、, ／, "/", ÷ ]
    "?" : { commit: ？ }
    ";" : { commit: ； }
    ":" : ：
    "'" : { pair: [ "‘", "’" ] }
    "\"" : { pair: [ "“", "”" ] }
    "\\" : [ 、, ＼, "\\" ]
    "|" : [ ・, ｜, "|", "§", "¦" ]
    "`" : [ ｀, "`" ]
    "~" : [ 〜, "~", ～, 〰 ]
    "!" : { commit: ！ }
    "@" : [ ＠, "@", ☯ ]
    "#" : [ ＃, "#", ⌘ ]
    "%" : [ ％, "%", "°", "℃" ]
    "$" : [ ￥, "$", "€", "£", "¥", "¢", "¤" ]
    "^" : { commit: …… }
    "&" : [ ＆, "&" ]
    "*" : [ ＊, "*", ・, ×, ※, ❂, · ]
    "(" : （
    ")" : ）
    "-" : [ －, "-" ]
    "_" : ——
    "+" : [ ＋, "+" ]
    "=" : [ ＝, "=" ]
    "[" : [ 「, 【, 〔, ［ ]
    "]" : [ 」, 】, 〕, ］ ]
    "{" : [ 『, 〖, ｛ ]
    "}" : [ 』, 〗, ｝ ]
  half_shape:
    "," : { commit: "," }
    "." : { commit: "." }
    "<" : "<"
    ">" : ">"
    "/" : "/"
    "?" : { commit: "?" }
    ";" : { commit: ";" }
    ":" : { commit: ":" }
    "'" : "'"
    "\" : "\"
    "\\" : "\\"
    "|" : "|"
    "`" : "`"
    "~" : "~"
    "!" : { commit: "!" }
    "@" : "@"
    "#" : "#"
    "%" : "%"
    "$" : "$"
    "^" : "^"
    "&" : "&"
    "*" : "*"
    "(" : "("
    ")" : ")"
    "-" : "-"
    "_" : "_"
    "+" : "+"
    "=" : "="
    "[" : "["
    "]" : "]"
    "{" : "{"
    "}" : "}"

```
