### ISSUE TITLE
中文输入的同时，上屏显示已经输入的拼音字母？

### ISSUE THREAD

**Issue by icedcup** [rime/home#633]
在输入中文的时候，上屏一直是空白状态的，除非用空格选中了备选词，上屏才会从空白状态变成有内容的状态。

举例：

键盘敲击 nihaoa
备选框里会显示: 你好啊
**上屏是空白的**
直到我敲击了空格键
上屏会显示: 你好啊

微软默认的拼音输入法的显示逻辑如下：

键盘敲击 nihaoa
备选框里会显示: 你好啊
**上屏显示 ni'hao'a**
敲击了空格键
上屏会显示: 你好啊 （ni'hao'a会被替代）

请问可以修改成类似微软的显示方案吗？

**Comment by Ace-Who** [comment]
```yaml
# *.custom.yaml
patch:
  style/inline_preedit: true
```
