### ISSUE TITLE
如何利用i和I进入大写数字模式？

### ISSUE THREAD

**Issue by meilinxiaoxue** [rime/home#635]
文档里面可以通过自己定义标点来输入单个的中文大写数字
智能abc有两个特殊模式，通过输入i或者I进入，比如：
输入：i1w2q3b4s4
输出：一万二千三百四十四

输入：I1w2q3b4s4
输出：壹万贰仟叁佰肆拾肆

输入：1g2f3y
输出：一个二分三月

在i或者I模式下，数字分别是 一二三四五六七八九○ 和 壹贰叁肆伍陆柒捌玖零，其他字母在此模式也
有特定的输出

不知是否可以通过设置实现以上功能？

**Comment by lotem** [comment]
大概可以在`recognizer`里配置匹配规则，用`affix_segmentor`把`i`定义成数字模式的前缀，后面的部分用一个专门的`script_translator`查码表转换。

**Comment by meilinxiaoxue** [comment]
我写了一个luna_pinyin_simp_custom.yaml如下:
patch:
        "engine/segmentors/@before 2": affix_segmentor@abcnum 
        "engine/translators/@next": script_translator@abcnum
        "recognizer/patterns/abcnum": "^i[0-9]*$"
        "abcnum/tag": abcnum
        "abcnum/dictionary": abcnum
        "abcnum/prefix": "i"
        "abcnum/suffix": "$"
        "abcnum/tips": "i mode"

abcnum.dict.yaml如下:

---
name: abcnum
version: "1"
sort: original
use_preset_vocabulary: true
...

一    1
二    2
三    3

==================================
按照我的理解:
1.recgonizer将i开头的输入标记为abcnum;
2.然后送到affix_segmentor@abcnum中按照prefix和suffix
  的设置,把i和$去掉
3.步骤2剩下的段落送到script_translator@abcnum中查找
  abcnum.dict.yaml输出结果. 

按照这样设置,输入i会提示进入"i mode",但是输入的数字无法转换为汉字是什么问题呢?
谢谢

**Comment by lotem** [comment]
是不是没有生成词典？
部署器只做方案里的主词典，就是`translator/dictionary`所定义的那个。
可以另写一个方案文件用来部署这个数字词典。

**Comment by meilinxiaoxue** [comment]
多谢回复，我检查了下，用户词典列表里面有abcnum，但是导出的时候记录却为0，luna_pinyin的导出是正常的。
看来确实是没有正常生成词典，这种情况除了另外写个方案以外还有别的办法手动生成么？
谢谢

**Comment by functoreality** [comment]
> 多谢回复，我检查了下，用户词典列表里面有abcnum，但是导出的时候记录却为0，luna_pinyin的导出是正常的。
> 看来确实是没有正常生成词典，这种情况除了另外写个方案以外还有别的办法手动生成么？
> 谢谢

用用户词典而不是固态词典，即词典文件使用 `abcnum.txt` 而非 `abcnum.dict.yaml`，文件里也不需要 YAML 的文件头。输入方案相关配置如下（前四行并没有改）
```yaml
patch:
"engine/segmentors/@before 2": affix_segmentor@abcnum
"engine/translators/@next": script_translator@abcnum
"recognizer/patterns/abcnum": "^i[0-9]*$"
abcnum:
  dictionary: ""
  user_dict: abcnum
  tag: abcnum
  prefix: "i"
  suffix: "$"
  tips: "i mode"
  db_class: stabledb
  enable_completion: false
  enable_sentence: true
  initial_quality: 1
```
我自己用这个办法写了一个临时大写的方案，`au` 唤起，这样像输入 GNU 之类的缩写不需要按大写锁定。原则上应该能够迁移到这个 issue 的需求。
