### ISSUE TITLE
default.custom.yaml無法修改key_binder

### ISSUE THREAD

**Issue by semizemi** [rime/home#656]
```
patch:
  key_binder:
    bindings:
    - { when: composing, accept: Control+c, send: Escape }
```

```
patch:
  key_binder:
    bindings:
      - { when: composing, accept: Control+c, send: Escape }
```

```
patch:
  key_binder:
    bindings:
      - { when: composing, accept: "Control+c", send: Escape }
```

重新部署，完全無效。求解。
系統：Windows10 20H2。小狼毫版本：0.14.3.0
