### ISSUE TITLE
RIME自帶的“倉頡五代”输入简体时，能否改善相关的提示信息。

### ISSUE THREAD

**Issue by VimWei** [rime/home#665]
目前，我使用RIME自帶的“倉頡五代”：
若想輸入“臺灣/台湾”，可以按照繁體的筆畫“臺灣”進行拆字，也可以按照簡體的筆畫“台湾”進行拆字；
但若想输入“理論/理论”，我只能按照繁體的筆畫“理論”才能輸入。

請問，是否有可能類似與“臺灣/台湾”那樣，讓所有的簡體字，都按照其自身的書寫筆畫進行拆字輸入嗎？需要改造哪些關鍵環節呢？

**Comment by VimWei** [comment]
理论 也可以输入  mgwg ivop

**Comment by VimWei** [comment]
但是 输入论的拼音 lun 作为提示时，只是提示：论〔論〕。

请问：这个提示能否改造为 直接提示 论〔ivop / 戈女人心〕？

**Comment by LEOYoon-Tsaw** [comment]
得用明月拼音·簡化字反查方可

**Comment by VimWei** [comment]
感谢！我改用了双拼用来提醒了！

**Comment by VimWei** [comment]
**我的设置主要是取消simplifier，这样简繁体的字就不会合并，配置供后来人參考：**
```
patch:
  simplifier: {}
```

**若希望简体中文的排序靠前，以及使用双拼等其他输入法作为反查，可以配置如下：**
```
patch:
  # schema/dependencies: double_pinyin_flypy
  # reverse_lookup/dictionary: vimwei
  # reverse_lookup/prism: double_pinyin_flypy
  # reverse_lookup/tips: 〔小鹤双拼〕

  schema/dependencies: luna_pinyin_simp
  reverse_lookup/dictionary: vimwei
  reverse_lookup/prism: luna_pinyin_simp
  reverse_lookup/tips: 〔明月拼音〕

  switches:
    - name: ascii_mode
      reset: 0
      states: [ 中文, 西文 ]
    - name: full_shape
      states: [ 半角, 全角 ]
    # - name: simplification
    #   states: [ 汉字, 漢字 ]
    - name: extended_charset
      states: [ 常用, 增廣 ]
    - name: ascii_punct
      states: [ 。，, ．， ]

  simplifier: {}
    # option_name: simplification
    # opencc_config: s2t.json
```
