### ISSUE TITLE
鼠须管在Mac自带终端下无法输入中文

### ISSUE THREAD

**Issue by Disciplining** [rime/home#694]
### 环境
现在的时间：2021-02-05
电脑系统：macOS Catalina 10.15.7
鼠须管版本：0.14.0

### 配置文件
已按照`https://github.com/rime/home/wiki/CustomizationGuide#%E5%9C%A8%E7%89%B9%E5%AE%9A%E7%A8%8B%E5%BA%8F%E8%A3%8F%E9%97%9C%E9%96%89%E4%B8%AD%E6%96%87%E8%BC%B8%E5%85%A5`配置
```yaml
# /Users/lyx/Library/Rime/default.custom.yaml
patch:
  app_options/com.apple.Terminal: {}
  app_options/com.microsoft.VSCode: {}
  schema_list:
    - schema: wubi86
```
### 这样配置之后的效果
- 在VSCode中按`control+shift+2`后可以输入中文.
- 但在Mac自带的终端中不论按不按这组快捷键还是无法输入中文.

**Comment by lotem** [comment]
设为

```yaml
# squirrel.custom.yaml
patch:
  app_options/com.apple.Terminal: {}
  app_options/com.microsoft.VSCode: {}
```
