### ISSUE TITLE
rime.im should support dark mode

### ISSUE THREAD

**Issue by LEOYoon-Tsaw** [rime/home#695]
Add these code to style to support dark mode
```css
/* Inline table in donation*/
@media (prefers-color-scheme: dark) {
  table tr { border-top: 1px solid #333333; background-color: black; margin: 0; padding: 0; }
  table tr:nth-child(2n) { background-color: #080808; }
  table tr th { font-weight: bold; border: 1px solid #333333; margin: 0; padding: 6px 13px; }
  table tr td { border: 1px solid #333333; margin: 0; padding: 6px 13px; }
}

/* style.css */
@media (prefers-color-scheme: dark) {
  body {
    background-color: #000;
  color: #aabbc0;
  }
  .downloads {
  background-color: #0f0f0f;
  }
  .user-quotes {
    background-color: #0f0f0f;
  }
  .home hr {
    border-color: #0f0f0f;
  }
  #sidebar {
    border-left: 1px solid #1f1f1f;
  }
  .widget {
    border-bottom: 1px solid #1f1f1f;
  }
  .has-success .form-control,
  .has-success .form-control:focus {
    background-color: #000;
  }
}

/* highlights.css */
@media (prefers-color-scheme: dark) {
  code {
    background: #111;
    border: 1px solid #1a1a1a;
    text-shadow: 0 1px #000;
  }
}

/* bootstrap.flatly.min.css */
@media (prefers-color-scheme: dark) {
  .panel {
    background-color: #000 !important;
  }
  .panel-default {
    border-color: #0e1013 !important;
  }
  .mypage > .panel-default > .panel-heading {
    border-bottom: 1px solid #0e1013 !important;
  }
  .mypage > .panel-default > .panel-heading:not(:first-child) {
    border-top: 1px solid #0e1013 !important;
  }
}
```
