### ISSUE TITLE
关于以数字键小键盘为输入方式的纵横码配置

### ISSUE THREAD

**Issue by Spico197** [rime/home#717]
大家好，我最近在看[纵横码](http://ckcsys.com/)输入法的相关内容，官方的软件版本太陈旧了，我想以rime为基础配置出新的纵横码输入法软件。我阅读了rime配置的相关文档和其它的教程，但是仍然遇到了一些困难，我不确定是否可以仅通过修改配置文件的方式达到该目的。

纵横码特点：
- 以字形为依据，采用码表查找方式进行检索；
- 以小键盘的数字为输入方式，不同的数字代表了不同的字形内容，每个汉字由1-4个数字组成，[这里是大概介绍](http://ckcsys.com/teach/guide-to-ckc.html)；
- 键盘其它区域仍可正常输入英文字母，不影响使用；
- 由于是以字形为编码方式，简繁体理论上可以混用输入。

目前情况及进展：
- 目前使用windows下的weasel开发版进行调试；
- 已经获得了2万多个字的码表，词组码表正在准备中。

目前遇到的问题：
- 如何区分键盘字母区上方的数字键和小键盘区域的数字键？使用 `key_binder` processor可以区分该按键，但我写的如下配置不能达到我的目的：`{accept: KP_0, send: 0, when: always}`；
- 由于使用数字键作为输入，在确定上屏字词时希望使用字母键作为候选的选择键，例如使用“qwerty”代替“123456”；
- 使用小键盘区域的“.“作为后退删除键，”NumLock“作为”万能键“。”万能键“相当于通配符中的”?“或正则表达式中的”.“，用以检索码表时做模糊匹配处理。

以上是我遇到的问题和问题发生的背景，希望大家可以提供一些思路或参考意见。谢谢~

当前的配置文件如下，未实现小键盘数字键区分功能，未实现万能键功能，未实现自定义后退键：
schema：
```yaml
schema:
  schema_id: zhhz_numpad_simple
  name: 纵横码简体字小键盘版
  version: "0.1.0"
  author:
    - Tong <tzhu1997@outlook.com>
  description: |
    纵横码输入法简体小键盘方案。

switches:
  - name: full_shape
    states: ["半角", "全角"]
    reset: 0
  - name: ascii_punct
    states: ["符號", "句讀"]
  - name: gbk
    states: ["增廣", "常用"]
    reset: 0

engine:                    # 輸入引擎設定，即掛接組件的「處方」
  processors:              # 一、這批組件處理各類按鍵消息
    - speller              # ※ 拼寫處理器，接受字符按鍵，編輯輸入碼
    - key_binder           # ※ 在特定條件下將按鍵綁定到其他按鍵，如重定義逗號、句號爲候選翻頁鍵
    - selector             # ※ 選字處理器，處理數字選字鍵、上、下候選定位、換頁鍵
    - navigator            # ※ 處理輸入欄內的光標移動鍵
    - express_editor       # ※ 編輯器，處理空格、回車上屏、回退鍵等
  segmentors:              # 二、這批組件識別不同內容類型，將輸入碼分段
    - abc_segmentor       # 標記輸入碼的類型
    - fallback_segmentor   # ※ 標識其他未標識段落
  translators:             # 三、這批組件翻譯特定類型的編碼段爲一組候選文字
    - echo_translator      # ※ 沒有其他候選字時，回顯輸入碼
    - table_translator

speller:
  alphabet: "1234567890"

key_binder:
  import_preset: default 
  bindings:
    - {accept: KP_0, send: 0, when: always}
    - {accept: KP_1, send: 1, when: always}
    - {accept: KP_2, send: 2, when: always}
    - {accept: KP_3, send: 3, when: always}
    - {accept: KP_4, send: 4, when: always}
    - {accept: KP_5, send: 5, when: always}
    - {accept: KP_6, send: 6, when: always}
    - {accept: KP_7, send: 7, when: always}
    - {accept: KP_8, send: 8, when: always}
    - {accept: KP_9, send: 9, when: always}

translator:
  dictionary: zhhz

```

dict:

```yaml
# 纵横码输入法字词表

---
name: zhhz
version: "0.1.0"
sort: by_weight
use_preset_vocabulary: true
...

鬷	1224
下	123
```

**Comment by Spico197** [comment]
当前的配置文件如下，未实现小键盘数字键区分功能，未实现万能键功能，未实现自定义后退键：
schema：
```yaml
schema:
  schema_id: zhhz_numpad_simple
  name: 纵横码简体字小键盘版
  version: "0.1.0"
  author:
    - Tong <tzhu1997@outlook.com>
  description: |
    纵横码输入法简体小键盘方案。

switches:
  - name: full_shape
    states: ["半角", "全角"]
    reset: 0
  - name: ascii_punct
    states: ["符號", "句讀"]
  - name: gbk
    states: ["增廣", "常用"]
    reset: 0

engine:                    # 輸入引擎設定，即掛接組件的「處方」
  processors:              # 一、這批組件處理各類按鍵消息
    - editor
    - speller              # ※ 拼寫處理器，接受字符按鍵，編輯輸入碼
    - key_binder           # ※ 在特定條件下將按鍵綁定到其他按鍵，如重定義逗號、句號爲候選翻頁鍵
    - selector             # ※ 選字處理器，處理數字選字鍵、上、下候選定位、換頁鍵
    - navigator            # ※ 處理輸入欄內的光標移動鍵
    - express_editor       # ※ 編輯器，處理空格、回車上屏、回退鍵等
  segmentors:              # 二、這批組件識別不同內容類型，將輸入碼分段
    - abc_segmentor       # 標記輸入碼的類型
    - fallback_segmentor   # ※ 標識其他未標識段落
  translators:             # 三、這批組件翻譯特定類型的編碼段爲一組候選文字
    - echo_translator      # ※ 沒有其他候選字時，回顯輸入碼
    - table_translator

speller:
  alphabet: "1234567890"

key_binder:
  import_preset: default 
  bindings:
    - {accept: KP_0, send: 0, when: always}
    - {accept: KP_1, send: 1, when: always}
    - {accept: KP_2, send: 2, when: always}
    - {accept: KP_3, send: 3, when: always}
    - {accept: KP_4, send: 4, when: always}
    - {accept: KP_5, send: 5, when: always}
    - {accept: KP_6, send: 6, when: always}
    - {accept: KP_7, send: 7, when: always}
    - {accept: KP_8, send: 8, when: always}
    - {accept: KP_9, send: 9, when: always}

translator:
  dictionary: zhhz

```

dict:

```yaml
# 纵横码输入法字词表

---
name: zhhz
version: "0.1.0"
sort: by_weight
use_preset_vocabulary: true
...

鬷	1224
下	123
```
