### ISSUE TITLE
mac 默认英文的问题

### ISSUE THREAD

**Issue by northleafup** [rime/home#72]
您好，我在squirrel.yaml文件中添加了以下的配置：
```yaml
app_options:
  com.alfredapp.Alfred:
    ascii_mode: true
  com.runningwithcrayons.Alfred-2:
    ascii_mode: true
```
据我所知，这个配置就是让alfred应用程序默认为英文输入的，第一次我按alt+空格，呼出alfred后，输入一些英文，再按shift 切换成中文，输入几个汉字，那为什么我下一次呼出alt+空格时，输入的还是中文呢，请问这种情况如何处理。
