### ISSUE TITLE
rime和notion的快捷键冲突

### ISSUE THREAD

**Issue by francis707** [rime/home#754]
notion有以下快捷键：
```
- Press `cmd/ctrl` + `option/shift` + `0` to create text.
- Press `cmd/ctrl` + `option/shift` + `1` to create an H1 heading.
- Press `cmd/ctrl` + `option/shift` + `2` to create an H2 heading.
- Press `cmd/ctrl` + `option/shift` + `3` to create an H3 heading.
- Press `cmd/ctrl` + `option/shift` + `4` to create a to-do checkbox.
- Press `cmd/ctrl` + `option/shift` + `5` to create a bulleted list.
- Press `cmd/ctrl` + `option/shift` + `6`  to create a numbered list.
- Press `cmd/ctrl` + `option/shift` + `7` to create a toggle list.
- Press `cmd/ctrl` + `option/shift` + `8` to create a code block - which looks like this:
```

但是rime的默认配置中有以下配置：
```yaml
key_binder:
  bindings:
     - {accept: "Control+Shift+1", select: .next, when: always}
     - {accept: "Control+Shift+2", toggle: ascii_mode, when: always}
     - {accept: "Control+Shift+3", toggle: full_shape, when: always}
     - {accept: "Control+Shift+4", toggle: simplification, when: always}
     - {accept: "Control+Shift+5", toggle: extended_charset, when: always}
```

目前找到的解决方法如下：
在`default.custom.yaml`中添加以下patch，
```yaml
patch:
  key_binder/bindings: 
    - {accept: "Control+Shift+1", noop, when: always} # 覆盖rime的默认配置，使rime不占用该快捷键
    - {accept: "Control+Shift+2", noop, when: always} # 覆盖rime的默认配置，使rime不占用该快捷键
    - {accept: "Control+Shift+3", noop, when: always} # 覆盖rime的默认配置，使rime不占用该快捷键
    - {accept: "Control+Shift+4", noop, when: always} # 覆盖rime的默认配置，使rime不占用该快捷键
    - {accept: "Control+Shift+5", noop, when: always} # 覆盖rime的默认配置，使rime不占用该快捷键
```
在`luna_pinyin_simp.custom.yaml`中添加以下patch，
```yaml
patch:
  key_binder/bindings: 
    - {accept: "Control+Shift+4", noop, when: always}  # 覆盖rime的默认配置，使rime不占用该快捷键
    - {accept: Control+Shift+dollar, noop, when: always} # 覆盖rime的默认配置，使rime不占用该快捷键
```
然后重新部署

-----
好象在官方文档中没有看到关于快捷键冲突的解决方法，
不知道有没有其他方法，能不能直接 `deny` 或 `disable` 某个快捷键，覆盖默认配置，释放出这个快捷键？

**Comment by Ace-Who** [comment]
```yaml
patch:
# 为替换整个 key_binder 节点，不能写成 'key_binder/bindings'
  key_binder:
    bindings:
      __patch:
        - key_bindings:/emacs_editing
        - key_bindings:/move_by_word_with_tab
        - key_bindings:/paging_with_minus_equal
        - key_bindings:/paging_with_comma_period
        # - key_bindings:/numbered_mode_switch  # 所涉按键绑定为这一组
```

**Comment by francis707** [comment]
@Ace-Who 谢谢，确实有效

替换整个节点这种写法之前没看到过，好象在官方文档里面没有？
我在这两个官方文档里找了，好象没找到：
[CustomizationGuide](https://github.com/rime/home/wiki/CustomizationGuide)
[RimeWithSchemata](https://github.com/rime/home/wiki/RimeWithSchemata)

然后后面那几个斜杠后面的名称我在 `rime安装目录\data\key_bindings.yaml` 里面找到了对应的名称，
但是 `__patch` 这种写法好象在官方文档里面也没有，可以麻烦告知哪里可以看到更详细的文档吗？

**Comment by francis707** [comment]
但是 `luna_pinyin_simp.custom.yaml` 中的patch还是需要的，
```
patch:
  key_binder/bindings: 
    - {accept: "Control+Shift+4", noop, when: always}  # 覆盖rime的默认配置，使rime不占用该快捷键
    - {accept: Control+Shift+dollar, noop, when: always} # 禁用小狼毫的快捷键，和notion快捷键冲突
```
因为在 `rime安装目录\data\luna_pinyin_simp.schema.yaml` 中有以下默认配置：
```
key_binder:
  import_preset: default
  bindings:
    - { when: always, accept: Control+Shift+4, toggle: zh_simp }
    - { when: always, accept: Control+Shift+dollar, toggle: zh_simp }
```

**Comment by Ace-Who** [comment]
上面的补丁就是 `luna_pinyin_simp.custom.yaml` 的内容，修改后该方案的按键绑定设置就与 `default` 脱钩了，可以不管 `default.custom.yaml` 了。
参考 https://github.com/rime/home/wiki/Configuration

**Comment by Ace-Who** [comment]
虽然你可能还没想到，但是上面的补丁带来一个问题——如何在此基础上添加按键绑定？方法如下：

```yaml
# luna_pinyin_simp.custom.yaml
patch:
  # 替换 key_binder 节点，而不止是 'key_binder/bindings' 节点
  key_binder:
    bindings:
      __patch:
        - key_bindings:/emacs_editing
        - key_bindings:/move_by_word_with_tab
        - key_bindings:/paging_with_minus_equal
        - key_bindings:/paging_with_comma_period
        # - key_bindings:/numbered_mode_switch  # 所涉按键绑定为这一组
        - key_bindings  # 额外添加一组，定义在下面。注意无冒号，表示本文件内的节点。
        - my_key_bindings:/some_bindings  # 也可添加定义在其他文件中的按键绑定。

# 存放额外的按键绑定，只有被 __patch 指令引用时才生效。该节点名称可任意选取，与同名文件 `key_bindings` 没有关系。
key_bindings:
  - { when: ... }
  - { when: ... }
  ...
```

```yaml
# my_key_bindings.yaml
some_bindings:
  - { ... }
  - { ... }
  ...
```
