### ISSUE TITLE
Rime的快捷键是怎么用的？

### ISSUE THREAD

**Issue by boboIqiqi** [rime/home#80]
最后一个问题。

我看key_binding里面定义了很多快捷键， 
Ctrl+shift+2切换到英文
Shift+Space切换全角/半角

为什么我按起来就没有反应呀？我现在在输入中文，然后按了一下 Ctrl+shift+2还是中文。
。。。按一下Shift+space。。。后面的符号还是全角

**Comment by xiaoqun2016** [comment]
检查一下所用方案的schema中有没有这句：   
```yaml
key_binder:
  import_preset: default
```

**Comment by boboIqiqi** [comment]
@xiaoqun2016 老师好.
不好意思,可能是我上次看错了.也可能是别的原因.

我想实现的就是在中文模式下输入英文符号. 然后,我参考前面佛振老大回复的一个帖子.做好了.
[请问小狼毫如何设定西文标点](http://tieba.baidu.com/p/1748128802)

现在我的default.yaml下面的所有快捷键都有效了. 比如对编码的编辑, Ctrl+e,Ctrl+A等等
ctrl+g = ESC 

我检查了wubi86.schema.yaml文件里面是有这个定义的.
```yaml
key_binder:
  import_preset: default
punctuator:
  import_preset: default
```
我再研究一下,看看原来到底是什么原因.再次感谢xiaoqun老师

**Comment by xiaoqun2016** [comment]
在中文模式用英文标点也可以加开关的：  
```yaml
  - name: ascii_punct
    states: [ 。，, ．， ]
    reset: 1
```
好处是：当你想用中文标点时可以一键切换回来。

**Comment by chs513** [comment]
@xiaoqun2016 
`  - name: ascii_punct
    states: [ 。，, ．， ]
    reset: 1`

你说的这个设置方法具体是操作哪个配置文件啊.

我想要的效果是: 1. 默认情况下, 中文输入法用的是英文标点; 2. 可以用快捷键来回切换中英文标点, 以备不时之需. 现在第 1 个效果实现了, 不知道第 2 个咋实现. 参考的是: [https://gist.github.com/lotem/2334409](url)

**Comment by chs513** [comment]
@xiaoqun2016 
我用的是五笔拼音，我在 `wubi_pinyin.custom.yaml `文件中加入以下内容。可以用 `Ctrl `+ `.` 来切换中英文标点，但默认是中文标点。咋解决哦？

```
patch:
     switches:
        - name: ascii_punct
            states: [ 。，, ．， ]
            reset: 1
```

**Comment by qyin** [comment]
@xiaoqun2016 正好解决我想问的,谢谢!

**Comment by boboIqiqi** [comment]
好久的issue了没想到 @xiaoqun2016 老师的回答还能帮助到这么多Rime爱好者。也好久没见 @xiaoqun2016 了

**Comment by tenhow** [comment]
感谢

**Comment by jcleng** [comment]
> 默认使用英文标点，是在schema里面设置的，类似这样：https://github.com/rime/rime-pinyin-simp/blob/master/pinyin_simp.schema.yaml#L21-L22 ，还要加上`reset: 1`
> 
> 默认的快捷键是 Ctrl + . ：
> `{ when: always, accept: Control+period, toggle: ascii_punct }` 也可以自定义。
> 
> gist里面那个方法已经过时了，没必要那样做。

给后来者一个参考,一个简单的便捷的配置：
`/Users/jcleng/Library/Rime/default.custom.yaml`

```yaml
patch:
  menu/page_size: 9 # 输入框待选项个数
  ascii_composer/switch_key:  # ctrl&&shift 切换键效果
    Caps_Lock: clear # 清屏幕
    Shift_L: commit_code # 上档code
    Control_L: noop # 不处理
    Shift_R: inline_ascii # 切换字符不上档
    Control_R: noop # 不处理
  key_binder:
    bindings:
      - { when: composing, accept: Control+c, send: Escape } # ctrl-c 清屏
      - { when: composing, accept: Control+p, send: Page_Up } # 候选词分页
      - { when: composing, accept: Control+n, send: Page_Down } # 候选词分页
      - { when: always, accept: Control+period, toggle: ascii_punct } # 切换西文/中文标点 Ctrl + .
```

**Comment by loggerhead** [comment]
想把 ctrl 相关的快捷键全部禁用，其它的快捷键保留，需要怎么配置呢？找到一个 `/Users/foo/Library/Rime/build/default.yaml` 文件，但是修改它再 deploy 以后文件又被覆盖了，似乎它是从某个地方生成的

**Comment by loggerhead** [comment]
参考 https://xinlu.ink/tech/rime.html，如果快捷键与 vscode 冲突，可以修改 `default.custom.yaml` 文件的 `patch` 下把 hotkey 改掉（注意复制 `/Library/Input Methods/Squirrel.app/Contents/SharedSupport/default.yaml` 的 `switcher`，只修改 `hotkeys`，`patch` 会覆盖整个 `switcher`）：

```yaml
patch:
  switcher:
    caption: 〔方案選單〕
    hotkeys:
      - Control+Shift+F12
```
