### ISSUE TITLE
阅读设计书有几点小疑问,求解答

### ISSUE THREAD

**Issue by boboIqiqi** [rime/home#82]
终于到周末了,满怀崇敬,又认真了重读了一遍wiki里,佛振老大的写的 Rime设计书.
有两个问题我没试出来.

## 1.通过下标给列表打patch

```yaml
patch:
  "一級設定項/二級設定項/三級設定項": 新的設定值
  "另一個設定項": 新的設定值
  "再一個設定項": 新的設定值
  "含列表的設定項/@0": 列表第一個元素新的設定值
  "含列表的設定項/@last": 列表最後一個元素新的設定值
  "含列表的設定項/@before 0": 在列表第一個元素之前插入新的設定值（不建議在補靪中使用）
  "含列表的設定項/@after last": 在列表最後一個元素之後插入新的設定值（不建議在補靪中使用）
  "含列表的設定項/@next": 在列表最後一個元素之後插入新的設定值（不建議在補靪中使用）
```

请问为什么有的"不建议在补丁中使用"? 我感觉这个功能还挺强大的.
当然,这不是重点,重点是,我试了一下用@0或者@last也不行.
下面是佛振老大教程中给出的例子,我想通过打patch实现.

```yaml
#hello.schema.yaml
schema:
  schema_id: hello
  name: 大家好
engine:
  processors:
    - speller          # 把字母追加到編碼串
    - speller
  segmentors:
    - fallback_segmentor
  translators:
    - echo_translator  # （無有其他結果時，）創建一個與編碼串一個模樣的候選項
```

```yaml
patch:
  "engine/processors/@1": express_editor
```yaml

但是deploy时会出错:

```
[Sun May 15 16:47:40 2016] config.cc           (00411) rime::ConfigData::LoadFromFile():  loading config file 'D:\Users\Bob\AppData\Roaming\Rime\hello.custom.yaml'.
[Sun May 15 16:47:40 2016] config.cc           (00316) rime::Config::SetItem():  key = 'engine/processors/@after last'
[Sun May 15 16:47:40 2016] customizer.cc       (00136) rime::Customizer::UpdateConfigFile():  Error applying customization item: 'engine/processors/@after last'.
```
换成@0,@last,@1都不可以
按照@xiaoqun2016 老师的指导,我在同文输入法中通过下标打过patch,是没有问题的.难道是我的小狼毫版本太低吗?
我是在百度默认搜索出来,下载的 0.9.14

## 2.有个例子好像是笔误吧

```yaml
# Rime schema
# encoding: utf-8
#
# 最簡單的 Rime 輸入方案
#

schema:
  schema_id: hello    # 注意此ID與文件名裏 .schema.yaml 之前的部分相同
  name: 大家好        # 將在〔方案選單〕中顯示
  version: "2"        # 這是文字類型而非整數或小數，如 "1.2.3"

engine:
  processors:
    - fluid_editor
  segmentors:
    - fallback_segmentor
```
下面的说明是:
>fluid_editor 將字符按鍵記入輸入上下文，fallback_segmentor 將輸入碼連綴成一段。於是重新佈署後，按下字符鍵不再直接上屏，而顯示爲輸入碼。

>你會發現，該輸入法只是收集了鍵盤上的可打印字符，並於按下空格、回車鍵時令輸入碼上屏。

但是,我试了一下,还是只能输入英文,而且是直接上屏.
难道跟我的default.yaml或者 weasel.yaml中的其他设置有关吗?

我照着做的时候,直到下一步, 改用 speller + express_editor 的組合取代 fluid_editor,才出现把字母按键记入编码区?前一步,一直是直接上屏的.

求解答...
我是不是该发到帖吧里?但是帖吧的格式太丑了....
