### ISSUE TITLE
如何实现中文输入模式下输入英文字母或数字后，紧接输入的标点为自动变为英文标点？

### ISSUE THREAD

**Issue by huruojin** [rime/home#834]
如何实现中文输入模式下输入英文字母或数字后，紧接输入的标点为自动变为英文标点？

**Comment by Ace-Who** [comment]
不能通过配置实现，修改源程序可以应该可以实现，最新 lua 插件大概也可以。现在的程序行为是数字后的句号和冒号自动转为英文，且不可配置。

**Comment by arpcn** [comment]
文字校對、加標點等工作中，因爲不是連續輸入，在輸句號前，常常不記得之前是否輸入過數字。此時需要準確輸入句號有一點麻煩，在谷歌拼音和搜狗拼音中有數字後的句點是否以小數點呈現的選項，不知rime中能不能加入這樣的選項啊。或者，通過lua可不可以加一個這樣的選項？謝謝！

**Comment by LightAPIs** [comment]
> 文字校對、加標點等工作中，因爲不是連續輸入，在輸句號前，常常不記得之前是否輸入過數字。此時需要準確輸入句號有一點麻煩，在谷歌拼音和搜狗拼音中有數字後的句點是否以小數點呈現的選項，不知rime中能不能加入這樣的選項啊。或者，通過lua可不可以加一個這樣的選項？謝謝！

分享一个我自己使用 lua 实现的方法吧。

---

**lua 函数：**

```lua
function dis_auto_conversion_processor(key_event, env)
  -- 禁用数字后的句号/冒号自动自动转为英文标点
  local keycode = key_event.keycode
  local dis_conversion = env.engine.context:get_option("dis_conversion")
  if (dis_conversion and (keycode == 46 or keycode == 59)) then
    -- keycode: 句号=46|冒号=59

    if (not key_event:release()) then
      local ascii_punct = env.engine.context:get_option("ascii_punct")

      if (ascii_punct) then
        if (keycode == 46) then
          env.engine:commit_text(".")
        elseif (keycode == 59) then
          env.engine:commit_text(";")
        end
      else
        if (keycode == 46) then
          env.engine:commit_text("。")
        elseif (keycode == 59) then
          env.engine:commit_text("；")
        end
      end
    end
    
    -- 1 表示 `kAccepted`; 字符不上屏，结束 processors 流程
    return 1
  end
end
```

**配置：**

```yaml
# *.schema.yaml
# ...
switches:
  - name: ascii_punct
    reset: 0
    states: ['，。', '，．']
  - name: dis_conversion # 自动转换标点
    reset: 1
    states: ['启用转换', '禁用转换']
# ...
engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - lua_processor@dis_auto_conversion_processor # 该 lua_processor 需在 punctuator 之前
    - punctuator
    - selector
    - navigator
    - express_editor
# ...
# 可选，快捷键配置
key_binder:
  bindings:
    - { when: always, accept: 'Control+F7', toggle: dis_conversion } # 自动转换标点切换
# ...
```
