### ISSUE TITLE
key_binder 是否能够绑定快捷键序列

### ISSUE THREAD

**Issue by functoreality** [rime/home#837]
目前的文档说明里，`key_binder/bindings` 选项设置的按键映射似乎只能把一个快捷键翻译成单独的另一个，而不能达到模拟“多个快捷键相继按下”的效果。我希望知道这种功能在目前的版本里是否能够通过设置实现。
例如，仿照 Trime 设置软键盘按键功能的语法，我希望进行如下的设置（应该不难看懂）：
```yaml
key_binder:
  bindings:
    - { when: composing, accept: Control+2, send: '{Home}{Shift+Right}{Shift+Right}' }
```
说明一下这个功能的需求所在：例如使用明月拼音方案，要输入一个长词组，一开始只打了所有字的声母，随后发现第 2 个字的的韵母自动补全不对、需要手动指明韵母；此时希望用这个快捷键将光标移动到第 2 个字对应的位置之后，然后直接在键盘上敲它的韵母部分。同理会定义相应的 `Control+3`，`Control+4` 等快捷键，对第 3、4 个字补充输入码。双拼加形等方案也会有类似的补充输入需求。
