### ISSUE TITLE
五笔拼音问题候选字优先级问题

### ISSUE THREAD

**Issue by TomatoFryEggs** [rime/home#860]
之前通过https://github.com/rime/home/discussions/853，关闭了打简拼提示，现在还存在个提示问题，目前只发现在“惜”这个字，当打出“naj”时先提示了naj开头的拼音，而 惜（najg）这个字被放在了第二页。
![image](https://user-images.githubusercontent.com/9395814/130018911-0b7f71b0-3d7a-499c-85ec-66ab555d610e.png)
![image](https://user-images.githubusercontent.com/9395814/130018940-22417981-d17a-484d-99d7-b164dcc0be0e.png)
  在这里问下如何才能让五笔的反查提示总是在拼音前？

**Comment by lotem** [comment]
那个不能叫做反查，提示的是更长的五笔编码。因为不匹配当前输入，这些选项优先级较低。
如果不需要不完整的拼音（前缀形式），可以在拼音反查方案里关闭该功能：
```yaml
# pinyin_simp.custom.yaml
patch:
  translator/enable_completion: true
```
