### ISSUE TITLE
繁体中台湾变体的问题 opencc_config openCC 问题

### ISSUE THREAD

**Issue by KyleBing** [rime/home#882]
### 前言：
我已经阅读并大体了解了 OpenCC 的使用。
知道 `s2tw.json` 的配置是将简体转为繁体，再从繁体基础之上处理台湾独有的一些字词的对应。
基于这个文件： [TWVariants.txt](https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/TWVariants.txt)

### 问题：
有位五笔使用者的用户需要输简出繁的功能，配置方案也配置正确，`schema.yaml` 中配置是这样的

```yaml
tradition:
#  opencc_config: s2t.json
#  opencc_config: t2s.json   # 繁 -> 简【默认】
#  opencc_config: t2tw.json  # 繁 -> 台湾
#  opencc_config: t2hk.json  # 繁 -> 香港
#  opencc_config: s2tw.json  # 簡 -> 臺灣標準
  opencc_config: s2twp.json  # 簡 -> 臺灣片語
  option_name: zh_trad
```
也能正常输出繁体，也能正常转换台湾独有的变体文字，比如

![2021-09-17 14 08 58](https://user-images.githubusercontent.com/12215982/133735504-988e2442-8f65-465a-90bd-f66a3d6e0c28.jpg)

有些文字能正常转换，比如上图的 `吃`。但 `床` 这个单字却不可以，词组是可以正常转换的。

![2021-09-17 14 33 47](https://user-images.githubusercontent.com/12215982/133735759-31e86f61-f57f-43f9-9112-8cf509bb3bf1.jpg)

单字 `床` 却不行：
![2021-09-17 14 32 18](https://user-images.githubusercontent.com/12215982/133735805-3d60e276-4c98-46f3-9b55-5cfb3516f647.jpg)

找了半天不知道是哪出了问题，能否指个方向？或者你试一下可以吗？

`s2twp.json`
```json
{
  "name": "Simplified Chinese to Traditional Chinese (Taiwan standard, with phrases)",
  "segmentation": {
    "type": "mmseg",
    "dict": {
      "type": "ocd",
      "file": "STPhrases.ocd"
    }
  },
  "conversion_chain": [
    {
      "dict": {
        "type": "group",
        "dicts": [
          {
            "type": "ocd",
            "file": "STPhrases.ocd"
          },
          {
            "type": "ocd",
            "file": "STCharacters.ocd"
          }
        ]
      }
    },
    {
      "dict": {
        "type": "ocd",
        "file": "TWPhrases.ocd"
      }
    },
    {
      "dict": {
        "type": "ocd",
        "file": "TWVariants.ocd"
      }
    }
  ]
}

```

> 参考问题：
> 簡繁配置說明關於 OpenCC ：[https://github.com/rime/home/issues/420](https://github.com/rime/home/issues/420)
