### ISSUE TITLE
自动上屏功能不能实现

### ISSUE THREAD

**Issue by woshichuanqilz** [rime/home#926]
Linux上面使用

我查阅了一些资料加入了 max_code_length, auto_select

这个是我部分配置文件， 重启之后没有反映

现在比如我输入`vsks`， 第一个选项是"中空"， 剩下的四个是单字， 这样的情况是不是我的中空应该直接上屏呢， 还是说只有一个中空才能上屏， 如果需要去掉其他的单字， 这个应该怎么操作呢？

```
patch:
  schema/dependencies: {}
  speller/max_code_length: 4
  speller/auto_select: true
  switches:
    - name: ascii_mode
      reset: 0
      states: [ 中文, 西文 ]
    - name: emoji_suggestion
      reset: 1
      states: [ "Yes", "No" ]
    - name: full_shape
      states: [ 半角, 全角 ]
    - name: zh_simp
      reset: 1
      states: [ 漢字, 汉字 ]
    - name: ascii_punct
      states: [ 。，, ．， ]

```
