### ISSUE TITLE
请问如何实现用editor订制操作键？

### ISSUE THREAD

**Issue by AfeiAfeiAfei** [rime/home#948]
editor用以訂製操作鍵〔不支持import_preset:〕，鍵板鍵名同key_binder/bindings中的accept和send，效果定義如下：
confirm	上屏候選項
commit_comment	上屏候選項備注
commit_raw_input	上屏原始輸入
commit_script_text	上屏變換後輸入
commit_composition	語句流單字上屏
revert	撤消上次輸入
back	按字符回退
back_syllable	按音節回退
delete_candidate	刪除候選項
delete	向後刪除
cancel	取消輸入
noop	空

**Comment by shewer** [comment]
```yaml
patch: 
  editor/bindings:
     "Control+Return": commit_comment
     "Control+Delete": delete_candidate
```
