### ISSUE TITLE
能否在不同app中使用不同配色方案？

### ISSUE THREAD

**Issue by Forty-2** [rime/home#979]
macOS自带输入法可以在不同app中显示不同主题色。但是squirrel中在`custom.yaml`中加入以下内容不能生效：

``` yaml
# squirrel.custom.yaml
patch:
  style: mystyle1

  app_options:
    com.apple.Safari:
      style:
        color_scheme: mystyle2
```
是`app_options`不支持style还是我实现方法有误呢？
